### ISSUE TITLE
Documentation question: SQS messaging config

### ISSUE THREAD

**Issue by DirkLachowski** [spring-cloud/spring-cloud-aws#100]
I'm trying to consume elastic transcoder job status messages in a `@MessageMapping()` handler.

Using this configuration

    <beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:aws-context="http://www.springframework.org/schema/cloud/aws/context"
       xmlns:aws-messaging="http://www.springframework.org/schema/cloud/aws/messaging"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/cloud/aws/context
        http://www.springframework.org/schema/cloud/aws/context/spring-cloud-aws-context-1.0.xsd
        http://www.springframework.org/schema/cloud/aws/messaging
	   	http://www.springframework.org/schema/cloud/aws/messaging/spring-cloud-aws-messaging-1.0.xsd">
        
        <aws-messaging:annotation-driven-queue-listener />
        <aws-messaging:queue-messaging-template id="queueMessagingTemplate" />
        
    </beans>

i am unable to get the (json) payload mapped back to  a bean, e.g. this throws an exception:

    @MessageMapping("queue")
    public void handleJobCompleted(TranscoderMessage message) {
        // do something...
    }

 while

    @MessageMapping("queue")
    public void handleJobCompleted(String message) {
    	ObjectMapper mapper = new ObjectMapper();
    	try {
			System.out.println(mapper.readValue(message, TranscoderMessage.class).getMessage().toString());
		} catch (IOException e) {
			e.printStackTrace();
		}
    }
 
is executed. Looks as if there is no Jackson marshaller available to the `QueueMessageHandler`. But why? What part of the config am i missing?

**Comment by aemruli** [comment]
Hello @DirkLachowski which version of Jackson are you using ? We check for com.fasterxml.jackson.databind.ObjectMapper if that exists int eh class path and configure the JSON support. If you have Jackson 1.x (with different package name org.codehaus...) then this will not be picked up.

**Comment by DirkLachowski** [comment]
I'm using Jackson 2.4.4 (transitive import via spring-cloud-starter-config 1.0.3).

Bootstrapping via

    @SpringBootApplication
    @EnableRetry
    @EnableConfigurationProperties
    @EnableStatsdClient
    @ImportResource("classpath:/aws.xml")
    public class Application extends SpringBootServletInitializer {

	@Override
        protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
            return application.sources(Application.class);
        }
	
	public static void main(String[] args) throws Exception {
		SpringApplication.run(Application.class, args);
	}
    }

where `aws.xml` is the config from my first post.

**Comment by eliudiaz** [comment]
I am still having the same problem, is there any way to solve it????

**Comment by DirkLachowski** [comment]
@eliudiaz I'm reading the raw `String` payload and unmarshall it on my own (as in the last code block of my original post).

**Comment by aemruli** [comment]
Hello @eliudiaz, how do you send the message ? Through spring aws sqs template or differently ? By default we check that the contentType header is set and matches to "application/json", you might try to set the header and check if the message is properly deserialized.

**Comment by DirkLachowski** [comment]
@aemruli Could that be the reason why deserializing the message from ElasticTranscoder fails? For the SNS topic in question raw message delivery is disabled, so i suppose ETC is sending json payload. Anything i can do to verify this?

**Comment by alainsahli** [comment]
Hi @DirkLachowski you can try to disable the `StrictContentTypeMatch` on the `MappingJackson2MessageConverter` then it should not verify for a content type header anymore. Just add this bean in your configuration to configure the `QueueMessageHandler`:

```java
@Bean
public QueueMessageHandlerFactory queueMessageHandlerFactory() {
    QueueMessageHandlerFactory factory = new QueueMessageHandlerFactory();
    MappingJackson2MessageConverter jacksonMessageConverter = new MappingJackson2MessageConverter();
    jacksonMessageConverter.setSerializedPayloadClass(String.class);
    jacksonMessageConverter.setStrictContentTypeMatch(false);
    PayloadArgumentResolver payloadArgumentResolver = new PayloadArgumentResolver(jacksonMessageConverter);
    factory.setArgumentResolvers(Collections.<HandlerMethodArgumentResolver>singletonList(payloadArgumentResolver));

    return factory;
}

**Comment by ujjwal** [comment]
Hey! I am using S3->SQS events and the contentType isn't set to json. How do I inject that header?

**Comment by nickdk** [comment]
@ujjwal: Stumbled upon this question and recently also tried out S3->SQS->Spring @MessageMapping

I didn't find a way to immediately unmarshal to a bean since you don't have any control on the actual message but this is what I'm currently using to get information out of the S3 event, I think it's pretty convenient:

```java
    @MessageMapping("${upload.queue}")
    private void receiveMessage(String message, @Header("MessageId") String messageId, @Header("ApproximateReceiveCount") String approximateReceiveCount) throws IOException {
        LOGGER.info("Received MessageId: {}, ApproximateReceiveCount: {} ", messageId, approximateReceiveCount);

        String s3Url = extractS3Url(message);

        LOGGER.info("Retrieving new upload: {}", s3Url);
        Resource resource = resourceLoader.getResource(s3Url);
        resource.getInputStream();
        LOGGER.info("Received {} successfully", s3Url);
    }

    private String extractS3Url(String s3EventMessage) throws UnsupportedEncodingException {
        S3EventNotification.S3Entity s3Entity = S3EventNotification.parseJson(s3EventMessage).getRecords().get(0).getS3();
        return URLDecoder.decode("s3://" + s3Entity.getBucket().getName() + "/" + s3Entity.getObject().getKey(), "UTF-8");
    }
```
