### ISSUE TITLE
SQS: consuming messages one at a time and delay each consumption

### ISSUE THREAD

**Issue by gioiab** [spring-cloud/spring-cloud-aws#108]
Hi everybody,

I'm using Spring 4 with spring cloud aws to get messages from an SQS queue through the @MessageMapping annotation. Each message is related to external API calls and it's not possible, for example, to make <N> concurrent calls to this service. I would like to get one of the following two situations:
- the listener processes one message at time so that, when a new message comes the previous has already been processed;
- the listener processes one message when a certain time has passed from the previous receipt.

I've already tried to set the max number of messages: 

messageListenerContainerFactory.setMaxNumberOfMessages(1);

and to set the number of parallel processes:

```
@Bean
public SimpleAsyncTaskExecutor simpleAsyncTaskExecutor() {
    SimpleAsyncTaskExecutor simpleAsyncTaskExecutor = new SimpleAsyncTaskExecutor();
    simpleAsyncTaskExecutor.setConcurrencyLimit(SimpleAsyncTaskExecutor.NO_CONCURRENCY);
    return simpleAsyncTaskExecutor;
}
```

No one of these solutions works for me. How can I accomplish my objective?

**Comment by aemruli** [comment]
Hello @gioiab did you configure the task executor for the SimpleMessageListenerContainer ? In XML you have to use the task-executor attribute and in Java config you will have to use org.springframework.cloud.aws.messaging.config.SimpleMessageListenerContainerFactory#setTaskExecutor method. 

To be sure that you do not have any concurrency you should additionally synchronize the service access

**Comment by ty-dev** [comment]
Thanks, this achieved message processing with no concurrency for me.

**Comment by maciejwalkowiak** [comment]
👍
