### ISSUE TITLE
Support nested CloudFormation stacks in StackResourceRegistryFactoryBean

### ISSUE THREAD

**Issue by sfussenegger** [spring-cloud/spring-cloud-aws#113]
We use nested stacks quite a bit to make templates reusable. It would be great to have `ResourceIdResolver` support this. 

I've just made a prototype work extending `StackResourceRegistryFactoryBean` by joining logical resource ids, e.g. `NestedStack` and `NestedStack.NestedResource` or `NestedStack.AnotherNestedStack.AnotherResource`.

PS: Qualifying resources similarly with the stack name this could also be the solution for the `TODO` in `StackResourceRegistryDetectingResourceIdResolver`: "discuss whether to support more than one stack resource registry and how to deal with ordering/name conflicts". So the name of a resource would be `{stackName}.{logicalResourceId}` or simply `{logicalResourceId}` if the name is unique.

PPS: Honestly, it was quite annoying to work on this stuff as `StackResourceRegistryFactoryBean` doesn't really allow for customization: a lot of private methods, no access to private fields, package-private classes etc. I had to put classes in `org.springframework.*` packages just circumvent package-privacy and copy quite some private code. For instance, `StackResourceRegistryFactoryBean.convertToStackResourceMappings(..)` is `private static` while it could easily be `protected` for customization. Another example are both `StackNameProvider` implementations that are package-private, making it unnecessarily complicated to create a completely custom `ListableStackResourceFactory` implementation.

**Comment by aemruli** [comment]
This should be solved already now with #124 , otherwise please re-open.
