### ISSUE TITLE
Docs for all versions point to the same place

### ISSUE THREAD

**Issue by adrianboimvaser** [spring-cloud/spring-cloud-aws#118]
All Refence documentation links in http://cloud.spring.io/spring-cloud-aws/ point to the same url: http://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html. I'm looking for docs for current stable release (1.0.3) and can't find them.

**Comment by aemruli** [comment]
@dsyer can you have a look at this ?

**Comment by dsyer** [comment]
It's the same for all the spring cloud projects AFAIK. The tagged versions are only being saved (up to now at least) in the big Spring Cloud user guide (which includes this one).
