### ISSUE TITLE
Support for AWS kinesis

### ISSUE THREAD

**Issue by maxsap** [spring-cloud/spring-cloud-aws#119]
Currently in order to listen for events from the Kinesis we have two options:
- Use spring-cloud-aws provided SNS/SQS integration (adding additional setup)
- Add manually a listener using the AWS SDK.
  I think it would be really helpful if you could support AWS Kinesis using the awesome listener annotation.

**Comment by maciejwalkowiak** [comment]
Kinesis support has been implemented in Spring Cloud Stream project: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis
