### ISSUE TITLE
Stack for i-fxxxxxx does not exist

### ISSUE THREAD

**Issue by ujjwal** [spring-cloud/spring-cloud-aws#121]
```Caused by: com.amazonaws.AmazonServiceException: Stack for i-fxxxxxx does not exist (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: eb98acd2-a384-11e5-a02b-dd982610db0f)```

Is there a way to use IAM role to pass credentials but not have it associated with a CloudFormation stack? I just want to use S3 and SQS, but encountering errors associated with ElasticCache etc too. 

Is there a way to restrict the AWS services it should try instantiating a bean for?

**Comment by douglaspribeiro** [comment]
for me worked

spring-boot property:
cloud.aws.stack.auto = false
cloud.aws.credentials.instanceProfile = false

**Comment by ujjwal** [comment]
```
@EnableAutoConfiguration(exclude = {
        ElastiCacheAutoConfiguration.class,
        MailSenderAutoConfiguration.class,
        StackResourceRegistryFactoryBean.class,
        ContextStackAutoConfiguration.class,
        StackResourceRegistry.class,
        ProxyCachingConfiguration.class,
        SnsWebConfiguration.class,
})
```

Thank @douglaspribeiro - I ended up excluding certain classes from it loading.

**Comment by aemruli** [comment]
Closing as there is not much we can do here. Feel free to reopen with more information.

**Comment by msanchezavalos** [comment]
@douglaspribeiro Your solution was on point! Thank you

**Comment by emilianotebes** [comment]
@douglaspribeiro THANKS!!!
