### ISSUE TITLE
Typo in artifactId spring-cloud-aws-depednencies

### ISSUE THREAD

**Issue by sfussenegger** [spring-cloud/spring-cloud-aws#129]
There is a typo in the artifactId of `spring-cloud-aws-depednencies` [in the 1.0.x branch](https://github.com/spring-cloud/spring-cloud-aws/blob/1.0.x/spring-cloud-aws-dependencies/pom.xml)

**Comment by aemruli** [comment]
Hi @sfussenegger we will not ship any 1.0.x release anymore. Therefore I close this issues, the typo has been fixed in 1.1.0
