### ISSUE TITLE
Allow for configureable # of messages size in SQS listener

### ISSUE THREAD

**Issue by karthikguda** [spring-cloud/spring-cloud-aws#133]
Would be nice if there was a way to set the maximum number of messages to pull from SQS. Currently it seems like only one message can be pulled off the queue.

**Comment by aemruli** [comment]
Hello @karthikguda you can specify the maxNumberOfMessages attribute on the container. An example in XML is <aws-messaging:annotation-driven-queue-listener max-number-of-messages="8"/>

You can provide a number between 1 and 10 (this is the maximum of SQS). If you are using Java, then have a look at https://github.com/spring-cloud/spring-cloud-aws/blob/3bede576cfd242f556c8b5f9127377fc9f63d6c7/spring-cloud-aws-integration-test/src/test/java/org/springframework/cloud/aws/messaging/JavaMessageListenerContainerAwsTest.java you can set the maximum number of messages in the SimpleMessageListenerContainerFactory class
