### ISSUE TITLE
Allow for developer to specify if messages pulled from SQS should be deleted off the queue

### ISSUE THREAD

**Issue by karthikguda** [spring-cloud/spring-cloud-aws#134]
Seems like the QueueMessageChannel auto deletes messages off the SQS queue. This might not be desirable to all clients. Consider allowing this to be configurable.

**Comment by aemruli** [comment]
Hello @karthikguda, you can specifiy (with the latest milestone release) the deletionPolicy within the annotation. 

e.g. @SqsListener(value = "myQueue", deletionPolicy = SqsMessageDeletionPolicy.NEVER) would not delete the messages, you can manually delete them by having a acknowledgment parameter. 

As a example 

public static class ManualDeletionPolicyTestListener {

	

		@SqsListener(value = "ManualDeletionQueue", deletionPolicy = SqsMessageDeletionPolicy.NEVER)
		public void receive(String message, Acknowledgment acknowledgment)  {
			acknowledgment.acknowledge().get();
		}
	}

Please re-open the ticket in case of any questions.

**Comment by wadechandler** [comment]
This isn't related to the annotation; at least not now, nor did the comment look related. I think this should be considered a bug. It makes QueueMessagingTemplate fairly useless as it just instantly deletes the message from the queue which is what one almost never wants. QueueMessagingTemplate uses QueueMessageChannel which in turn deletes the message as soon as taking it from the queue. The SimpleMessageListenerContainer uses the SQS client directly, and is why it doesn't have this issue. **Too, this is not documented, and one could say makes QueueMessagingTemplate dangerous as one must either read the code of the project or find out the hard way by having code delete messages before they are processed before they realize they don't want to use QueueMessagingTemplate**.

Too, and most certainly a topic for another issues, or multiple ones, feature requests, QueueMessagingTemplate needs to be more thorough allowing delete and other items. It would be handy too if it supported a back-off strategy, perhaps configurable, like the SimpleMessageListenerContainer, as it then supports the developer in a more utilitarian fashion.

**Comment by wadechandler** [comment]
Currently I'm working around this bug by extending QueueMessagingTemplate, overriding resolveMessageChannel, extending QueueMessageChannel, and overriding receive(long). So, a little copy and paste with deletion, but it doesn't seem like what one wants to do long term.

**Comment by wadechandler** [comment]
I see. There is no handle to delete the message returned, so technically the whole model just doesn't work. It really needs to return a wrapper, and the template would need to do something similar. I was trying to work around with some extensions, but it isn't practical as there needs to be other information returned or set with parameters (out parameters).

**Comment by gerosa** [comment]
+1

**Comment by apexkid** [comment]
Is this resolved? Do we have a fix or ETA for fix?

**Comment by wadechandler** [comment]
Considering it is closed, I'm guessing the answer is no @apexkid. I see no response to my points either. I assume that means one would need to put together a PR, or create workarounds; which is what I did. I actually made use of the underpinnings of the annotations, SimpleMessageListenerContainer, and converters, to allow similar use without a fully custom solution, and that worked out well for me back when I commented on this.

**Comment by apexkid** [comment]
It is quite unfortunate that this library doesn't implement the basic functionality correctly.  SQS workflows are highly dependent on the message acknowledgement which prevents message loss if a server goes down after reading a message. Without this feature available first hand, i do not feel this library is reliable to use. I will stick to AWS java sdk.

**Comment by bisoldi** [comment]
Can I clarify this....Am I to understand that the Spring Cloud AWS SQS integration does not currently allow manually acknowledging the message?  I'm having some trouble getting the Acknowledgment object to be properly deserialized.  That does not seem to be the same issue as this ticket, but if the feature doesn't currently work, I don't want to keep banging my head against the wall....

**Comment by frockert** [comment]
any resolutions to this? I am facing this issue atm as I need to manually acknowledge / delete a message from dead letter queue and there seems to be no way with spring cloud

**Comment by frockert** [comment]
can this be reopen or someone share if there is any resolutions to this? I am facing this issue atm as I need to manually acknowledge / delete a message from dead letter queue and there seems to be no way with spring cloud

**Comment by bisoldi** [comment]
@frockert Can’t you use the SimpleMessageListenerContainer?  That’s how I’ve implemented it and it works perfectly.  In my app, Messages are deleted off the queue manually in a separate batch process, in a separate thread.

**Comment by frockert** [comment]
I can't see on SimpleMessageListenerContainer anything exposed to delete/acknowledge the message, might be missing something. If you have an example on how you doing it that would be great @bisoldi

**Comment by bisoldi** [comment]
@frockert Below is some code I use that works and allows manual acknowledge/delete of the SQS messages.

Not being a Spring guru, it was excessively difficult to get this just right, with all of the Spring projects/dependencies, there was, it seemed, a lot of overlap and a lot of different instructions out there on how to get this right.  Additionally, getting the messageConverter code and the PayloadArgument stuff just right was also painful, it took me quite a while.  Bottom line, I felt your pain.

Just some caveats, I did not include:

- The exact maven coordinates for this.  Unfortunately, my pom is a bit of a mess and it will be difficult for me to isolate exactly which dependencies provide everything needed, though I provided some clues to get you started.
- The values for each of the setters below, you should be able to figure out what values are appropriate for your use case.

I hope this helps, let me know of any questions.

```
@Bean
@Primary
public AmazonSQSAsync amazonSQSAsync(@Autowired AWSCredentialsProvider credentials) {
    return AmazonSQSAsyncClientBuilder.standard()
        .withCredentials(credentials)
        .withExecutorFactory(null)
        .withRegion(region)
        .build();
}

@Bean
@Primary
public AWSCredentialsProvider buildDefaultAWSCredentialsProvider() {
    return new DefaultAWSCredentialsProviderChain();
}

@Bean("IngestJsonConsumerBean")
@Primary
public SimpleMessageListenerContainer simpleMessageListenerContainer(@Autowired AmazonSQSAsync amazonSQSAsync, 
@Autowired QueueMessageHandler queueMessageHandler) {

    SimpleMessageListenerContainer smlc = new SimpleMessageListenerContainer();
    smlc.setWaitTimeOut(20);
    smlc.setAmazonSqs(amazonSQSAsync);
    smlc.setMessageHandler(queueMessageHandler);
    smlc.setBeanName("IngestJsonConsumerBean");
    smlc.setMaxNumberOfMessages(sqsMaxMessages);
    smlc.setQueueStopTimeout(sqsThreadAwaitTerminationSeconds * 1000L);
    smlc.setTaskExecutor(buildSqsThreadPoolExecutor());
        
    return smlc;
}

private ThreadPoolTaskExecutor buildSqsThreadPoolExecutor() {
    ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        
    executor.setCorePoolSize(sqsThreadCorePoolSize);
    executor.setAllowCoreThreadTimeOut(sqsThreadCoreTimeout);
    executor.setWaitForTasksToCompleteOnShutdown(sqsThreadWaitForTasksOnShutdown);
    executor.setAwaitTerminationSeconds(sqsThreadAwaitTerminationSeconds);
    executor.setMaxPoolSize(sqsThreadMaxPoolSize);
    executor.setKeepAliveSeconds(sqsThreadTimeoutSeconds);
    executor.setThreadNamePrefix(sqsThreadName + "-");
        
    executor.initialize();
        
     return executor;
}

@Bean
@Primary
public QueueMessageHandler queueMessageHandler(@Autowired AmazonSQSAsync sqsClient, @Autowired QueueMessageHandlerFactory queueMessageHandlerFactory) {
    queueMessageHandlerFactory.setAmazonSqs(sqsClient);
    QueueMessageHandler queueMessageHandler = queueMessageHandlerFactory.createQueueMessageHandler();

    return queueMessageHandler;
}
	
@Bean
@Primary
public QueueMessageHandlerFactory queueMessageHandlerFactory() {
    QueueMessageHandlerFactory factory = new QueueMessageHandlerFactory();
    MappingJackson2MessageConverter messageConverter = new MappingJackson2MessageConverter();
    messageConverter.setSerializedPayloadClass(String.class);

    //set strict content type match to false
    messageConverter.setStrictContentTypeMatch(false);
    PayloadArgumentResolver payloadArgumentResolver = new PayloadArgumentResolver(messageConverter);
    AcknowledgmentHandlerMethodArgumentResolver acknowledgmentResolver = new AcknowledgmentHandlerMethodArgumentResolver("Acknowledgment");
    factory.setArgumentResolvers(Arrays.asList(acknowledgmentResolver, payloadArgumentResolver));

    return factory;
}
```

As for dependencies, here are the Spring dependencies I have.  You will also need the AWS SDK.

```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-aws</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-aws-messaging</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-test</artifactId>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-aws-autoconfigure</artifactId>
</dependency>

<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-dependencies</artifactId>
			<version>${spring-cloud.version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
<repositories>
	<repository>
		<id>spring-milestones</id>
		<name>Spring Milestones</name>
		<url>https://repo.spring.io/milestone</url>
		<snapshots>
			<enabled>false</enabled>
		</snapshots>
	</repository>
</repositories>
```
