### ISSUE TITLE
MappingJackson2MessageConverter Not Extracting The SQS Payload

### ISSUE THREAD

**Issue by kurron** [spring-cloud/spring-cloud-aws#139]
I'm using Spring Cloud AWS 1.1.0 M2 and JSON message conversion is not working properly for me.  What I see in the debugger is that `org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal` is asking the `ObjectMapper` to deserialize too much of the JSON document.  This is what gets sent to the mapper:

```
{
  "payload" : {
    "foo" : "foo"
  },
  "headers" : {
    "id" : "6db7d430-1966-72b9-96c5-609d420b1a18",
    "timestamp" : 1458068178719
  }
}
```
My object only contains the `foo` field.  I would assume that only the content associated with the `payload` key needs to be sent to the mapper.  I'm using `org.springframework.messaging.support.MessageBuilder` along with `org.springframework.cloud.aws.messaging.core.QueueMessagingTemplate.convertAndSend()` so I don't think I'm screwing up the assembly of the message.  My only other thought is that a serialization view is supposed to get configured and used somehow.

**Comment by demboos** [comment]
Hi,

I had the very same problem. In my case the solution was to send the message using
convertAndSend(String destinationName, T payload, Map<String, Object> headers)

instead of using the MessageBuilder.withPayload(...)

Cheers,

**Comment by kurron** [comment]
I think I'm doing something similar to what demboos did but I'm still not seeing the conversion happening correctly.  Here is my Spock test:

```
@IntegrationTest
@ContextConfiguration( classes = Application, loader = SpringApplicationContextLoader )
class SqsGatewayIntegrationTest extends Specification implements GenerationAbility {

    @Autowired
    QueueMessagingTemplate template

    @Autowired
    ApplicationProperties configuration

    def 'success message'() {
        given: 'valid environment'
        assert template
        assert configuration

        and: 'a valid message'
        def message = MessageBuilder.withPayload( new ProcessingCommand( foo: 'foo' ) ).build()

        when: 'message is sent'
        template.convertAndSend( configuration.queueName, message )

        then:
        Thread.sleep( 1000 )
    }
}
```

**Comment by kurron** [comment]
I **finally** understood what demboos meant. I've got things working now.  Here is the working form of the test:

```
    def 'success message'() {
        given: 'valid environment'
        assert template
        assert configuration

        and: 'a valid message'
        def message = new ProcessingCommand( foo: 'foo' )

        when: 'message is sent'
        template.convertAndSend( configuration.queueName, message )

        then:
        Thread.sleep( 1000 )
    }
```
I still think that we have an issue if we can't take already assembled message and send it.  Am I wrong?

**Comment by aemruli** [comment]
@kurron if you use the MessageBuilder, then you have to use the method org.springframework.messaging.core.MessageSendingOperations#send(org.springframework.messaging.Message<?>). In this case you also have to set the content-type header to allow for deserialization. 

Our recommendation is to use convertAndSend with the plain object you want to be serialized and send over the queue.

I am closing this issue as there is not much we can do here. Feel free to re-open in case of any questions

**Comment by juanmbellini** [comment]
@aemruli Thank you very much. Would be great if this is well documented.
