### ISSUE TITLE
XSD document not located

### ISSUE THREAD

**Issue by doom777** [spring-cloud/spring-cloud-aws#140]
http://stackoverflow.com/questions/29682242/the-matching-wildcard-is-strict-but-no-declaration-can-be-found-for-element-aw

Basically, spring for some reason can't access the xsd. I looked through everything, but couldn't find an error. It can't be only me.

**Comment by artembilan** [comment]
Maybe this one: http://stackoverflow.com/questions/20656424/eclipse-gradle-projects-spring-xml-validation/20657440#20657440
?

**Comment by doom777** [comment]
Not it:

    <natures>
		<nature>org.springframework.ide.eclipse.core.springnature</nature>
		<nature>org.eclipse.m2e.core.maven2Nature</nature>
		<nature>org.eclipse.jem.workbench.JavaEMFNature</nature>
		<nature>org.eclipse.wst.common.modulecore.ModuleCoreNature</nature>
		<nature>org.eclipse.wst.common.project.facet.core.nature</nature>
		<nature>org.eclipse.jdt.core.javanature</nature>
		<nature>edu.umd.cs.findbugs.plugin.eclipse.findbugsNature</nature>
	</natures>

**Comment by artembilan** [comment]
OK.
With IntelliJ IDEA there is no problems, because it always resolves XSDs from the classpath.

But I see your concern in the Internet: http://www.springframework.org/schema/cloud/
All those AWS XSDs must be placed to their own directory, like we have, for example, with Spring Integration: http://www.springframework.org/schema/integration/

**Comment by doom777** [comment]
The solution is definitely not putting the xsd's on the internet. Either the STS already resolves XSDs from the classpath, and here there was a specific problem, or the solution must be to fix STS. 

I think you should look through carefully to make sure it's not your configuration issue, and if definately not, open a ticket with STS on this.

After all, it's not vanilla Eclipse who would know to look in spring.schemas file...

**Comment by aemruli** [comment]
@dsyer is there a way to upload the XSDs during the build process ? Should I open a ticket in Spring Build ?

**Comment by dsyer** [comment]
@aemruli I honestly don't know. The XSDs are on a physical server somewhere that I don't have access to any more. Bamboo builds probably have access somehow, but that doesn't help us here. This week @trevormarshall is on vacation, but maybe he'll have time to respond when he gets back.

The original poster has a problem with STS, but that should (and does) work fine without the XSD being physically resolvable on the internet. My guess is he needs to look into how he's opening the XML files.

**Comment by aemruli** [comment]
Closing this for now. There is not much we can do here. XSD files should be auto-resolved by the IDE

**Comment by rcotta** [comment]
For those looking for a solution, changing the xsd declaration to http://www.springframework.org/schema/cloud/spring-cloud-aws-context.xsd should work.

It seems that documentation at http://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html (by today) points to a wrong location.
