### ISSUE TITLE
mvn install throws gpg command error

### ISSUE THREAD

**Issue by Cuneytt** [spring-cloud/spring-cloud-aws#143]
'mvn package' builds sucessfully but 'mvn install' ends with a gpg error:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project spring-cloud-aws-dependencies: Unable to execute gpg command: Error while executing process. Cannot run program "gpg.exe": CreateProcess error=2, The system cannot find the file specified -> [Help 1]
`

**Comment by aemruli** [comment]
Hi @Cuneytt the build uses gpg to sign the artifacts, but only if the central profile is activated. Can you please run mvn install without the "central" profile enabled.

**Comment by Cuneytt** [comment]
Thank you
