### ISSUE TITLE
How to get the MessageId with mailSender.send ?

### ISSUE THREAD

**Issue by borehack** [spring-cloud/spring-cloud-aws#144]
In order to track message (with bounce / complaints) I need the MessageId from AWS from the mailSender.send method. How do I get that messageId, any ideas? Would be great to have that feature.

**Comment by borehack** [comment]
my solution for the problem is like so : 
http://www.borehack.com/2016/04/24/spring-cloud-aws-ses-message-id.html
but thats maybe not the best way .. woulud be much better if that could be part of the sender class.

**Comment by aemruli** [comment]
@borehack you can not get the message id with the Mailsender as there is no return value. But you can now get the message id by using the JavaMailSender. The message id is set to the MimeMessage after sending the message. 

Example is here 

 MimeMessage mimeMessage = ...;
 mailSender.send(mimeMessage);
mimeMessage.getMessageID();
