### ISSUE TITLE
ContextResourceLoaderConfiguration direct dependency to AmazonS3Client

### ISSUE THREAD

**Issue by borehack** [spring-cloud/spring-cloud-aws#145]
If one only want to use SES or SNS Service why there are services configured in the context package that need the AmazonS3Client class? That should be changed.

**Comment by cemo** [comment]
+1

**Comment by aemruli** [comment]
@borehack I added a check for the auto-configuration. Without the S3 client you should now not get the resource loader configuration. 
If you don't use auto-configuration, then the client is anyways only configured if you explicitly configure it (through xml or java config)
