### ISSUE TITLE
Module structure 

### ISSUE THREAD

**Issue by borehack** [spring-cloud/spring-cloud-aws#146]
spring-cloud-aws-autoconfigure module has a dependency to spring-cloud-aws-context and context has every aws services needed. with this configuration all aws services get configured but I only want to configure lets say SNS. how is this possible?

**Comment by PedroAlvarado** [comment]
This is all spring-boot goodness. Therefore, you can cherry pick which auto-configuration you want excluded via `@EnableAutoConfiguration(exclude={SomeAutoConfiguration.class})` or `spring.autoconfigure.exclude` as described [here](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-auto-configuration.html).

**Comment by borehack** [comment]
thanks, didn't know this feature...
