### ISSUE TITLE
Feature request SqsListener: Support multiple queues configured by placeholder

### ISSUE THREAD

**Issue by msparer** [spring-cloud/spring-cloud-aws#147]
I would like to configure multiple queues by property placeholder. E.g. having a property like this

`com.myproject.queues=queueOne,queueTwo`

and use it in `SqsListener` like that:
`@SqsListener(value = "#{'${com.myproject.queues}'.split(',')}"`

Currently `QueueMessageHandler` iterates through all constant expressions of `SqsListener.value()` and adds them one by one - by invoking the `toString` after resolve. The array gets resolved fine, but the queue name then of course looks like `[Ljava.lang.String;@4e25154f`.

I think this could be easily supported by checking if the resolved result is an array or list, and if it is, add all to the `Set` of queues. E.g.

```
private Set<String> resolveDestinationNames(String[] destinationNames) {
		Set<String> result = new HashSet<>(destinationNames.length);

		for (String destinationName : destinationNames) {
			result.addAll(resolveName(destinationName)); // addAll instead of simple add
		}

		return result;
	}

	private Collection<String> resolveName(String name) { // return collection instead of string
		if (!(getApplicationContext() instanceof ConfigurableApplicationContext)) {
			return name;
		}

		ConfigurableApplicationContext applicationContext = (ConfigurableApplicationContext) getApplicationContext();
		ConfigurableBeanFactory configurableBeanFactory = applicationContext.getBeanFactory();

		String placeholdersResolved = configurableBeanFactory.resolveEmbeddedValue(name);
		BeanExpressionResolver exprResolver = configurableBeanFactory.getBeanExpressionResolver();
		if (exprResolver == null) {
			return name;
		}
		Object result = exprResolver.evaluate(placeholdersResolved, new BeanExpressionContext(configurableBeanFactory, null));
		if (result != null) {
			// check for array or collection and return accordingly
			...
		} else {
			return Arrays.asList(name);
		}
	}
```

**Comment by alainsahli** [comment]
HI @msparer,

Thanks for reporting this. I added this feature for the next minor release (1.1.1.RELEASE), see d06cf9cdf595ce4f96eaad96af38c859d9afc75e.

**Comment by HagarJNode** [comment]
I'm running some tests on this, with two queues, but somehow messages are not ending at the listener. Did someone see multiple queues working? 
When I only use one queue in the "com.myproject.queues" value messages are coming through.
Using breakpoints in QueueMessageHandler indicate that resolveDestinationNames do give a set with my two queues.

**Comment by tmnuwan12** [comment]
I had a use case where we wanted to listen to queues in different region. It will make sense to have the placeholder value to accommodate  multi region queues also instead of just queue name.
