### ISSUE TITLE
Auto Configuration inconsistency in the MailSenderAutoConfiguration

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-aws#151]
I would like to use SC-AWS auto-configuration but I may not be interested in SES, SQS or any thing else. In fact I am interested only in S3. 

The `MailSenderAutoConfiguration` relies on the `AmazonSimpleEmailService`. But actually I can't exclude SES because `@ConditionalOnMissingAmazonClient(AmazonSimpleEmailService.class)` has bad implementation in face of `OnMissingAmazonClientCondition` and its cast like `(Class<?>) amazonClientClass)`.

would be better when that top-level `@ConditionalOnClass` will be like:
````java
@ConditionalOnClass({MailSender.class, AmazonSimpleEmailService.class})
````
Although the `OnMissingAmazonClientCondition` must be fixed as a logic in the `OnClassCondition`.

**Comment by artembilan** [comment]
OK. To exclude SES (and others) I was made to do this:
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-aws</artifactId>
	<exclusions>
		<exclusion>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-ses</artifactId>
		</exclusion>
		<exclusion>
			<groupId>javax.mail</groupId>
			<artifactId>javax.mail-api</artifactId>
		</exclusion>
		<exclusion>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-support</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-elasticache</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.amazonaws</groupId>
			<artifactId>elasticache-java-cluster-client</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```
I fact with this I'm only interested in S3.

What is the problem that I can be interested in `javax.mail`, e.g. some other mail service, not SES.
But anyway I'd like do not have `AmazonSimpleEmailService` on board. So, exclusion of `aws-java-sdk-ses` should be enough for me. But that doesn't work because of an error during `MailSenderAutoConfiguration` process:
```
Caused by: java.lang.ClassCastException: java.lang.ClassNotFoundException cannot be cast to java.lang.Class
	at org.springframework.cloud.aws.context.annotation.OnMissingAmazonClientCondition.matches(OnMissingAmazonClientCondition.java:36)
```
Just because the `attributes.get("value")` is like:
```
java.lang.ClassNotFoundException: com.amazonaws.services.simpleemail.AmazonSimpleEmailService
```

That's why I suggest to move `AmazonSimpleEmailService` class condition into the top `@ConditionalOnClass({MailSender.class, AmazonSimpleEmailService.class})` instead.

And also fix `OnMissingAmazonClientCondition` do not explode with `ClassNotFoundException`.

For this purpose you should use there this method:
```
/**
	 * Retrieve all attributes of all annotations of the given type, if any (i.e. if
	 * defined on the underlying element, as direct annotation or meta-annotation).
	 * Note that this variant does <i>not</i> take attribute overrides into account.
	 * @param annotationName the fully qualified class name of the annotation
	 * type to look for
	 * @param classValuesAsString  whether to convert class references to String
	 * @return a MultiMap of attributes, with the attribute name as key (e.g. "value")
	 * and a list of the defined attribute values as Map value. This return value will
	 * be {@code null} if no matching annotation is defined.
	 * @see #getAllAnnotationAttributes(String)
	 */
	MultiValueMap<String, Object> getAllAnnotationAttributes(String annotationName, boolean classValuesAsString);
```

**Comment by artembilan** [comment]
Thank you @aemruli for the fix!
But how about `OnMissingAmazonClientCondition` it is still in bug if someone doesn't use `@ConditionalOnClass` and don't have an appropriate jar in classpath?
Or do you consider that as a separate commit!

**Comment by aemruli** [comment]
@artembilan I hope that the separate commit https://github.com/spring-cloud/spring-cloud-aws/commit/25703e294f1bce722b6e8e44604267e1bf708dd7 fixes that. Or did you have something different in mind ?

**Comment by artembilan** [comment]
Perfect turnaround!
LGTM :smile:
