### ISSUE TITLE
Support VPC Endpoints

### ISSUE THREAD

**Issue by hoegertn** [spring-cloud/spring-cloud-aws#152]
I did not find a configuration property to change the endpoint of Autowired client object. 
We use S3 VPC endpoints in private subnets and do not have access to the S3 API

Is this supported or is this a missing feature?

If you give me a hint I can try to create a PR.

**Comment by hoegertn** [comment]
@aemruli any ETA for this or a hint where I can fix it?

**Comment by aemruli** [comment]
What kind of support are you looking for specifically @hoegertn ? As far as I understood, for VPC endpoint there is a special bucket policy. We currently do not support creating bucket. 

Please let me know if there is some further support needed so that we can think about it.

**Comment by hoegertn** [comment]
I am searching for a way to set the endpoint of the AWS client. As I understand it I have to set a different client endpoint when using VPC endpoints to access S3 buckets.

**Comment by hoegertn** [comment]
Also, this feature is needed when I try to use S3ninja to emulate S3 locally. 

I think in class `org.springframework.cloud.aws.core.config.AmazonWebserviceClientFactoryBean` the endpoint should be derived from an application property if set.

**Comment by maciejwalkowiak** [comment]
Thanks for reporting. Support for custom endpoints will be added in 2.3. This issue is superseeded by #570.
