### ISSUE TITLE
S3 client shouldn't follow the same region policy as other clients

### ISSUE THREAD

**Issue by edudar** [spring-cloud/spring-cloud-aws#153]
S3 is substantially different in this matter from many if not all other AWS services. S3 bucket names are  unique not only within an account but across all S3 system. While it's possible to create bucket in specific region they all appear in the same list since S3 is Global. This means that for servers in 4 regions there should be 4 different buckets with replication setup in between. This leads to more configuration on application and management levels. That's quite non-standard case I think. I'd suggest to use `us-east-1` (aka US Standard) or some prorety-configured one as default region for this specific client. There's an option to set other region if required available already.

**Comment by aemruli** [comment]
Hello @edudar, you are right that the S3 buckets are globally available (which SQS queues are as well by using the queue urls). We configure the S3 client with the same region like other clients, therefore the client connects to the S3 endpoint in which normally the application is executed (if the application is hosted on a EC2 instance). Of course, the client can access all the buckets. 
We have taken this approach to have a unified configuration model for all S3 clients, feel free to comment if that leads to a problem for you.

**Comment by edudar** [comment]
I found this 
> Of course, the client can access all the buckets. 

not to be correct and the exact reason why this issue has been created. All our buckets are in `us-east` but a service I was working on at that time was distributed across 4 other regions. As result only instances from `us-east` were able to read files properly. The rest were given 404. As workaround I've created S3 client manually with specific region and it works flawlessly.

**Comment by rehevkor5** [comment]
@edudar is right. If using virtual-hosted style URL, you should use the url for the standard region (s3.amazonaws.com). If you instead use the url for a different region (eg. my-bucket.s3-us-west2.amazonaws.com), and your bucket isn't hosted in that region, you'll get 301 "Moved Permanently" status response as described here http://docs.aws.amazon.com/AmazonS3/latest/dev/Redirects.html#RedirectsPermanentRedirection and here http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

**Comment by edudar** [comment]
@aemruli can you please elaborate on the last comments? Thanks.

The setup that is more or less standard I guess is that you have a bucket named, let's says, `data` with some files your application needs. Then you create EC2 instances in all, for example, US regions: 2 east and 2 west. Your services start up, go to predefined `data` bucket, get files and live happily.

However, this gets a little cumbersome with the way S3 client is setup out of the box. If you'd like to do the same setup with `spring-cloud-aws` only 1 server will be happy, the rest won't get any files from `data` as described in comments above. 

So there are two ways to solve this issue:
1) override S3 client and specifically tell it what region `data` bucket was created in (as I did at the moment)
2) create one bucket per region in those regions like `us-east-1-data`, `us-west-2-data`, etc and sync their content (complexity and space multiplies as multi-region deployment expands)

I can't say that (2) is preferred solution, that why I went with (1).

**Comment by gregturn** [comment]
This isn't addressed by this is it?

https://github.com/spring-cloud/spring-cloud-aws/pull/96

**Comment by edudar** [comment]
@gregturn seems so. Although proxy is a way more bulky solution while serving wider purpose obviously. Also, it sits there for more than a year. However if your team decides that's the way to go - then let it be.

**Comment by gregturn** [comment]
Not my team. I tried to use this project and it failed due to a regional issue so I coded the redirect. Haven't convinced the project lead to bite.

**Comment by edudar** [comment]
Well, it does not work in some specific use-cases. I have `TransferManager` for uploading/downloading files from S3. It is described here: http://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html#_uploading_with_the_transfermanager. It uses 'pure' client that is not proxied and I can't proxy it because it's package-visible only.

**Comment by gregturn** [comment]
Are you saying the proxy needs a different visibility to leverage it for transgerManager?

Not sure given the method just creates an instance right there, not allowing the object to be a transformed Spring bean.

**Comment by edudar** [comment]
Opening it to the public with help for sure. I don't understand yet why default S3 client created by auto-configuration can't be proxied this way by default. Right now it's secret knowledge that one has to find out somehow, as it's not anywhere in docs
