### ISSUE TITLE
@MessageMapping for websocket end point

### ISSUE THREAD

**Issue by sunilsp54** [spring-cloud/spring-cloud-aws#154]
**Problem:**
Currently When `<aws-messaging:annotation-driven-queue-listener   />` is enabled @MessageMapping requires a physical aws SQS queue name  and @MessageMapping cannot be used for mapping websocket end points.

Since `@SqsListner`  is introduced, `@MessageMapping` annotation should not be used for mapping SQS listner.

This way websocket end points and sqs listner annotation can be used in a standard way.
@aemruli your input on this will be a great help.

**Comment by sunilsp54** [comment]
is duplicate of #77

**Comment by alainsahli** [comment]
Hi @sunilsp54,

This is actually just a warning. I have to leave this warning otherwise there would be no feedback if a queue that should exist is not found.

You could just raise the log level to `ERROR` for this class if you don't want to see this warning.

**Comment by stnor** [comment]
So what if the actual SQS topic did exist? This behavior is not great. Why should the SQS Annotation resolver even look in @Controller:s?

**Comment by sunilsp54** [comment]
@stnor as you said  SQS Annotation resolver should not look in @Controller:s? . The conflict here is @MessageMapping is used for mapping both "WebSocket end point" and "AWS SQS Listener ".

May be to support backward compatibility,  SQS Annotation resolver should look in @Controller:s and decide @MessageMapping is actually intended for SQS Listener or not , as you suggested here #171
