### ISSUE TITLE
ElastiCacheCacheConfigurer bean factory should be annotated with ConditionalOnMissingBean

### ISSUE THREAD

**Issue by lopesmcc** [spring-cloud/spring-cloud-aws#159]
The user should be allowed to use his own `CachingConfigurer`, however `spring-cloud-aws` is forcing the use of `ElastiCacheCacheConfigurer`.

A solution would be to annotate the ElastiCacheCacheConfigurer factory (`ElastiCacheCachingConfiguration#cachingConfigurer`) with `ConditionalOnMissingBean(CachingConfigurer.class)`.

**Comment by psabharwal123** [comment]
@aemruli @lopesmcc @spencergibb this issue is fixed by PR 179 - https://github.com/spring-cloud/spring-cloud-aws/pull/179 

when will this be merged?

**Comment by psabharwal123** [comment]
@maciejwalkowiak please have a look at this
