### ISSUE TITLE
Config Property for AWS Stack Name Ignored

### ISSUE THREAD

**Issue by noelob** [spring-cloud/spring-cloud-aws#162]
Hi, 

I need to resolve AWS Cloudformation stack resource names from within my application. For Dev/Prod (running in EC2), this can be automatic, but for integration testing (running locally), I need to provide the stack name manually. Each developer has their own stack, so the integration test stack name cannot be hardcoded.

From reading the [docs](http://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html#_managing_cloud_environments), it seems this should be feasible by:
1. Adding `@EnableStackConfiguration` to my Java config, without specifying `stackName`; the app should 'just work' when running in EC2
2.  Running integration tests with a system property `cloud.aws.stack.name=my-personal-stack`. Per the Spring Boot [external config docs](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html), this should set the stack name

However, there is always an attempt to automatically determine the stack name, which fails the start up of the integration test spring context. Setting `cloud.aws.stack.name=my-personal-stack` explicitly in `application.properties` also makes no difference. I've only been able to have it work with `@EnableStackConfiguration(stackName="my-personal-stack")` which doesn't work for my use case.

I'm using spring-cloud-aws 1.1.0. Am I doing something wrong here? Seems like`cloud.aws.stack.name` is not being honoured at all.

Thanks,
Noel

**Comment by noelob** [comment]
Rather interestingly, it seems to work if I remove `@EnableStackConfiguration` and provide just config

    cloud.aws.stack.name=my-personal-stack
    cloud.aws.stack.auto=false

I'll test adding `cloud.aws.stack.auto=true` to the dev/prod profiles to confirm it works based on my use case above

**Comment by alainsahli** [comment]
Hi @noelob,

The requests that are sent are not requests to find out the stack name but to list the resources of the stack.

I also tried to remove the stackName from our IntegrationTest class (https://github.com/spring-cloud/spring-cloud-aws/blob/master/spring-cloud-aws-integration-test/src/test/java/org/springframework/cloud/aws/IntegrationTestConfig.java#L35) and specify the stack name with the property `cloud.aws.stack.name` and it worked.

Could you send us the stack trace you get at startup?

**Comment by aemruli** [comment]
Closing as there is no feedback.
