### ISSUE TITLE
404 Error Missing Reference Docs

### ISSUE THREAD

**Issue by geekpgh** [spring-cloud/spring-cloud-aws#168]
The Spring cloud AWS site has a link to the 1.1 reference documents. That link is broken. It points here: http://cloud.spring.io/spring-cloud-static/spring-cloud-aws/1.1.1.RELEASE/

That link results in a 404.

**Comment by alainsahli** [comment]
Hi @dsyer,

Could you have a look in to that?

**Comment by garyrussell** [comment]
The [current project page](http://cloud.spring.io/spring-cloud-aws/) correctly points to the [1.1.3](http://cloud.spring.io/spring-cloud-static/spring-cloud-aws/1.1.3.RELEASE/) reference document, and the link is correct.

**Comment by dsyer** [comment]
Thanks Gary
