### ISSUE TITLE
SimpleStorageResource private

### ISSUE THREAD

**Issue by tamrsolutions** [spring-cloud/spring-cloud-aws#169]
I am trying to get some data out of the SimpleStorageResource,   is there a reason this class is private?

**Comment by alainsahli** [comment]
Hi @tamrsolutions 

This class is package protected because it is meant for internal usage. We didn't want to expose this class because one should just use the Resource interfaces provided by Spring to favour portability.

What is you use case? What would you like to access?

**Comment by aemruli** [comment]
closing as there is no use-case mentioned for that. 
Feel free to open with new comments.
