### ISSUE TITLE
Websockets and SQS @MessageHandler conflicts

### ISSUE THREAD

**Issue by stnor** [spring-cloud/spring-cloud-aws#171]
I think there is a problem with QueueMessageHandler and how it handles the @MessageMapping annotation.

I don't know how conflicting @MessageMappings are supposed to handled, but I think the solution in #77 is somewhat of a hack (assuming that SQS should be used and logging a stack trace if the queue doesn't exist).

Suggested improvements to the existing solution:
1) The stack trace is removed from the warning log.
2) QueueMessageHandler.getMappingForMethod should perhaps look at the handlerType and if it's a Spring MVC@Controller, the method should return null in order to avoid conflicts with WebSockets use of @MessageMapping. This would at least solve #154 

Thanks,
Stefan

**Comment by stnor** [comment]
I get this exception every ten seconds (on a websocket @MessageListener)

2016-09-19 22:46:26 W   SimpleMessageListenerContainer - An Exception occurred while polling queue '/topic/livereporting'. The failing operation will be retried in 10000 milliseconds
java.lang.NullPointerException: null
	at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer$AsynchronousMessageListener.run(SimpleMessageListenerContainer.java:255) ~[spring-cloud-aws-messaging-1.1.1.RELEASE.jar:1.1.1.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

**Comment by alainsahli** [comment]
Hi @stnor

Thanks for reporting this issue.

The problem is that I cannot add a check for the handler type and ignore the mapping method if it is on a controller because that would break existing projects that use @MessageMapping on controllers. We recently introduced the annotation `@SqsListener` and we plan to remove the support for @MessageMapping but this will only happen in version 2.0.

In the meantime, what you could do, is extend the `QueueMessageHandler` and override the method `getMappingForMethod` to ignore controllers:

```java
public class MyQueueMessageHandler extends QueueMessageHandler {
  
  @Override
  protected MappingInformation getMappingForMethod(Method method, Class<?> handlerType) {
    if (AnnotationUtils.findAnnotation(handlerType, Controller.class) != null) {
      return null;
    } else {
      return super.getMappingForMethod(method, handlerType);
    }
  }

}
```

Then you have to register you customized message handler using the [SimpleMessageListenerContainerFactory](http://cloud.spring.io/spring-cloud-static/spring-cloud-aws/1.1.0.RELEASE/#_the_simplemessagelistenercontainerfactory).

As for your exception, this should only happen if you have a queue with name `/topic/livereporting`, is it the case?

**Comment by stnor** [comment]
Hi @alainsahli 
Thanks for the response and suggested workaround.
I will have to remove the "  <aws-messaging:annotation-driven-queue-listener task-executor="sqsExecutor" auto-startup="false" wait-time-out="20" max-number-of-messages="10" />" in favor for the The SimpleMessageListenerContainerFactory, right?

I don't understand the last question. Does it have to do with the name of the web socket endpoint?

**Comment by stnor** [comment]
I had to leave the aws-messaging:annotation-driven-queue-listener in and added
`  <bean class="org.springframework.cloud.aws.messaging.config.SimpleMessageListenerContainerFactory">
    <property name="autoStartup" value="false"/>
    <property name="taskExecutor" ref="sqsExecutor"/>
    <property name="waitTimeOut" value="20"/>
    <property name="maxNumberOfMessages" value="10"/>
    <property name="queueMessageHandler" ref="controllerIgnoringQueueMessageHandler"/>
  </bean>`

I still get this on startup though:
`2016-09-20 21:32:27 W   o.s.c.a.m.l.SimpleMessageListenerContainer - The queue with name '/topic/livereporting' does not exist.
org.springframework.messaging.core.DestinationResolutionException: The specified queue does not exist for this wsdl version. (Service: AmazonSQS; Status Code: 400; Error Code: AWS.SimpleQueueService.NonExistentQueue; Request ID: 5f46a1c0-aa51-58c2-b372-f19b3b5813f1); nested exception is com.amazonaws.services.sqs.model.QueueDoesNotExistException: The specified queue does not exist for this wsdl version. (Service: AmazonSQS; Status Code: 400; Error Code: AWS.SimpleQueueService.NonExistentQueue; Request ID: 5f46a1c0-aa51-58c2-b372-f19b3b5813f1)
	at org.springframework.cloud.aws.messaging.support.destination.DynamicQueueUrlDestinationResolver.resolveDestination(DynamicQueueUrlDestinationResolver.java:81) ~[spring-cloud-aws-messaging-1.1.1.RELEASE.jar:1.1.1.RELEASE]
	at org.springframework.cloud.aws.messaging.support.destination.DynamicQueueUrlDestinationResolver.resolveDestination(DynamicQueueUrlDestinationResolver.java:37) ~[spring-cloud-aws-messaging-1.1.1.RELEASE.jar:1.1.1.RELEASE]
	at org.springframework.messaging.core.CachingDestinationResolverProxy.resolveDestination(CachingDestinationResolverProxy.java:88) ~[spring-messaging-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer.queueAttributes(AbstractMessageListenerContainer.java:292) [spring-cloud-aws-messaging-1.1.1.RELEASE.jar:1.1.1.RELEASE]
	at org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer.initialize(AbstractMessageListenerContainer.java:270) [spring-cloud-aws-messaging-1.1.1.RELEASE.jar:1.1.1.RELEASE]
	at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer.initialize(SimpleMessageListenerContainer.java:110) [spring-cloud-aws-messaging-1.1.1.RELEASE.jar:1.1.1.RELEASE]
	at org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer.afterPropertiesSet(AbstractMessageListenerContainer.java:250) [spring-cloud-aws-messaging-1.1.1.RELEASE.jar:1.1.1.RELEASE]`

**Comment by stnor** [comment]
Unfortunately SimpleMessageListenerContainer cannot be overridden due to it's design. And AbstractMessageListenerContainer is package-private.

I guess I have to live with the exception on startup...?

Here's what I ended up with:
```xml
 <task:executor id="sqsExecutor" pool-size="5" />

  <bean id="queueMessagingTemplate" class="org.springframework.cloud.aws.messaging.core.QueueMessagingTemplate">
    <constructor-arg ref="amazonSqsAsyncClient"/>
  </bean>

  <bean id="controllerIgnoringQueueMessageHandler" class="se.nomp.sqs.ControllerIgnoringQueueMessageHandler"/>

  <bean id="amazonSqsAsyncClient" class="com.amazonaws.services.sqs.AmazonSQSAsyncClient">
    <constructor-arg ref="awsCredentials"/>
  </bean>

  <bean class="org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer">
    <property name="messageHandler" ref="controllerIgnoringQueueMessageHandler"/>
    <property name="autoStartup" value="false"/>
    <property name="taskExecutor" ref="sqsExecutor"/>
    <property name="waitTimeOut" value="20"/>
    <property name="maxNumberOfMessages" value="10"/>
    <property name="amazonSqs" ref="amazonSqsAsyncClient"/>
  </bean>

  <bean class="org.springframework.cloud.aws.messaging.config.SimpleMessageListenerContainerFactory">
    <property name="autoStartup" value="false"/>
    <property name="taskExecutor" ref="sqsExecutor"/>
    <property name="waitTimeOut" value="20"/>
    <property name="maxNumberOfMessages" value="10"/>
    <property name="queueMessageHandler" ref="controllerIgnoringQueueMessageHandler"/>
  </bean>
```

**Comment by stnor** [comment]
I got rid of all warnings and exceptions by using this config:

```xml
  <task:executor id="sqsExecutor" pool-size="5" />

  <bean id="queueMessagingTemplate" class="org.springframework.cloud.aws.messaging.core.QueueMessagingTemplate">
    <constructor-arg ref="amazonSqsAsyncClient"/>
  </bean>

  <bean id="controllerIgnoringQueueMessageHandler" class="se.nomp.sqs.ControllerIgnoringQueueMessageHandler"/>

  <bean id="amazonSqsClient" class="com.amazonaws.services.sqs.AmazonSQSClient">
    <constructor-arg ref="awsCredentials"/>
    <property name="endpoint" value="https://sqs.eu-west-1.amazonaws.com"/>
  </bean>

  <bean id="amazonSqsAsyncClient" class="com.amazonaws.services.sqs.AmazonSQSAsyncClient">
    <constructor-arg ref="awsCredentials"/>
    <property name="endpoint" value="https://sqs.eu-west-1.amazonaws.com"/>
  </bean>

  <bean class="org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer">
    <property name="messageHandler" ref="controllerIgnoringQueueMessageHandler"/>
    <property name="autoStartup" value="false"/>
    <property name="taskExecutor" ref="sqsExecutor"/>
    <property name="waitTimeOut" value="20"/>
    <property name="maxNumberOfMessages" value="10"/>
    <property name="amazonSqs" ref="amazonSqsAsyncClient"/>
  </bean>

  <bean class="org.springframework.cloud.aws.messaging.config.SimpleMessageListenerContainerFactory">
    <property name="autoStartup" value="false"/>
    <property name="taskExecutor" ref="sqsExecutor"/>
    <property name="waitTimeOut" value="20"/>
    <property name="maxNumberOfMessages" value="10"/>
    <property name="queueMessageHandler" ref="controllerIgnoringQueueMessageHandler"/>
  </bean>
```
