### ISSUE TITLE
SqsListener doesn't support method parameter of org.springframework.messaging.Message

### ISSUE THREAD

**Issue by wadechandler** [spring-cloud/spring-cloud-aws#175]
The SqsListener docs state it supports an unannotated parameter of type org.springframework.messaging.Message which allows one to receive the full message being processed. This fails in every way I have tried to use it/combination of parameters. Is this supposed to work, or are the docs wrong?

**Comment by wadechandler** [comment]
I am using 1.1.3.RELEASE, but even the 1.1.1 javadocs stated this

**Comment by wadechandler** [comment]
I should state that the logic arrives at a place where it is trying to convert the payload into the message which is wrong, and it instead, it should just hand it off, and as such, even if a converter is used, it wouldn't "convert" anything as it has already built a GenericMessage instance.

**Comment by frommeyerc** [comment]
This is still in the JavaDoc of `@SqsListener` as of Version 1.2.2.RELEASE and still not supported out of the box.
