### ISSUE TITLE
Breaking API Change in 1.1.3

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-aws#176]
a86650ab8296696d05805d7213849159f64f0a4b introduced a breaking API in`QueueMessagingTemplate`.

http://stackoverflow.com/questions/39840002/amazon-sqs-outbound-channel-adapter-wont-initialize

Normally, Spring projects don't make such changes in a point (1.1.x) release; we make best-effort attempts to maintain backwards compatibility so people can upgrade point releases without pain.

It would be ideal if it's possible to reintroduce the old ctors to avoid this breaking change.

Normally, if an API has to change, we bump the minor version, e.g. 1.2.0 in this case; for a case like this (change to `AmazonSQSAsync` from `AmazonSQS` we would normally support both in a point release and possibly deprecate the older version (or leave it as an option). Of course, if the underlying library no longer supports the sync version, then that wouldn't be an option and we'd go the route of the minor version change.

**Comment by aemruli** [comment]
@garyrussell it was not intended to have the breaking code change. With release 1.1.4 you should have the restored constructor signature. For the > 1.1.4 we are using an instance of check to see if we have an sync or async client. In the former case we will not support timeouts.

Closing this ticket feel free to re-open if you still have compatibility problems with 1.1.4
