### ISSUE TITLE
SQS runs super slow on MacOS Sierra if cloud.aws.credentials.instanceProfile=true

### ISSUE THREAD

**Issue by haskovec** [spring-cloud/spring-cloud-aws#183]
The version of AWS SDK shipped with Spring Cloud AWS runs super slow on MacOS Sierra. It sounds like if a newer version was shipped with Spring Cloud this issue would be resolved. Here is an issue that I opened on the AWS SDK relating to this:

https://github.com/aws/aws-sdk-java/issues/885

Is there any possibility of getting an update to update AWS to 1.11.20s in the near future. I could manually override it in my pom, but for me the value proposition of Spring Boot and Spring Cloud is knowing that the Dependencies have all been tested together, so I would prefer to not override them.

I am currently running Camden.SR1.

**Comment by aemruli** [comment]
@haskovec Spring Cloud AWS 1.1.4 will contain the AWS release 1.11.83 which should solve your issue. See cc1faaaae81edb6f6b9179bd009f682d74e39bb0 commit.
