### ISSUE TITLE
spring-cloud-aws-autoconfigure dependencies and module organization

### ISSUE THREAD

**Issue by ksperling** [spring-cloud/spring-cloud-aws#195]
`spring-cloud-aws-autoconfigure` seems to pull in too many dependencies that could be made optional or in some cases removed

* `spring-cloud-aws-actuator` should be optional
  * `org.springframework.boot:spring-boot-actuator` can be removed (transitive dep of `spring-cloud-aws-actuator`)
  * `com.amazonaws:aws-java-sdk-cloudwatch` can be removed  (transitive dep of `spring-cloud-aws-actuator`)
* `spring-cloud-aws-context` should be optional

Ideally the cache (e.g. `aws-java-sdk-elasticache`, ...) and mail (`javax.mail`, `aws-java-sdk-ses`) related dependencies would also be (re)moved. This could be simplified for the user by splitting the integrations out of `spring-cloud-aws-context` into e.g. `spring-cloud-aws-cache` and `spring-cloud-aws-mail`, and then having those modules pull in the relevant third party deps.

This way the `spring-cloud-aws-autoconfigure` could act more like normal Boot autoconfiguration modules that configures what's present, rather than pulling in dependencies itself (it seems like something of a hybrid between providing autoconfig and acting as a 'starter' at the moment).

An even better option might be to move the autoconfiguration classes into the relevant modules that they actually configure (the dependency on `spring-boot-autoconfigure` could be optional in each of those modules). `spring-cloud-aws-autoconfigure` could then be removed entirely or be replaced by a `spring-cloud-aws-starter`.

**Comment by aemruli** [comment]
@ksperling thanks for your suggestions. I already refined the dependencies. With regards to re-arranging the modules: Currently Spring Boot is "optional" for the 1.x release line, once we have a mandatory dependency on all modules to Spring Boot we will likely collapse the auto-configure module into the other modules. 
With 2.x we also plan to drop the entire XML support and be more aligned with Spring Boot in general.

**Comment by jayanderson** [comment]
Along these lines `spring-cloud-aws-autoconfigure` assumes we are using cloud formation. If we aren't either it will be missing permissions to access `describeStackResources` or it will have a different error when it is unable to get the name of the stack. I'd prefer this fail more gracefully.

**Comment by maciejwalkowiak** [comment]
2.3 will introduce following changes: 

- Actuator dependency has been removed in https://github.com/spring-cloud/spring-cloud-aws/pull/604
- CloudFormation support will be disabled by default https://github.com/spring-cloud/spring-cloud-aws/issues/573
