### ISSUE TITLE
region from context-region not injected when building CloudFrontClient with Builder

### ISSUE THREAD

**Issue by doom777** [spring-cloud/spring-cloud-aws#198]
Recent aws-java has deprecated building clients via constructors, and now recommends creating by Builder classes. At least AmazonCloudFrontClientBuilder is not injected with the spring's RegionProvider, and crashes. 

The workaround is to get a RegionProvider by autowiring, and then passing its Region to the Builder manually. Please fix so no workaround is needed, and it works automatically like it did with constructors.

**Comment by aemruli** [comment]
We are not having a CloudFrontClient at all, we have changed alle the construction to the builder pattern introduced in AWS SDK. Please re-open if you think that we can changes anything else.
