### ISSUE TITLE
Interest in support for retrieving config from EC2 Parameter Store?

### ISSUE THREAD

**Issue by wcurrie** [spring-cloud/spring-cloud-aws#207]
I recently learned about the EC2 [Parameter Store](https://aws.amazon.com/blogs/compute/managing-secrets-for-amazon-ecs-applications-using-parameter-store-and-iam-roles-for-tasks/). An example use case: distributing a database password to a spring boot app running in ECS or EC2. The password can be stored encrypted under KMS (envelope encryption). Access can be restricted based on the IAM role assigned to the container (ECS) or instance (EC2).

Seems this could be quite useful as a secret distribution mechanism for spring boot apps running on AWS. Not as elegant, feature rich and polished as Hashicorp's vault but perhaps good for simple use cases or where you don't want to run a vault cluster (backed by a consul cluster).

There's a spike with more detail in [aws-ssm-demo](https://github.com/wcurrie/aws-ssm-demo).

**Comment by atmani** [comment]
Any progress on that request ? It will be helpful to have a feature where we can get encrypted value from ParameterStore.

**Comment by btsteve** [comment]
Sounds like a great feature.

**Comment by jkuipers** [comment]
I wrote something like this recently. The current code can be found here: https://gitlab8.trifork.nl/jorisk/spring-cloud-aws-param-store

I'd be happy to contribute it.

**Comment by mrcasablr** [comment]
@jkuipers  Would you be able to convert this into a PR for the upstream folks to merge?

**Comment by jkuipers** [comment]
I will have a look at what it would take to turn this into a proper pull request.

**Comment by dsyer** [comment]
Closed via #308

**Comment by jkuipers** [comment]
Would be nice if the updated docs could be republished as well: my code has been integrated in a republished RC2, but as there are no docs no one will know that nor how to use it.

**Comment by dsyer** [comment]
That should be done now. Might take a while for caches to clear.
