### ISSUE TITLE
Move from travis-ci to circleci

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-aws#211]

**Comment by alainsahli** [comment]
Hi @spencergibb, why should we move to circleci?

**Comment by spencergibb** [comment]
We've started to move the other projects for various reasons. We'd like to be consistent.

**Comment by aemruli** [comment]
@spencergibb is there anything left to do ? As #242 already provided an initial circle ci implementation.

**Comment by spencergibb** [comment]
Closed by #242
