### ISSUE TITLE
ResourceLoaderBeanPostProcessor causes eager load for beans

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-aws#228]
The `ResourceLoaderBeanPostProcessor` has dependency on the `AmazonS3` and if we declare the last one in our own custom `@Configuration` all the beans from this class will be loaded pretty early. The rest of `BeanPostProcessor`s might be missed.

See https://jira.spring.io/browse/INT-4281 for more info.

Not sure how to fix logic in the `ResourceLoaderBeanPostProcessor`, but that was always bad to have dependency from other beans in the `BeanPostProcessor`...

**Comment by alltej** [comment]
I get this same issue. Any work around if using the `ResourceLoaderBeanPostProcessor`?
