### ISSUE TITLE
Add support for AWS FIFO SQS Queues

### ISSUE THREAD

**Issue by louisalexander** [spring-cloud/spring-cloud-aws#246]
Currently, sending to a FIFO queue is impossible due to the following error:

> [SimpleAsyncTaskExecutor-3] 13 Jul 2017 10:16:49,628 DEBUG PublishSubscribeChannel [{}]: preSend on channel 'errorChannel', message: ErrorMessage [payload=org.springframework.messaging.MessageDeliveryException: The request must contain the parameter MessageGroupId. (Service: AmazonSQS; Status Code: 400; Error Code: MissingParameter; Request ID: 332c9b37-699b-57c3-bf90-cad6ea83dd7d); nested exception is com.amazonaws.AmazonServiceException: The request must contain the parameter MessageGroupId. (Service: AmazonSQS; Status Code: 400; Error Code: MissingParameter; Request ID: 332c9b37-699b-57c3-bf90-cad6ea83dd7d), headers={id=a67ac1e9-911b-7263-ae14-979473f90d25, timestamp=149995000009628}]

For definition of FIFO SQS Key Terms, see http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html#FIFO-queues-understanding-logic

**Comment by osamahq** [comment]
+1

**Comment by IbrahimAl-Zreqat** [comment]
+1

**Comment by qaisalazzeh** [comment]
+1

**Comment by raedhabbab** [comment]
+1
