### ISSUE TITLE
Populating cache name dynamically in @EnableElastiCache annotation

### ISSUE THREAD

**Issue by deepak-malik** [spring-cloud/spring-cloud-aws#248]
Right now we have to hard code the cache cluster name in `@EnableElastiCache` annotation, something like below
`@EnableElastiCache({@CacheClusterConfig(name = "sample-cache", expiration = 3600)})`

This becomes a problem when we have to pick up cache cluster name based on environment or spring profile. Just wanted to check if currently there is a way to achieve this, or maybe fetch this name from properties file based on the environment. 

I understand that one way could be to create separate ElastiCacheConfiguration per environment. 
Any thought to do this in a better way?

**Comment by julianohsf** [comment]
I am facing the same problem. Is there any solution already?

**Comment by paskos** [comment]
Same here. we have 30+ cache-clusters, we don't use cloudformation and I'd like to be able to do something like:

`@EnableElastiCache(@CacheClusterConfig(name ="${cloud.aws.elasticache.cache-cluster-id}", expiration = 3600))`

**Comment by maciejwalkowiak** [comment]
This will be fixed in 2.3 as ElastiCache will configurable through configuration properties classes.
