### ISSUE TITLE
About AmazonS3 Presigned URL 

### ISSUE THREAD

**Issue by elluard** [spring-cloud/spring-cloud-aws#249]
Hello, 

I am developing my service via Spring Cloud AWS.

I have some question 

How can I get the presigned URL from amazon S3? 

thank you.

**Comment by pacey** [comment]
Autowire the AmazonS3 bean and call the `generatePresignedUrl` method http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#generatePresignedUrl-com.amazonaws.services.s3.model.GeneratePresignedUrlRequest-

**Comment by juanmbellini** [comment]
Hi!
Is there any way to make this without autowiring the AmazonS3 bean? 
Could it be added as a feature?

Thank you very much!

**Comment by spencergibb** [comment]
Closing as answered.
