### ISSUE TITLE
Nothing is published to Cloudwatch

### ISSUE THREAD

**Issue by Frantch** [spring-cloud/spring-cloud-aws#250]
Hello,

I have included the CloudWatchMetricAutoConfiguration in my config
`@Import({loudWatchMetricAutoConfiguration.class })
`

and add the bean
```
@Bean
  public MetricsEndpointMetricReader metricsEndpointMetricReader(MetricsEndpoint metricsEndpoint) {
```

But if I put a breakpoint in CloudWatchMetricAutoConfiguration's cloudWatchMetricWriter bean it is never called. and in turn my metric are never sent to cloudwatch

**Comment by aemruli** [comment]
closing as the CloudWatch integration will be moved to micrometer.io in combination with Spring Boot 2.0.
