### ISSUE TITLE
Typo 'not' instead of 'no': Minor error log message typo - for people with grammar OCD.

### ISSUE THREAD

**Issue by dostiharise** [spring-cloud/spring-cloud-aws#254]
`Caused by: java.lang.IllegalStateException: There is not EC2 meta data available, because the application is not running in the EC2 environment. Region detection is only possible if the application is running on a EC2 instance`

Refer to classes: `org.springframework.cloud.aws.core.regionEc2MetadataRegionProvider:39`, and `org.springframework.cloud.aws.core.region.Ec2MetadataRegionProviderTest:57`.

**Comment by aemruli** [comment]
merged with #255
