### ISSUE TITLE
Annotation based sqs configuration for spring boot 1.5.6

### ISSUE THREAD

**Issue by selvakumar25** [spring-cloud/spring-cloud-aws#258]
I m integration aws sqs in my spring boot 1.5.6 and may i know whether you have suupport for annotation based integration of sqs

**Comment by selvakumar25** [comment]
I m integration aws sqs in my spring boot 1.5.6 and may i know whether you have suupport for annotation based integration of sqs

**Comment by pacey** [comment]
Yep they sure do - http://cloud.spring.io/spring-cloud-static/spring-cloud-aws/1.2.1.RELEASE/#_annotation_driven_listener_endpoints

**Comment by aemruli** [comment]
@selvakumar25 yes sure we do as @pacey wrote. Have a look at https://github.com/spring-cloud/spring-cloud-aws/blob/master/spring-cloud-aws-integration-test/src/test/java/org/springframework/cloud/aws/messaging/BootMessageListenerContainerAwsTest.java for a concrete example
