### ISSUE TITLE
How do you trigger @SqsListener (or SimpleMessageListenerContainer) to Error on Invalid Queue Names?

### ISSUE THREAD

**Issue by pluttrell** [spring-cloud/spring-cloud-aws#269]
I have a `CommandLineRunner` that creates a queue if it's missing. I also have a class that has a method with `@SqsListener("name-of-queue")` and an `@Configuration` class with the config listed below - note that I can't find any documentation on how wire/configure the necessary support for `@SqsListener`, so please advise if this configuration is not correct. 

The trouble is that it takes a moment for AWS to actually create the queue and in that timeframe the `SimpleMessageListenerContainer` is initialized _without_ any errors. But because the queue doesn't exist, it _never_ binds to it, so message never get retrieved from the queue unless I restart the app.

What is recommended here? Is there a way to get `SimpleMessageListenerContainer` to error out if the name of the queue in the `@SqsListener` isn't found? Or better yet, is there a way to get it to write a warning to the log and then retry shortly thereafter?

```
@Bean
public SimpleMessageListenerContainerFactory simpleMessageListenerContainerFactory(AmazonSQSAsync amazonSqs) {
  SimpleMessageListenerContainerFactory factory = new SimpleMessageListenerContainerFactory();
  factory.setAmazonSqs(amazonSqs);
  factory.setMaxNumberOfMessages(5);
  return factory;
}

@Bean
public QueueMessageHandler queueMessageHandler(AmazonSQSAsync amazonSQSAsync) {
  QueueMessageHandlerFactory factory = new QueueMessageHandlerFactory();
  factory.setAmazonSqs(amazonSQSAsync);
  return factory.createQueueMessageHandler();
}

@Bean
public SimpleMessageListenerContainer simpleMessageListenerContainer(SimpleMessageListenerContainerFactory simpleMessageListenerContainerFactory, QueueMessageHandler queueMessageHandler) {
  SimpleMessageListenerContainer container = simpleMessageListenerContainerFactory.createSimpleMessageListenerContainer();
  container.setMessageHandler(queueMessageHandler);
  container.setWaitTimeOut(20);
  return container;
}
```

**Comment by pluttrell** [comment]
@aemruli Wondering if you might know the answer of this?

**Comment by aemruli** [comment]
@pluttrell sorry for the very late reply here. You can set the auto start to false (https://github.com/spring-cloud/spring-cloud-aws/blob/3020a7d07abc7d2c418cd94860e2640d81c628bf/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/listener/AbstractMessageListenerContainer.java#L221) and thens start the container later. With that you do not need to re-start your app. 

You can also start/stop queue individually if it is only necessary for a few queues see 
https://github.com/spring-cloud/spring-cloud-aws/blob/c42717a8fe03ce87d0e5fe81fb5ea7dfa7a05066/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/listener/SimpleMessageListenerContainer.java#L257

I am closing this issue as we have #305 to improve the error handling.

**Comment by sajanlamsal** [comment]
@aemruli,
Just a quick question,  How do I start the container later after the auto start has been set to false?

**Comment by gezerk** [comment]
@aemruli 
You can call `start(String logicalQueueName)` on the SimpleMessageListenerContainer:
https://github.com/spring-cloud/spring-cloud-aws/blob/c42717a8fe03ce87d0e5fe81fb5ea7dfa7a05066/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/listener/SimpleMessageListenerContainer.java#L237
