### ISSUE TITLE
DynamicQueueUrlDestinationResolver is throwing away the resolved resource id

### ISSUE THREAD

**Issue by born2snipe** [spring-cloud/spring-cloud-aws#274]
The resource Id resolved from `ResourceIdResolver.resolveToPhysicalResourceId(...)` is **not** being used when trying to create/query SQS for the queue. Instead the original value passed into the method is being used [here](https://github.com/spring-cloud/spring-cloud-aws/blob/master/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/support/destination/DynamicQueueUrlDestinationResolver.java#L70).

It looks like this change was introduced after version [`1.1.3.RELEASE`](https://github.com/spring-cloud/spring-cloud-aws/blob/dd03080583290d4f7a4b0f74a6094cb7094540ea/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/support/destination/DynamicQueueUrlDestinationResolver.java#L64).

**Comment by aemruli** [comment]
should be resolved with f9d1d8a46a53faedc1970073db1c459d5046c7ab
