### ISSUE TITLE
Lost ability to define custom region

### ISSUE THREAD

**Issue by zonybob** [spring-cloud/spring-cloud-aws#278]
In spring-cloud-aws 1.1.0 and earlier versions, I was able to provide a custom region via my own regions.xml file (see http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/SDKGlobalConfiguration.html#REGIONS_FILE_OVERRIDE_SYSTEM_PROPERTY).

In 1.1.1 (and later) I can no longer do this because it is trying to parse my region name as an enum. I believe this is related to the following lines/commit...

https://github.com/spring-cloud/spring-cloud-aws/commit/d4fae43ddc5edbc66d3e56dfc23480b94df10a9a#diff-acdbba6b36a6cbe1af0b12d9d90d16db

I am effectively requesting a revisiting of #36 as I believe that PR has since been undone.

Any help is greatly appreciated as I am currently going to have to rollback to some old versions of Spring dependencies.

**Comment by bgroff** [comment]
Has there been any effort to look into this issue? There are unpublished regions that should be allowed to be used without hacking/recompiling the spring jar. Also it would be nice to not need to update dependencies when a new published region goes online.

**Comment by spencergibb** [comment]
PRs welcome.

**Comment by maciejwalkowiak** [comment]
Spring Cloud AWS supports only regions supported by AWS SDK. If there is a newer AWS SDK version available than one configured by Spring Cloud AWS it's possible to overwrite version by importing AWS SDK bom. Documentation on how to do it will come together with #482
