### ISSUE TITLE
Add Java8 Time Message Converter Support

### ISSUE THREAD

**Issue by pluttrell** [spring-cloud/spring-cloud-aws#288]
As of version 1.2.1, the SQS Sending/Receiving support does not support the Java 8 Time types whereas SpringBoot 1.5.x with a couple of dependencies automatically adds support for them and SpringBoot 2.0.0.Mx support them out of the box.

This is a feature request to provide the same support, perhaps leveraging the ObjectMapper provided by the auto configuration.

**Comment by pluttrell** [comment]
@aemruli Is there an easy way to add support for this manually to the current release? I've attempted several hacks and none have worked.

**Comment by aemruli** [comment]
@pluttrell you should be able now to use Java 8 types (if the corresponding Jackson Modules are in your classpath). If you want to re-configure the Jackson Objectmapper (for other reasons, then you can do that as well see https://github.com/spring-cloud/spring-cloud-aws/blob/5b49482eb2d5cdf1caaf6ad9b66ebb6488ad3d1a/spring-cloud-aws-messaging/src/test/java/org/springframework/cloud/aws/messaging/core/QueueMessagingTemplateTest.java#L179 as an example).
