### ISSUE TITLE
Add scheduler support for SQS queue listener

### ISSUE THREAD

**Issue by superhomine** [spring-cloud/spring-cloud-aws#29]
@MessageMapping is aggressively polling messages at a rate of between 16 and 26 times a second on a single EC2 node. 

It would be great to be able to specify the scheduled rate (ideally using cron expression) at which messages are pull from the queue.

**Comment by alainsahli** [comment]
Hi @superhomine 

Thanks for your input. It's true that from a cost perspective the current implementation is not ideal. Especially when the queue is empty most of the time.

In my opinion there should be a configurable wait time when the queue is empty. As long as messages are received by the container it should poll as fast as possible. Would this solution be ok for you?

What I don't like with the scheduler approach, is that the application could easily run into troubles if the polling rate is to slow and the queue becomes always bigger and bigger.

**Comment by rpk** [comment]
@alainsahli Shouldn't using SQS long polling partially resolve this cost issue?  Set wait-time-out to up to 20 seconds when creating the queue listener.  That should result in ~4320 requests / day, 1.5MM requests per year.  Running 10 hosts on the free tier, this comes out to $0.16/mo.

```.xml
<aws-messaging:annotation-driven-queue-listener wait-time-out="20">
```

**Comment by alainsahli** [comment]
@rpk Yes, you are right. This solution solves the issue.

**Comment by stnor** [comment]
I do not think this issue is solved. I just had a $200 bill because of the default value. Please set wait time to 1 or something if the queue is empty.
