### ISSUE TITLE
Enhancement: support native SQS messages in listener argument

### ISSUE THREAD

**Issue by MrBuddyCasino** [spring-cloud/spring-cloud-aws#295]
The @SqsListener annotation should support com.amazonaws.services.sqs.model.Message as method parameter. 

We want to store incoming events in DynamoDB including payload and headers, and the conversions that are done in QueueMessageUtils are making this considerably harder (String to MimeType / UUID etc.). Also we want to store events just like they come in, without any conversions or processing so there are less chances for bugs.

**Comment by jarc0der** [comment]
Let me guys discover this one 
@maciejwalkowiak

**Comment by maciejwalkowiak** [comment]
Go for it @jarc0der !
