### ISSUE TITLE
(spring-cloud-aws-jdbc) Add maxNumberOfRetries (failover concept) to EnableRdsInstance annotation

### ISSUE THREAD

**Issue by prasadus92** [spring-cloud/spring-cloud-aws#299]
This is a feature request.

Right now, the number of retries during the failover can only be configured using the bean XML. The easy to use annotation `EnableRdsInstance` allows us to configure only the read replica support. If we don't like to have this by default, it would be nice to have at least a boolean flag to enable or disable a default value.

Thank you.

**Comment by renanreismartins** [comment]
@maciejwalkowiak RDS was one the biggest motivations I landed on this project. Could I take this one?

**Comment by maciejwalkowiak** [comment]
Yes although keep in mind we will likely drop @Enable annotations in 2.3. this will be only a part of 2.2.3 release and then there is a plan to focus efforts only on autoconfiguration

**Comment by renanreismartins** [comment]
Shouldn't it be rejected due the roadmap then?

And with that in mind, how will be the maxNumberOfRetries configured?

**Comment by renanreismartins** [comment]
@maciejwalkowiak another point would be to not introduce another configuration option that will disappear in the future. Let me know what you think.

**Comment by maciejwalkowiak** [comment]
Thanks @renanreismartins for feedback. You are right, we should not introduce new things just to kill them in the next version. 

I will post an issue with a proposal on how I see RDS integration in 3.0.
