### ISSUE TITLE
(spring-cloud-aws-jdbc) Using dbInstanceIdentifier fails after the failover due to readonly conversion

### ISSUE THREAD

**Issue by prasadus92** [spring-cloud/spring-cloud-aws#302]
This is a bug report.

When using annotation based configuration (@EnableRdsInstance), specifying dbInstanceIdentifier of one of the instances (writer) of the cluster results with service failing to write anything to the database after the failover as the earlier writer becomes the reader now.

**Comment by sheltonn** [comment]
At my job, we use the `cname`.  Is that a possible solution here?

**Comment by prasadus92** [comment]
Yes, we could use the cluster URL (we also ended up doing the same). 
But the documentation of the Spring Cloud JDBC, claims that the failover works while using @EnaleRdsIstance which isn't the case. Using DB Instance identifier would be nicer in case of using CloudFormation, we had one such use case, now we have to wait till the complete cluster launch and reference the cluster URL.

**Comment by aemruli** [comment]
@prasadus92 can you please add more details about your stack, probably paste necessary stack configuration and annotation part ?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
