### ISSUE TITLE
Cron Job Scheduling on SQS queue listeners

### ISSUE THREAD

**Issue by ramdesina** [spring-cloud/spring-cloud-aws#307]
As per my use case , i want to scheduling the SQS queue listeners for interval of times.

Is there any way to scheduling the  @SqsListener methods in spring cloud aws.

Thanks and Regards,
Ram

**Comment by aemruli** [comment]
@ramdesina you can write an own method that is scheduled by Spring (e.g. org.springframework.scheduling.annotation.Scheduled) this method can then call 

https://github.com/spring-cloud/spring-cloud-aws/blob/c42717a8fe03ce87d0e5fe81fb5ea7dfa7a05066/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/listener/SimpleMessageListenerContainer.java#L237

to start the queue listener and 

https://github.com/spring-cloud/spring-cloud-aws/blob/c42717a8fe03ce87d0e5fe81fb5ea7dfa7a05066/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/listener/SimpleMessageListenerContainer.java#L215

to stop the queue.
