### ISSUE TITLE
Does caching work at all?

### ISSUE THREAD

**Issue by pacey** [spring-cloud/spring-cloud-aws#309]
spring-cloud-aws 1.2.1

After adding the aws elasticache sdk, see #304, I now get this error on startup:
```
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cachingConfigurer' defined in class path resource [org/springframework/cloud/aws/cache/config/annotation/ElastiCacheCachingConfiguration.class]: Unsatisfied dependency expressed through method 'cachingConfigurer' parameter 2; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<org.springframework.cloud.aws.cache.CacheFactory>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations:
```

My Java config is:
```
@Configuration
@ConditionalOnBean(ElastiCacheAutoConfiguration.class)
@EnableElastiCache(
	@CacheClusterConfig(name = "CascadedUserRolesCacheCluster", expiration = 3600)
)
public class CacheConfiguration {
}
```

Does anyone know what magic I have to do to get it working? The docs are very light on caching and it really doesn't "just work" like they make out. I can't remote debug the issue as our aws instances are in private subnets that do not have public addresses.

**Comment by aemruli** [comment]
@pacey which spring version do you use ? And which spring boot version ?

**Comment by pacey** [comment]
spring-cloud-aws 1.2.1
spring-boot 1.5.11 and also 2.0.1

**Comment by aemruli** [comment]
Hello @pacey have a look at https://github.com/spring-cloud/spring-cloud-aws/tree/5fde56ffaf1ff11a80ef99aa122142f2fc758387/spring-cloud-aws-integration-test/src/test/java/org/springframework/cloud/aws/cache

There you can find a memcached and redis example, those are executed regularly within our test suite.
