### ISSUE TITLE
Support type serialization during SNS convertAndSend

### ISSUE THREAD

**Issue by rpk** [spring-cloud/spring-cloud-aws#31]
When sending messages from SNS, only String payloads are permitted in any of the convertAndSend instances.

[NotificationMessagingTemplate.java#L91-L101](https://github.com/spring-cloud/spring-cloud-aws/blob/master/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/core/NotificationMessagingTemplate.java#L91-L101)
```java
/**
 * <b>IMPORTANT</b>: the underlying message channel {@link org.springframework.cloud.aws.messaging.core.TopicMessageChannel} only
 * supports {@code String} as payload. Therefore only {@code String} payloads are accepted.
 *
 * @see org.springframework.messaging.core.MessageSendingOperations#convertAndSend(Object, Object, java.util.Map)
 */
@Override
public <T> void convertAndSend(String destinationName, T payload, Map<String, Object> headers, MessagePostProcessor postProcessor) throws MessagingException {
	Assert.isInstanceOf(String.class, payload, "Payload must be of type string");
	super.convertAndSend(destinationName, payload, headers, postProcessor);
}
```

After glancing through the code it seems like this constraint is not necessary as when AbstractMessagingSendingTemplate in spring-messaging is invoked it creates a string backed payload:

[AbstractMessageSendingTemplate.java#L128-L134](https://github.com/spring-projects/spring-framework/blob/master/spring-messaging/src/main/java/org/springframework/messaging/core/AbstractMessageSendingTemplate.java#L128-L134)
```java
@Override
public void convertAndSend(D destination, Object payload, Map<String, Object> headers,
		MessagePostProcessor postProcessor) throws MessagingException {

	Message<?> message = doConvert(payload, headers, postProcessor);
	send(destination, message);
}
```
[AbstractMessageSendingTemplate.java#L157](https://github.com/spring-projects/spring-framework/blob/master/spring-messaging/src/main/java/org/springframework/messaging/core/AbstractMessageSendingTemplate.java#L157)
```java
Message<?> message = getMessageConverter().toMessage(payload, messageHeaders);
```
MessageConverter 
	applies toMessage [AbstractMessageSendingTemplate.java#L157](https://github.com/spring-projects/spring-framework/blob/master/spring-messaging/src/main/java/org/springframework/messaging/core/AbstractMessageSendingTemplate.java#L157)
	which calls [AbstractMessageConverter.java#L201](https://github.com/spring-projects/spring-framework/blob/master/spring-messaging/src/main/java/org/springframework/messaging/converter/AbstractMessageConverter.java#L201)
	which calls [MappingJackson2MessageConverter.java#L191](https://github.com/spring-projects/spring-framework/blob/master/spring-messaging/src/main/java/org/springframework/messaging/converter/MappingJackson2MessageConverter.java#L191).
```java
payload = writer.toString();
```

The other codepath in MappingJackson2MessageConverter allows a byte array to be returned.  In order to prevent this, NotificationMessagingTemplate can have the Jackson converter added similar to 
[QueueMessagingTemplate.java#L86-L94](https://github.com/spring-cloud/spring-cloud-aws/blob/master/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/core/QueueMessagingTemplate.java#L86-L94).

```java
if (messageConverter != null) {		
	messageConverters.add(messageConverter);
} else if (JACKSON_2_PRESENT) {
	MappingJackson2MessageConverter mappingJackson2MessageConverter = new MappingJackson2MessageConverter();
	mappingJackson2MessageConverter.setSerializedPayloadClass(String.class);
	messageConverters.add(mappingJackson2MessageConverter);
}
setMessageConverter(new CompositeMessageConverter(messageConverters));
```

As message conversion ordering is guaranteed within CompositeMessageConverter, as long as jackson is added first, the output is guaranteed to be a String.  This would make consuming types from SNS->SQS (or other delivery channels) easier.

**Comment by sfussenegger** [comment]
we came to the same conclusion as @rpk and implemented it for ourselves. the outcome is in PR #75

**Comment by jeffxor** [comment]
Any chance we can get the pull request merged it is pretty useful thing if we want to do pub sub in AWS.
