### ISSUE TITLE
If I don't have the permission to the GetQueueAttributes action

### ISSUE THREAD

**Issue by jiayun** [spring-cloud/spring-cloud-aws#318]
I am accessing the queues created by others, and don't have the permission to the GetQueueAttributes action. What can I do with this line of code?

https://github.com/spring-cloud/spring-cloud-aws/blob/2ced24c033e59a1cb5046855316121f5d2c3768d/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/listener/AbstractMessageListenerContainer.java#L306

**Comment by aemruli** [comment]
@jiayun we are doing this call because we need to know the redrive policy. In theory we could catch the exception and just assume that there is no re-drive policy, but I think that might create unwanted side-effects. 

Please make sure you can get the sqs:GetQueueAttributes permission.
