### ISSUE TITLE
SimpleMessageListenerContainerFactory waitTimeOut defaults to 0

### ISSUE THREAD

**Issue by zhaoqingchris** [spring-cloud/spring-cloud-aws#319]
Default waitTimeOut value is 0, and `SqsListener` is smashing the queue as hard as it can

**Comment by petromir** [comment]
I had the same issue and CPU was almost burned.

As a work around you can set `waitTimeOut` to 20 (which is the maximum) in
https://github.com/spring-cloud/spring-cloud-aws/blob/5fde56ffaf1ff11a80ef99aa122142f2fc758387/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/config/SimpleMessageListenerContainerFactory.java#L99

This is sent with each `receive-message` request. Another option is to set it in AWS console as described here https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-long-polling-for-queue.html#sqs-configure-long-polling-for-queue-console

**Comment by maciejwalkowiak** [comment]
Thanks @zhaoqingchris for reporting and @petromir for an advice. Defaults have been changed to 20 seconds.
