### ISSUE TITLE
ElastiCache on EC2

### ISSUE THREAD

**Issue by jehunkim** [spring-cloud/spring-cloud-aws#322]
Enhancement

Hi

I'm trying to develop an app using spring-cloud-aws(2.0.0RC1)

I didn't use ElastiCache. And It doesn't have a problem on my develop machine.
And I trying to deployment on AWS, it caused problem.

like below message
> No qualifying bean of type 'java.util.List<org.springframework.cloud.aws.cache.CacheFactory>'

I solved this problem like below

> @SpringBootApplication(exclude = ElastiCacheAutoConfiguration.class)

It is problem that enabling elasticache configuration, running on ec2.
I think it should be optional feature likes below.
User write explicit @EnableElastiCache on code
or
Write in application properties
> cloud.aws.cache.auto: false

And It need to update manual more detail, can possible predicate issue.

Thanks

**Comment by aemruli** [comment]
@jehunkim we check for com.amazonaws.services.elasticache.AmazonElastiCache in the classpath and assume that if you have that class on your classpath, then you want to create a cache instance. Can you please check if you have that dependency ? Because that should be optional.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
