### ISSUE TITLE
Support for ECS Service Discovery?

### ISSUE THREAD

**Issue by ringods** [spring-cloud/spring-cloud-aws#326]
On 22 Mar 2018, AWS introduced ECS Service Discovery:

https://aws.amazon.com/about-aws/whats-new/2018/03/introducing-service-discovery-for-amazon-ecs/

To have automatic registration/deregistration of spring based services, would this project be the place to have this implemented?

**Comment by mattmadhavan** [comment]
Hello,
Any progress on this issue?

Thanks
Matt

**Comment by ringods** [comment]
Reading further on the documentation, nothing is needed on the coding side as everything is handled in the ECS service registration. Resolving a service can be done via DNS A or SRV records.

**Comment by mattmadhavan** [comment]
Hello Ringo,
Can you please share some sample code ? Looks like the name-space is injected to the Docker and you append the abstract service name to that. Very similar to Eureka. If you have some sample code that will be great.
