### ISSUE TITLE
Disabling spring-cloud-aws auto configurations

### ISSUE THREAD

**Issue by jslott** [spring-cloud/spring-cloud-aws#335]
As a follow-up to: https://github.com/spring-cloud/spring-cloud-aws/issues/227, I'm trying to disable sqs messaging auto-configuration based upon my own application property. (The use case is that when running code locally, I don't want to contact a shared queue if I don't need to.)

Following the advice in the #227 issue, I'm trying to figure out what auto-configurations to exclude, something along the lines of:

```
@Configuration
@ConditionalOnProperty(prefix = "sqs", name = "enable", havingValue = "false", matchIfMissing = true)
@EnableAutoConfiguration(exclude = {MessagingAutoConfiguration.class, ContextStackAutoConfiguration.class, ContextCredentialsAutoConfiguration.class, ContextInstanceDataAutoConfiguration.class} )
public class SQSDisabledConfig {
}
```

I can't figure out exactly what auto-configuration classes to exclude. Even with the above, it still tries to create an instance of SimpleMessageListenerContainer (which fails because I haven't configured aws credentials, but I'm hoping it wouldn't even attempt to instantiate these beans).

Your guidance greatly appreciated.

**Comment by jslott** [comment]
After further investigation, the issue was because I was putting @EnableAutoConfiguration not on a top-level class. When I did, only MessageAutoConfiguration.class needed to be excluded (and furthermore the spring.autoconfig.exclude property works too). 

Closing since the issue wasn't Spring Cloud AWS related.

**Comment by Jardo-51** [comment]
What do you mean by "not on a top-level class" ?

**Comment by jslott** [comment]
```
public class TopLevelClass {
        public static class NotATopLevelClass {
        }
}
```
