### ISSUE TITLE
Request to add support for AWS Secrets Manager

### ISSUE THREAD

**Issue by sakhtar1979** [spring-cloud/spring-cloud-aws#337]
Is there any plan to support [AWS Secret Manager](https://aws.amazon.com/secrets-manager/)? The service enables you to easily rotate, manage, and retrieve database credentials, API keys, and other secrets throughout their lifecycle.

**Comment by jonatan-ivanov** [comment]
Since the PR (#357) was merged and it seems @ryanjbaxter added it to a release (2.0.1) which has already published, can somebody close this issue?

**Comment by spencergibb** [comment]
Closed by #357
