### ISSUE TITLE
Document policies need for each integration

### ISSUE THREAD

**Issue by engrun** [spring-cloud/spring-cloud-aws#341]
Testing my first spring-cloud-aws app these days, deploying to ECS

I have a task-role for my task-definition, and are running into multiple rollback/deploy of the stack, adding more and more policies to grant the autodetection for stacks enough privileges. 

It would be nice if you could document the exact privileges needed for spring-cloud-aws.

**Comment by maciejwalkowiak** [comment]
In fact, we need to document required IAM permissions for each integration.

**Comment by MatejNedic** [comment]
I believe we can close this issue @maciejwalkowiak

**Comment by maciejwalkowiak** [comment]
Policies can be found now in the reference docs: https://docs.awspring.io/spring-cloud-aws/docs/2.3.0.BUILD-SNAPSHOT/reference/html/index.html
