### ISSUE TITLE
ContextCredentialsAutoConfiguration Issue

### ISSUE THREAD

**Issue by davidgoate** [spring-cloud/spring-cloud-aws#354]
# Environment

* Java 10.0.1
* Spring Boot 1.5.14.RELEASE
* spring-cloud-aws-autoconfigure 1.2.2.RELEASE
* spring cloud: Edgware.SR3

# Issue

I am having some trouble with `org.springframework.cloud.aws.autoconfigure.context.ContextCredentialsAutoConfiguration`

When running my app locally inside Docker with the following environment variables set:

```properties
cloud.aws.credentials.accessKey=xxx
cloud.aws.credentials.secretKey=yyy
```

my app works as I expect. However, when I run it on docker on an EC2 instance with the same environment variables the app fails when calling SQS due to the not having permission.

I have set:

```properties
cloud.aws.stack.auto=false
cloud.aws.credentials.instance.profile=false
```

both locally and on EC2.

Should I define my own `com.amazonaws.auth.AWSCredentialsProvider` bean or should the default auto config behaviour be enough? I am confused about why the auto config seems to be favouring an instance profile or some other credentials over the ones provided via the environment.

**Comment by internetstaff** [comment]
I think you want `cloud.aws.credentials.instanceProfile=false` ?

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
