### ISSUE TITLE
Ability to get s3:// URI back from an S3 resource

### ISSUE THREAD

**Issue by osi** [spring-cloud/spring-cloud-aws#361]
I am trying to "round-trip" resources from a s3:// URI into a `Resource` and back again. Currently, `SimpleStorageResource#getURL` returns a `https://` URI into AWS. 

It would be nice to be able to round-trip these URIs

**Comment by tmnuwan12** [comment]
I want to help. Where should I look into.?

**Comment by maciejwalkowiak** [comment]
@tmnuwan12 go for it. Just keep in mind that whatever we do here should stay backward compatible.

**Comment by tmnuwan12** [comment]
Can you assign it to me.. But I need some time with this if that's ok. I have some office stuff to clear out  this week.

**Comment by tmnuwan12** [comment]
For bug fixes do we need to branch off from master or 2.2.x branch..?

**Comment by maciejwalkowiak** [comment]
Good question! Ideally from 2.2.x

**Comment by tmnuwan12** [comment]
I checked the code for SimpleStorageResource. From what I understand from the requirement is ability to specify "s3://" endpoint when creating SimpleStorageResource and return 
 "s3://" compliant URL by calling method getURL().. Before I change anything want to check the approach here.. I was thinking of add/modify constructor to accommodate a URL object or url string and return a compatible URL based on constructor argument.. Feel free to provide some inputs please.

**Comment by tmnuwan12** [comment]
@maciejwalkowiak

**Comment by maciejwalkowiak** [comment]
I think it it should be possible to obtain s3:// and https:// no matter how what parameters were passed to the constructor. What do you think?

**Comment by osi** [comment]
agreed @maciejwalkowiak

**Comment by tmnuwan12** [comment]
@osi @maciejwalkowiak Yes I agree. What do you think about getURI() implementation for SimpleStorageResource class that provides the "s3://" URI.

**Comment by tmnuwan12** [comment]
@maciejwalkowiak  I am getting some compilation errors when running  maven tests ( but in Intellij editor no compilation errors). Is this something known issue or am I missing something..?

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile (default-testCompile) on project spring-cloud-aws-core: Compilation failure: Compilation failure:
[21,17] package org.junit does not exist

**Comment by maciejwalkowiak** [comment]
@tmnuwan12 I explained reasons for compilation failure here https://github.com/spring-cloud/spring-cloud-aws/pull/565#pullrequestreview-425760511. Lets continue discussion in the pull request.
