### ISSUE TITLE
Support more data source properties in Spring Boot configuration files!?

### ISSUE THREAD

**Issue by Mortinke** [spring-cloud/spring-cloud-aws#362]
Inspired by the [12 factor app](https://12factor.net/) I would like to store the configuration properties in [configuration files](http://cloud.spring.io/spring-cloud-static/spring-cloud-aws/1.2.3.RELEASE/multi/multi__data_access_with_jdbc.html#_configuring_data_source_in_spring_boot) instead of [in the code](http://cloud.spring.io/spring-cloud-static/spring-cloud-aws/1.2.3.RELEASE/multi/multi__data_access_with_jdbc.html#_configuring_data_source_with_java_config). 

Is there any mechanism to use more data source properties than mentioned in the [documentation](http://cloud.spring.io/spring-cloud-static/spring-cloud-aws/1.2.3.RELEASE/multi/multi__data_access_with_jdbc.html#_configuring_data_source_in_spring_boot)? - comparable to 
```
spring.datasource.tomcat.connectionProperties
spring.datasource.tomcat.testOnBorrow  
spring.datasource.tomcat.validationQueryTimeout
```

Currently I use userdefined properties in my application.properties and import these in the TomcatJdbcDataSourceFactory:

> application.properties

```
tomcat.connectionProperties=socketTimeout=20;connectTimeout=10;loginTimeout=10;
tomcat.testOnBorrow=true
```

> TomcatJdbcDataSourceFactory

```
    TomcatJdbcDataSourceFactory tomcatJdbcDataSourceFactory() {

        TomcatJdbcDataSourceFactory fac = new TomcatJdbcDataSourceFactory();

        fac.setTestOnBorrow(env.getProperty("tomcat.testOnBorrow"));  
        fac.setConnectionProperties(env.getProperty("tomcat.connectionProperties", String.class));
        return fac;
    }
```

I'm wonder that there is no way that the properties are used directly

**Comment by spencergibb** [comment]
Is this specific to spring cloud aws?

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
