### ISSUE TITLE
Feature request: Expand MessageAttributeDataTypes to include String array

### ISSUE THREAD

**Issue by MPoorter** [spring-cloud/spring-cloud-aws#368]
### spring-cloud-aws-messaging
Version: 2.0.0.RELEASE

According to [Amazon documentation](https://docs.aws.amazon.com/sns/latest/dg/SNSMessageAttributes.html), the message attribute types are `String`, `String.Array`, `Number`, and `Binary`. But the types in [`MessageAttributeDataTypes`](
https://github.com/spring-cloud/spring-cloud-aws/blob/b69cc06856d00e77481580a292b6592b9d411363/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/core/MessageAttributeDataTypes.java) are limited to `String`, `Number`, and `Binary`.

My issue:
I would like to send a message to a SNS topic that has a message attribute of the type String.Array with multiple values, so that the SQS queues subscribed to the topic can filter on the condition whether a specific value is present in the array, as documented [here](https://docs.aws.amazon.com/sns/latest/dg/message-filtering.html). The trouble is, when the `NotificationMessagingTemplate` converts and sends the message, the `TopicMessageChannel`(https://github.com/spring-cloud/spring-cloud-aws/blob/b69cc06856d00e77481580a292b6592b9d411363/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/core/TopicMessageChannel.java) can't handle a String array and doesn't add it to the message attributes.

Is there a reason why `String.Array` wasn't included?

**Comment by vghero** [comment]
Any news on this? Seems a PR is already provided. Could someone take a look please?
