### ISSUE TITLE
Conditional on Missing AmazonSQS

### ISSUE THREAD

**Issue by ahmednasir91** [spring-cloud/spring-cloud-aws#370]
We an internal SDK that also defines a bean of type `AmazonSQSAsync`

```java
  @Bean
  @Primary
  @ConditionalOnMissingBean(AmazonSQSAsync.class)
  public AmazonSQSAsync amazonSQSAsync() {
    return AmazonSQSAsyncClientBuilder.defaultClient();
  }
```
When this SDK is included in a project which also uses Spring Cloud AWS SQS messaging, it started to fail with the following error
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method simpleMessageListenerContainer in org.springframework.cloud.aws.messaging.config.annotation.SqsConfiguration required a single bean, but 2 were found:
    - amazonSQSAsync: defined by method 'amazonSQSAsync' in class path resource [com/ahmed/events/sdk/publisher/configuration/EventPublishingAutoConfiguration.class]
    - amazonSQS: defined by method 'amazonSQS' in class path resource [org/springframework/cloud/aws/messaging/config/annotation/SqsClientConfiguration.class]

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

When checked the `SqsClientConfiguration` it has a `@ConditionalOnMissingAmazonClient(AmazonSQS.class)` any reason we have this on `AmazonSQS` instead of `AmazonSQSAsync`? since a client can define a bean with just synchronous `AmazonSQS` instead and the `AmazonSQSAsync` bean will not be created.

Secondly, in our client SDK what is the best way to avoid such conflict? Shall we also make the conditional `@ConditionalOnMissingBean(AmazonSQS.class)`?

https://github.com/spring-cloud/spring-cloud-aws/blob/b69cc06856d00e77481580a292b6592b9d411363/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/config/annotation/SqsClientConfiguration.java#L36

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
