### ISSUE TITLE
Bug? Override aws.param.* values already in the Environment?

### ISSUE THREAD

**Issue by pclements12** [spring-cloud/spring-cloud-aws#376]
Using version 2.0.0.RELEASE of the spring-cloud-starter-aws-parameter-store-config:

If in my application.properties file I have a value set for aws.paramstore.prefix, that should override the default value in the locator, but it is ignored.

The only way to override the default values in the current implementation is to provide them as program arguments using `-Daws.paramstore.prefix=/myCustomPrefix`

The AwsParamStorePropertySourceLocator is provided a default set of properties from Spring on initialization, and then when calling locate() is provided the the existing Environment so far. This Environment contains properties already loaded (such as those present in the application.properties file)

In the same way that the locator looks for an existing value for "spring.application.name", the app should look for values already set in the Environment for aws.paramstore.* values so that they can be overridden by an application.properties value.

**Comment by spencergibb** [comment]
The priority of `AwsParamStorePropertySourceLocator` is higher than that of `application.properties` on purpose. It doesn't make much sense to have it the other way around.

**Comment by bisoldi** [comment]
Another side-effect, the properties kept in Parameter Store can't be overridden on the command line.  Isn't the command line typically the highest priority?  With Cloud Config, there is a setting to allow local properties to override it.  Wouldn't the same functionality make sense for parameter-store-config?

**Comment by spencergibb** [comment]
That property is actually from spring-cloud-commons. It should work here as well.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by sourabhjagtap95** [comment]
> Another side-effect, the properties kept in Parameter Store can't be overridden on the command line. Isn't the command line typically the highest priority? With Cloud Config, there is a setting to allow local properties to override it. Wouldn't the same functionality make sense for parameter-store-config?

I was wondering if there is any solution for this, as I'm also facing the same issue of not overriding the value which is coming from AWS paramstore with the one provided in command line.
