### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by anshumanpurohit** [spring-cloud/spring-cloud-aws#38]
I want to use this in my project, but without a user guide it is hard to get started.

**Comment by gschukin** [comment]
Hi @anshumanpurohit 
Maybe this will work for you http://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html

**Comment by anshumanpurohit** [comment]
Thanks this is very helpful!

**Comment by aemruli** [comment]
Helllo @anshumanpurohit additionally to the mentioned documentation you can also have a look at our reference application here https://github.com/spring-cloud-samples/aws-refapp

I will leave this issue open as we have any way a plan to write a short user-guide for R1.0 GA

**Comment by russomi** [comment]
Are there any recent sample apps/guides that address running a simple rest service locally and running in deployed in AWS?  I cannot seem to get anything running locally by using start.spring.io.
