### ISSUE TITLE
spring-boot-devtools dependency breaks S3 ResourceLoader 

### ISSUE THREAD

**Issue by FedorRomanov** [spring-cloud/spring-cloud-aws#384]
When running spring-cloud example on how to use  S3 ResourceLoader :
```
Resource resource = this.resourceLoader.getResource("s3://myBucket/rootFile.log");
WritableResource writableResource = (WritableResource) resource;
try (OutputStream outputStream = writableResource.getOutputStream()) {
  outputStream.write("test".getBytes());
}
```
error happens:
```
java.lang.ClassCastException: org.springframework.web.context.support.ServletContextResource cannot be cast to org.springframework.core.io.WritableResource
```
It turns out that the issue is with `spring-boot-devtools` dependency: removing it from `pom.xml` fixes the issue:
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-devtools</artifactId>
</dependency>
```
When `spring-boot-devtools` is included, inside the `GenericApplicationContext.getResources()` method it executes the if block, but without `spring-boot-devtools` it calls the super.getResource():
```
public Resource getResource(String location) {
    if (this.resourceLoader != null) {
        return this.resourceLoader.getResource(location);
    }
    return super.getResource(location);
}
```

**Comment by groat-mike** [comment]
Nice catch on the devtools! I was scratching my head why this was working deployed but not when I ran locally...

After removing devtools from my POM I no longer encountered this issue.

**Comment by spencergibb** [comment]
Not sure how to fix devtools.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by mikaelhg** [comment]
@spencergibb, what is the feedback you're requesting, and from whom?

I've bumped in this issue, and just advised another person who encountered it.

**Comment by ollaw** [comment]
I've hit this issue too, i'm the "other person" @mikaelhg talks about.
