### ISSUE TITLE
@ConditionalOnAwsCloudEnvironment at method level

### ISSUE THREAD

**Issue by bsamartins** [spring-cloud/spring-cloud-aws#389]
When setting @ConditionalOnAwsCloudEnvironment or @ConditionalOnMissingAwsCloudEnvironment (Srping Cloud 2.0.0) at a method level i would have expected the bean to be created on the environment that matches the condition, but instead it's ignored. It works fine at class level.

The below example will produce two beans with value "cloud" and "local" regardless of the environment.

```
@Configuration
class MyConfig {
   
    @ConditionalOnAwsCloudEnvironment 
    public String cloud() {
        return "cloud"
    }

    @ConditionalOnMissingAwsCloudEnvironment 
    public String local() {
        return "local"
    }

}
```

Could it be related with the ConfigurationPhase?
https://github.com/spring-cloud/spring-cloud-aws/blob/3bfd3a537192cf38a14c7a0c8df16876511db42a/spring-cloud-aws-context/src/main/java/org/springframework/cloud/aws/context/annotation/OnAwsCloudEnvironmentCondition.java#L30-L33

**Comment by spencergibb** [comment]
Not sure. Do you want to experiment and try changing the phase and see if that help? That condition hits an aws endpoint, so that may have something to do with it as well.

**Comment by bsamartins** [comment]
https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/context/annotation/ConditionEvaluator.java#L103-L113

I was debugging the code and it never got to evaluate if the condition matched (at a method level), because the `phase` was `REGISTER_BEAN` and the `requiredPhase` was `PARSE_CONFIGURATION`.

Returning `null` or `ConfigurationPhase.REGISTER_BEAN` on the `getConfigurationPhase` seams to make it work just fine.

**Comment by spencergibb** [comment]
PRs welcome
