### ISSUE TITLE
Add support for AWS SDK 2.x

### ISSUE THREAD

**Issue by mrcasablr** [spring-cloud/spring-cloud-aws#400]
AWS java 2.x sdk is now GA

https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-x-released/

**Comment by artembilan** [comment]
And also with that I would like to consider to have Reactor-wrapping clients. For example all those `CompletableFuture` returns could simply be wrapped to the `Mono` or `Flux`. As well as some incoming arguments could be as a `Publisher` as well.
