### ISSUE TITLE
AWS SQS Fifo maintain ordering

### ISSUE THREAD

**Issue by scott9999** [spring-cloud/spring-cloud-aws#401]
Enhancement (maybe)

I am using the SqsListener with a FIFO queue and I need to maintain the order of the messages based on the group id. If I configure the max number of messages on the SimpleMessageListenerContainerFactory to 10; so that it retrieves the messages in batches to obtain the required throughput; the messages are processed by the task executor concurrently, so the order is lost. Is there a way to configure the listener to receive 10 messages but process them sequentially, and to have multiple listeners running for the same queue.

**Comment by spencergibb** [comment]
Why not get batches of 1?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by scott9999** [comment]
To get the desired throughput we need to pull batches of 10.

**Comment by spencergibb** [comment]
I'm afraid I'm not knowledgable enough about that to give a proper answer. @garyrussell or @dsyer?

**Comment by garyrussell** [comment]
I am not familiar with it either, but it looks like you could inject a `ThreadPoolTaskExecutor` with a core pool size of 1.

The default executor gets a dynamic pool sized 2 (min) to `number of queues * (maxNumberOfMessagePerBatch  + 1)` (max).

https://github.com/spring-cloud/spring-cloud-aws/blob/5b6fa933fcd6e36d90c77ecdd0de0dd2949306b2/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/listener/SimpleMessageListenerContainer.java#L181-L216

**Comment by garyrussell** [comment]
cc/ @artembilan

**Comment by artembilan** [comment]
If you have some sequence in those messages to determine order, you can consider to use Spring Integration's `Resequencer` downstream, after the listener container: https://docs.spring.io/spring-integration/docs/current/reference/html/messaging-routing-chapter.html#resequencer.

Otherwise let's see what authors of that code can say!

**Comment by scott9999** [comment]
Thanks, I will look at handling the ordering in the subscriber code. 

I have noticed during performance testing that there is a relatively big latency between each batch call, so to increase the number of listeners for the same queue I created multiple listeners and gave them queue names ending in virtual.x then used the DestinationResolver to resolve to the same physical queue. I couldn't find a simple way to register multiple listeners for the same queue.

You can close this case.
