### ISSUE TITLE
Setting AWS SDK fails

### ISSUE THREAD

**Issue by xiaoyudeng666** [spring-cloud/spring-cloud-aws#404]
Bugs:
http://www.springframework.org/schema/cloud/aws/context/spring-cloud-aws-context.xsd
cannot be found now

**Comment by spencergibb** [comment]
I don't think we maintain that anymore.

**Comment by xiaoyudeng666** [comment]
Thanks Spencer. I want to ask if there is any new way let me register aws in spring?

**Comment by aemruli** [comment]
@xiaoyudeng666 why do you want to access the url at all ? The schema file should never be loaded from the internet as we are using the schmea.handler see https://github.com/spring-cloud/spring-cloud-aws/blob/master/spring-cloud-aws-context/src/main/resources/META-INF/spring.handlers

Please re-open if you think there is really a need for the online schema.
