### ISSUE TITLE
Which release version of spring cloud aws supports java 7?

### ISSUE THREAD

**Issue by froilan** [spring-cloud/spring-cloud-aws#405]
Our project currently use java 7 on Grails 2.4 and we don't foresee upgrading from it in the near future.
We are looking to integrate with sqs/sns through Spring Cloud but not sure which version to try. 

Is there a specific version that supports java 7?

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-aws/tree/v1.2.3.RELEASE is the last version to support java 7.
