### ISSUE TITLE
Make ResourceLoader lazy

### ISSUE THREAD

**Issue by gschukin** [spring-cloud/spring-cloud-aws#41]
It will be great if S3 ResourceLoader will fetch meta-data, may be optional, only if told to so, eg calling exists(), contentLenth() and etc methods.

**Comment by aemruli** [comment]
Hello @gschukin is there any particular situation where this has an user impact ?

**Comment by gschukin** [comment]
Hi @aemruli 
Actual S3 resource may be unavailable upon creation of Resource, but may be available later and vice versa.

Current implementation assume that S3 resource state (available, not available) can't be changed.

**Comment by gschukin** [comment]
@aemruli 
Unfortunately commit doesn't fix an issue when S3 resource were available but not available anymore.
