### ISSUE TITLE
Add support for SQS custom data types

### ISSUE THREAD

**Issue by AbdulWahedHaiderzadah1217** [spring-cloud/spring-cloud-aws#410]
Currently custom data types are silently ignored during transformation from MessageAttributes to MessageHeaders in QueueMessageUtils. Either custom data types should be supported fully or an Exception should be thrown.
If somebody uses SQS custom data type, which currently can only hold String or Binary values, it will get omitted in QueueMessageUtils and finding out why can be very time consumeing since it is omitted silently.

**Comment by maciejwalkowiak** [comment]
@AbdulWahedHaiderzadah1217 how do you see this support should look like?

**Comment by voytech** [comment]
Maybe when there is a custom data type like e.g. binary.png  - a value for header should be just wrapper like: CustomTypeMessageAttribute with fields: type: Binary, typeLabel: png, value - wrapped value like Binary type.
This way we are not loosing this header value ( current implementation would skip it). We are also not loosing info about custom type extension.

**Comment by voytech** [comment]
@maciejwalkowiak, @AbdulWahedHaiderzadah1217 if You are happy with solution with CustomTypeMessageAttribute wrapper then I can make it working that way...

**Comment by voytech** [comment]
@maciejwalkowiak, I'd like to help with that one. IMHO its quite important to have it done, as lack of proper handling of custom data types may force people to workarounds. I could create initial PR. I think that for this one, I will have to extend documentation a bit to mention about  `CustomTypeMessageAttribute` (if decide to go in that direction). Let me know If I should/can grab this one.

**Comment by maciejwalkowiak** [comment]
Go for it @voytech. I can't tell for sure now but the idea with wrapper sounds legit.

**Comment by voytech** [comment]
After thinking a bit more, I am not sure if using `CustomTypeMessageAttribute` as value wrapper is the way to go:
1. Solution for `Number` type currently allows labels that can be resolved to Java number types. This prevents from switching to `CustomTypeMessageAttribute` (it would be breaking change then)
2. Using `CustomTypeMessageAttribute` still is possible for `Binary` and `String` (only when label suffix detected) and I have submitted PR with that approach, but I think it is inconsistent with how `Number` type with labels are handled. Most preferred solution would be if all types with label are treated the same way - and as long as they can not - **Maybe dropping CustomTypeMessageAttribute and using unwrapped raw      Binary (ByteBuffer) or String value (with skipping type label from MessageAttribute) is the way to go (for 2.3)  ?**

**Comment by maciejwalkowiak** [comment]
What if we go with 2. but with addition that for `Number` where custom type does not match any of the known ones we already support, we return `CustomTypeMessageAttribute`?

**Comment by voytech** [comment]
I think that this is ok. The only thing that i personally don't like here - is lack of consistency in that sometimes we are using CustomTypeMessageAttribute for MessageAttributes with labeled types, but there are situations for Number with labelled type where we cannot use CustomTypeMessageAttribute (number type hints for primitives e.g.).  

Here is the thing: 
What if someone wants to publish to SQS (from app without spring-cloud-aws integration) and he is willing to use custom type labels. The consumer app uses spring-cloud-aws, and someone sees that there is a wrapper 'CustomTypeMessageAttribute'. He naturally expects CustomTypeMessageAttribute for all MessageAttributes with labelled types - I think it becomes tricky in situation where someone accidentally will use the same scheme (or its superset) for labelling Number type as the scheme automatically supported by spring-cloud-aws now. If he fail to discover that case - he would cast everything to CustomTypeMessageAttribute, but sometimes it will be just a java Number e.g.

**Comment by voytech** [comment]
By the way - I started to think that SqsMessageHeaders should provide convenience getters allowing to get MessageAttributes from headers.. e.g: `CustomTypeMessageAttribute getMessageAttribute(key)`. If someone uses SqsMessageHeaders class as argument for SqsListener method signature, then there is can be no type casting at all.
