### ISSUE TITLE
CredentialProfile loaded from wrong file

### ISSUE THREAD

**Issue by doom777** [spring-cloud/spring-cloud-aws#414]
I am using latest Spring 5.1.4 

In AWS-CLOUD 1.2.3, but s3 does work.

**Comment by maciejwalkowiak** [comment]
I'm sorry it took so long to get an answer. Could you provide more details on your problem? Ideally sample code with the bug reproduced.

**Comment by maciejwalkowiak** [comment]
Closing due to lack of feedback. If this problem is still happening please provide more details and we will reopen it.
