### ISSUE TITLE
Is there any simple way to retrieve MessageAttribute in @SqsListener

### ISSUE THREAD

**Issue by VelDeveloper** [spring-cloud/spring-cloud-aws#418]
We didn't have the support of getting MessageAttributes in @SqsListener. Is there any other way to fetch the MessageAttributes? 

I have explained the issue clearly along with a useCase [here](https://stackoverflow.com/questions/54673128/issue-getting-messageattributes-in-spring-cloud-sns-sqs-listener)

Any hint or solution would be really appreciable.

**Comment by maciejwalkowiak** [comment]
MessageAttributes are accessible through `@Header` annotation:

```java
@SqsListener("QueueListenerTest")
public void receiveMessage(String message,
                           @Header(value = "SenderId", required = false) String senderId) {
 ...
}
```
