### ISSUE TITLE
Support property placeholder for queue names in @MessageMapping value

### ISSUE THREAD

**Issue by alainsahli** [spring-cloud/spring-cloud-aws#43]
Resolve properties in queue names to allow environment specific queue names.

For example:
```java
@MessageMapping("${dead.letter.queue}")
public void deadLetterQueue(String deadLetter) {
    // ...
}
```

**Comment by leocwolter** [comment]
Any updates about this feature?

**Comment by simonso** [comment]
Please update.  Need this feature.

**Comment by aemruli** [comment]
Hi @simonso expect the feature in the next days (till end of weekend).

**Comment by simonso** [comment]
No problem!  That'll be great!
BTW - my team really like the spring cloud aws!  Ease the model of development! Sincerely
Simon

**Comment by simonso** [comment]
Hi all, 

Any update on this?

Thanks
Simon

**Comment by aemruli** [comment]
Hello @simonso I have comitted the change. I think 1.0.1 release will be released in the next weeks or so, but you can use the snapshot. We are pretty stable on the master, so there shouldn't be any major issues. 

Thanks 
Agim

**Comment by joeo73** [comment]
The usage would be like below correct?

@MessageMapping("${my.queueName}")
public void job(String message) {}

As the snapshot I have, this doesn't appear to be working.

**Comment by joeo73** [comment]
Does this also work for the @SendTo annotation?

**Comment by alainsahli** [comment]
Hi @joeo73, no it doesn't work with @SendTo yet. I opened a new issue #65 for that.
