### ISSUE TITLE
Multilpe Sqs listener  for single queue

### ISSUE THREAD

**Issue by thiyagu06** [spring-cloud/spring-cloud-aws#469]
I have an application which listen to single SQS queue. The SQS queue contains different types of messages like foo,bar etc. Is it possible to have multiple listener using single queue and dispatch it to the respective method based on the event name from SQS message?

**Comment by andreheringer-hotmart** [comment]
I have the same doubt.

**Comment by maciejwalkowiak** [comment]
It's currently not possible. You have to write dispatch logic by yourself inside method annotated with `@SqsListener`.

**Comment by nikhithagoli** [comment]
Hey people, Any one can share me a sample code how to implement two sqsListeners for a single sqs queue like the following:
class A{
@SqsListener(value = "some-queue", deletionPolicy = ON_SUCCESS)
public void onMessageReceived1(String payload, @Header(TYPE) String messageType) {}
}

class B {
@SqsListener(value = "some-queue", deletionPolicy = ON_SUCCESS)
public void onMessageReceived2(@Payload SomeMessagePayload message, @Header(TYPE) String messageType) {}
}

I got "Ambiguous handler methods mapped for destination " when I run my application

**Comment by nikhithagoli** [comment]
Hey guys ... question to spring-cloud-aws / multiple listeners on one queue(to have multiple sqsListeners for the same queue) can any one please the code for it. I have tried it as follows:
@Component
public class MessageListener2 {

	private static final String QUEUE = "sqs_spring_poc.fifo";
	
	@Autowired 
    AmazonSQSAsync sqs;

	@SqsListener(value = QUEUE, deletionPolicy = SqsMessageDeletionPolicy.NEVER)
    public void readMessage(String message) {
        System.out.println("Received message= {} with messageId= {} ******************* " + message);
    }
	
}

@Component
public class MessageListener {

	private static final String QUEUE = "sqs_spring_poc.fifo";
	

	@SqsListener(value = QUEUE, deletionPolicy = SqsMessageDeletionPolicy.ON_SUCCESS)
    public void getMessageFromSqs1(@Payload Message message, @Header("MessageId") String messageId) {
      System.out.println("Received message= {} with messageId= {}  " + message + "  "+ messageId);
  }
}

I'm getting "Ambiguous handler methods mapped for destination " when  I run the application.
