### ISSUE TITLE
Confusing credential defaults / documentation.

### ISSUE THREAD

**Issue by internetstaff** [spring-cloud/spring-cloud-aws#470]
I'm on v2.1.1.RELEASE

The documentation is at least unclear on the credential configuration:

https://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html#_sdk_credentials_configuration

... says the DefaultAWSCredentialsProvider will be used if nothing is configured. While this is  accurate within a certain context, it does not appear to be the case when auto configuration is included.

https://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html#_configuring_credentials

... does not make it clear what the default chain is, or that it is *not* the DefaultAWSCredentialsProvider. It seems odd that the Default wouldn't be the default. :)

The chain that seems to get configured by default (EC2ContainerCredentialsProviderWrapper -> ProfileCredentialsProvider) does make some sense as a default for an EC2 or ECS deployment. 

However, it causes applications to **hang repeatedly** and, worse, **silently** for 2s when running on a non-EC2 instance - e.g. in local development. For example, firing up a QueueMessagingTemplate with a default configuration it would take ~7s to send a message because the EC2ContainerCredentialsProvider tried 3 times to query the metadata on each send.

I see lots of people getting frustrated with startup time and credentialing and abandoning auto configuration completely. It seems like using DefaultAWSCredentialsProvider as a default would solve a lot of issues for people since the problems *not* using it can be silent and challenging to debug.

This is related to at least #52 #102 #191 #354

**Comment by mdkv4** [comment]
+1 Additionally I would add that the workaround in #52 no longer works.

https://github.com/spring-cloud/spring-cloud-aws/issues/102#issuecomment-248327747
Appears to be the only way to force the usage of DefaultAWSCredentialsProviderChain

**Comment by maciejwalkowiak** [comment]
Ability to use `DefaultAWSCredentialsProviderChain` as added in #170 but I agree documentation is not clear.
