### ISSUE TITLE
Configure FIFO queue @SqsListener to read from particular Message Group ID

### ISSUE THREAD

**Issue by Gomzee18** [spring-cloud/spring-cloud-aws#471]
I am using @SqsListener to read msgs from SQS FIFO Queue. I do not see a direct reference to configure my SqsListener to read message from queue based on Message Group ID and Message Deduplication ID.

I also raised a question on Stack-Overflow but no one replied. So, thought of checking it here.

https://stackoverflow.com/questions/56487474/configure-message-group-id-for-fifo-using-sqslistener-annotation

**Comment by maciejwalkowiak** [comment]
SQS itself does not allow filtering messages based on group id, we can't do much about it.
