### ISSUE TITLE
Application is not running with Spring Boot 2

### ISSUE THREAD

**Issue by AliakseiMat** [spring-cloud/spring-cloud-aws#477]
**When I try to use spring-cloud-starter-aws-secrets-manager-config with Spring Boot 2 2.0.0.RELEASE and latest, have the following error:**
```
17:33:13.369 [background-preinit] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Log4j2LoggerProvider
17:33:13.370 [background-preinit] INFO org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.13.Final
17:33:13.381 [background-preinit] DEBUG org.hibernate.validator.internal.engine.resolver.TraversableResolvers - Cannot find javax.persistence.Persistence on classpath. Assuming non JPA 2 environment. All properties will per default be traversable.
17:33:13.387 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ValidationXmlParser - Trying to load META-INF/validation.xml for XML based Validator configuration.
17:33:13.388 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ResourceLoaderHelper - Trying to load META-INF/validation.xml via TCCL
17:33:13.388 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ResourceLoaderHelper - Trying to load META-INF/validation.xml via Hibernate Validator's class loader
17:33:13.388 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ValidationXmlParser - No META-INF/validation.xml found. Using annotation based configuration only.
17:33:13.539 [background-preinit] DEBUG org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator - Loaded expression factory via original TCCL
17:33:13.544 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator as ValidatorFactory-scoped message interpolator.
17:33:13.544 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.resolver.TraverseAllTraversableResolver as ValidatorFactory-scoped traversable resolver.
17:33:13.544 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.util.ExecutableParameterNameProvider as ValidatorFactory-scoped parameter name provider.
17:33:13.544 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.DefaultClockProvider as ValidatorFactory-scoped clock provider.
17:33:13.544 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.scripting.DefaultScriptEvaluatorFactory as ValidatorFactory-scoped script evaluator factory.
17:33:13.797 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>([Ljava/lang/Object;)V
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:161)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:102)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:68)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
```
```
<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-aws-secrets-manager-config</artifactId>
            <version>2.1.2.RELEASE</version>
        </dependency>

    </dependencies>
```

**Comment by maciejwalkowiak** [comment]
You're using incompatible version of Spring Cloud with Spring Boot 2.0. It's usually better to use Spring Cloud BOM for managing Spring Cloud dependencies. If you would go with Spring Boot 2.1.6 complete `pom.xml` would look like:

```<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.6.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>Greenwich.SR1</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-aws-secrets-manager-config</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by AliakseiMat** [comment]
Thank you @maciejwalkowiak now the application able to start. But have another error
Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
Even if I provide cloud.aws.region.static=US-WEST-2 in application.properties file.

**Comment by maciejwalkowiak** [comment]
Region has to be lowercase:
```
cloud.aws.region.static=us-west-2
```
Also, if you don't run it in AWS or do not use CloudFormation you may have to disable stack detection:
```
cloud.aws.stack.auto=false
```
In general, I believe these kind of questions fit better to Stackoverflow than Github issue.

**Comment by AliakseiMat** [comment]
Thank you @maciejwalkowiak, yes you are right such kind of questions more fit to StackOverflow. Just because the Documentation is unclear how to use Spring Cloud AWS Secret Manager I thought it is some kind of the bug. Also, it would be very useful to have a working example of spring-cloud-starter-aws-secrets-manager-config. Thank you!

**Comment by AliakseiMat** [comment]
And regarding your answer. I have  cloud.aws.stack.auto=false in my config and any way I have this error(with lowercase region name as well). Only adding aws.region as an Env property fixed this problem. Same for the aws.accessKeyId and aws.secretKey. I'm quite confused is the spring-cloud-aws-autoconfigure working correctly?

**Comment by maciejwalkowiak** [comment]
Understood and I agree that documentation is not that great. Maybe you can consider making a pull request that improves it? If you still have issues I can take a look if you publish on GitHub complete sample project.

**Comment by AliakseiMat** [comment]
Could you please take a look at the following project https://github.com/AliakseiMat/SpringCloudAWsSecretManager

**Comment by maciejwalkowiak** [comment]
Indeed you're right. It's easy to miss it once you have AWS CLI set up.

As far as I can tell `org.springframework.cloud.aws.autoconfigure.secretsmanager.AwsSecretsManagerBootstrapConfiguration` should use `org.springframework.cloud.aws.core.region.RegionProvider` to set correct region on `AWSSecretsManager` object.

**Comment by devondragon** [comment]
I appear to be having the same issue.  I have cloud.aws.region.static=us-east-2 set in my application.properties file.  However I get the " Unable to find a region via the region provider chain" error on startup.  Other Spring AWS services have been working fine to date, this just started when I tried to use the SecretsManager module.

**Comment by maciejwalkowiak** [comment]
As stated in documentation - usual region and credentials resolution does not apply to Secret Manager and Parameter Store integration as beans are created during bootstrap phase. Was it a design decision or can we consider implementing passing these properties during bootstrap phase? cc @jkuipers

**Comment by jkuipers** [comment]
The bootstrap autoconfiguration needs a configured `AWSSimpleSystemsManagement` instance, and when I wrote the initial code (which didn't use Spring Cloud AWS at all, this was just the best project to contribute the code to) relying on `AWSSimpleSystemsManagementClientBuilder.defaultClient()` with its `DefaultAWSCredentialsProviderChain` and `DefaultAwsRegionProviderChain` was by far the easiest way to have something working that's still configurable in all the usual AWS ways. 
For more advanced use cases a user can override the provided `AWSSimpleSystemsManagement` bean, but that's not trivial because it's created during Spring Cloud's bootstrapping phase rather than as part of the regular application context. 

If it's possible to align this code more with the way that Spring Cloud AWS allows users to configure credentials and regions, then by all means go for it! Users will have to understand that they'll need to use `bootstrap.[properties|yml]` for the configuration though, or the configuration won't be applied to the bootstrap context.

**Comment by harinjy** [comment]
> Could you please take a look at the following project https://github.com/AliakseiMat/SpringCloudAWsSecretManager

why did you mention aws.sercretmanager.* properties when all of them are default?

**Comment by harinjy** [comment]
How can i  configure my spring boot application to use aws secrets manager VPC endpoint instead of going public network?

**Comment by maciejwalkowiak** [comment]
You would have to overwrite provided bean during bootstrap phase, which as @jkuipers wrote is not trivial but doable. You can find more about bootstrap phase here https://cloud.spring.io/spring-cloud-commons/multi/multi__spring_cloud_context_application_context_services.html

**Comment by bfkelsey** [comment]
> Region has to be lowercase:
> 
> ```
> cloud.aws.region.static=us-west-2
> ```
> 
> Also, if you don't run it in AWS or do not use CloudFormation you may have to disable stack detection:
> 
> ```
> cloud.aws.stack.auto=false
> ```
> 
> In general, I believe these kind of questions fit better to Stackoverflow than Github issue.
It seems like cloud-secrets-manager-starter includes aws-autoconfigure which causes this problem. I was able to exclude autoconfigure and it still worked fine. So it seems like that dependency could probably be removed from the starter? cloud-parameter-store-starter doesn't include it and it works just fine.

**Comment by luupqvinh** [comment]
Hi all.
Any update on this issue?
I have this in my pom.xml

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-aws</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-aws-autoconfigure</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-aws-parameter-store-config</artifactId>
		</dependency>

The autoconfigure works well and configure a static region. In my case:
cloud.aws.region.auto=false
cloud.aws.region.static=eu-west-1

But this code in AwsParamStoreBootstrapConfiguration does not work

	@Bean
	@ConditionalOnMissingBean
	AWSSimpleSystemsManagement ssmClient() {
		return AWSSimpleSystemsManagementClientBuilder.defaultClient();
	}

The error:

Caused by: com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:436) ~[aws-java-sdk-core-1.11.415.jar:na]
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:402) ~[aws-java-sdk-core-1.11.415.jar:na]
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46) ~[aws-java-sdk-core-1.11.415.jar:na]
	at com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClientBuilder.defaultClient(AWSSimpleSystemsManagementClientBuilder.java:45) ~[aws-java-sdk-ssm-1.11.415.jar:na]
	at org.springframework.cloud.aws.autoconfigure.paramstore.AwsParamStoreBootstrapConfiguration.ssmClient(AwsParamStoreBootstrapConfiguration.java:55) ~[spring-cloud-starter-aws-parameter-store-config-2.2.1.RELEASE.jar:2.2.1.RELEASE]

Is this a bug?

**Comment by jkuipers** [comment]
It's not a bug, but basically a "missing feature". The parameter store support must use the config from bootstrap.properties rather than application.properties, and thus can't use the same config that you specify for the other spring-cloud-aws components. 
It defaults to that code that you showed, so there's two ways of changing the AWS config it uses:
1. Use the mechanisms from the AWS SDK: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html
2. Override that bean definition with your own. That does require some work, as this is Spring Cloud's bootstrap context, not the regular Spring ApplicationContext. Seehttps://cloud.spring.io/spring-cloud-static/spring-cloud-commons/2.2.2.RELEASE/reference/html/#customizing-the-bootstrap-configuration

**Comment by maciejwalkowiak** [comment]
Can we rephrase this issue into: Add option to set static region in Parameter Store integration?

**Comment by maciejwalkowiak** [comment]
Closed due to lack of feedback. Setting static region for Parameter Store and Secrets Manager is moved to separate issue #578
