### ISSUE TITLE
Documentation Enhancement Request - Secret Manager

### ISSUE THREAD

**Issue by devondragon** [spring-cloud/spring-cloud-aws#481]
For someone trying to use the AWS Secret Manager in a Spring application, the existing documentation is severely lacking.  It may make sense if you've already been using Spring Cloud/Consul, etc... But if not, the tiny amount of documentation does not provide enough info to get things actually working.  

I would love to see a working example added to the documentation or linked to.  Something with actual paths, secret names, etc.. so we can see how it's all supposed to work.  I've been struggling for two days with no luck and am going to just revert to writing my own code against the AWS SDK:(. 

Thanks!

**Comment by knutschlesselmann4242** [comment]
@devondragon I struggled with this myself and I feel your pain ;-)

The solution: The SecretsManager support doesn't work with paths like the SSM integration. Instead you have to supply **one** secret like `/secret/${ApplicationName}_${Environment}` where you specify a config map as value e.g.
```
{
  "spring.data.mongodb.uri": "my uri"
}
```

**Comment by kschlesselmann** [comment]
@devondragon I struggled with this myself and I feel your pain ;-)

The solution: The SecretsManager support doesn't work with paths like the SSM integration. Instead you have to supply **one** secret like `/secret/${ApplicationName}_${Environment}` where you specify a config map as value e.g.
```
{
  "spring.data.mongodb.uri": "my uri"
}
```

**Comment by devondragon** [comment]
@kschlesselmann thanks for the reply.  I am pretty sure that I got there (eventually) but the values weren't being read or at least not populated into my classes using the @Value annotation, etc..  At this point I've redone the code to use the AWS API directly, so I can't really troubleshoot.  But some sort of step by step, with examples, paths, etc.. that works, would be great to see in the documentation. This seems like a potentially powerful feature, and could be a very good practice for security, if only it were better documented.

**Comment by maciejwalkowiak** [comment]
@eddumelendez perhaps you can do it as a part of https://github.com/spring-cloud/spring-cloud-aws/issues/655?

**Comment by MatejNedic** [comment]
This can be closed with https://github.com/awspring/spring-cloud-aws/pull/27 @maciejwalkowiak?

**Comment by maciejwalkowiak** [comment]
Spring Cloud AWS has now a sample application showing how to use Secrets Manager integration: https://github.com/awspring/spring-cloud-aws/tree/2.3.x/spring-cloud-aws-samples/spring-cloud-aws-secrets-manager-sample

Ideally we will also add a getting started guide, but this will come later.
