### ISSUE TITLE
AWS SDK version upgrade request

### ISSUE THREAD

**Issue by internetstaff** [spring-cloud/spring-cloud-aws#482]
1.11.415 is now pretty stale - we're having to override lots of dependencies for newer functionality. 

Any chance of an upgrade? :)

Thanks!

**Comment by geriBatai** [comment]
Are there any plans for this? Current SDK is even more outdated now, blocking some developments, especially in Cloud Native space.

**Comment by dkimdon** [comment]
We want to use the new framework for per-pod IAM permissions in Kubernetes as described here:

https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

The current AWS SDK version (1.11.415) doesn't support the sts:AssumeRoleWithWebIdentity call necessary for permission control as described above.  Updating to a version equal to or greater than 1.11.623 will fix this for us.  See details at the link above.

I can rebuilt the spring-cloud-aws code with the new version in spring-cloud-aws-dependencies/pom.xml.  I ran the local tests with the new version (I didn't run the tests that actually use AWS) and they all passed.  I don't want to build my own jar but would rather use an untouched jar from upstream.

Thanks a lot for considering :-)

-David

**Comment by internetstaff** [comment]
@dkimdon Perhaps try submitting a pull request, even as tiny as it probably is? :)

@ryanjbaxter @OlgaMaciaszek @marcingrzejszczak You're the only recent committers on spring-cloud-aws ... are you by chance able to assist ... or is this project dead? :)

**Comment by kingofmooks** [comment]
@dkimdon any chance you could post the pom your using to manually get this to work. i cant get this one to work for me.

**Comment by internetstaff** [comment]
@spencergibb Your blog post on 17 April seems to confirm that this project is dead, as already indicated by the plethora of "waiting-for-triage" issues and pull requests. Can you clarify?

Thanks.

**Comment by spencergibb** [comment]
Look for some official communication soon.

**Comment by joodlehammond** [comment]
Hi @spencergibb can this upgrade not be released separately from the SDK 2.0 work? It looks like @dkimdon managed to get this repo to work with the latest AWS SDK 1.0 libraries. Why does this need to bundled in with the new major update?

**Comment by jonfreedman** [comment]
"soon" is a bit vague - should we look to remove this as a dependency?

**Comment by internetstaff** [comment]
@spencergibb it doesn't seem like other PRs are being reviewed. There's a significant amount of overhead (especially w.r.t. integration tests) for a non-contributor to perform this upgrade. Are there no contributors that could knock this one out?

Alternatively, is there a CI pipeline for this project that will at least run the integration tests?

Thanks.

**Comment by spencergibb** [comment]
Please see https://github.com/spring-cloud/spring-cloud-aws/issues/557 for updates on the state of the project.

**Comment by maciejwalkowiak** [comment]
Dependencies will be updated independently from AWS SDK v2 migration. At the time being if you're using Maven you can overwrite versions by adding AWS SDK v1 BOM to your dependencies management - you only have to make sure that it's declared first, before Spring Cloud Dependencies BOM.

```
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-bom</artifactId>
			<version>1.11.791</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-dependencies</artifactId>
			<version>${spring-cloud.version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
```

**Comment by gauravbrills** [comment]
> rsions by adding AWS SDK v1 BOM to your dependencies management - you only have to make sure that it's declared first, before Spring Cloud Dependencies BOM.

how about for gradle will this work 

```
 mavenBom "com.amazonaws:aws-java-sdk-bom:${awsVersion}"
         mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
```

**Comment by maciejwalkowiak** [comment]
@gauravbrills I don't know how boms work with Gradle.
