### ISSUE TITLE
Allow using a different credential/region provider for RDS data source

### ISSUE THREAD

**Issue by kzwang** [spring-cloud/spring-cloud-aws#486]
Use case: The RDS database and the application are in two different AWS accounts/regions (or the application uses multiple RDS databases in different AWS accounts/regions). I want to use a specific credential/region provider for a specific data source.

**Comment by maciejwalkowiak** [comment]
Spring Cloud AWS does not support using multiple credentials. An option to set custom region has been implemented in https://github.com/spring-cloud/spring-cloud-aws/pull/715
