### ISSUE TITLE
Cannot use jasypt-spring-boot to decrypt RDS password

### ISSUE THREAD

**Issue by kzwang** [spring-cloud/spring-cloud-aws#487]
I'd like to store encrypted RDS database password in properties, and use jasypt-spring-boot (https://github.com/ulisesbocchio/jasypt-spring-boot) to decrypt it. However, Spring Cloud AWS is reading the password when register bean definitions, at that time, jasypt-spring-boot haven't processed environment sources yet, and it reads the encrypted value not the actual password.

**Comment by meonwax** [comment]
I have the same problem. Any suggestions?

**Comment by maciejwalkowiak** [comment]
Just to make sure - this problem occurs when using `@EnableRds` but not when using autoconfiguration, correct?

**Comment by maciejwalkowiak** [comment]
Closed due to inactivity.

**Comment by richbolen** [comment]
I have the same issue.  Any chance we could reopen this?
