### ISSUE TITLE
Support different RDS datasource for different profile

### ISSUE THREAD

**Issue by kzwang** [spring-cloud/spring-cloud-aws#489]
If I use `cloud.aws.rds.<db name>` to setup RDS data source, there is no way to override it for different profile (it seems I can't unset properties in Spring, I can only override it to an empty value, but Spring Cloud AWS still try to set up RDS data source even all those properties have empty values).

Use case: I want to use RDS database A by default, and a specific profile (e.g. local) will override to use RDS database B (or use local H2 so RDS shouldn't be setup).

**Comment by behrangsa** [comment]
@kzwang have you tried overriding the value in `bootstrap-profileName.yml`/`bootstrap-profileName.properties`? For example:

#### `bootstrap.yml`
```yaml

```

#### `bootstrap-prod.yml`
```yaml
cloud.aws.rds.prod
```

#### `bootstrap-test.yml`
```yaml
cloud.aws.rds.test
```

**Comment by kzwang** [comment]
@behrangsa That approach works for simple cases where there are not many profiles and each profile uses its own db. But won't work for some complex cases, e.g. I want a default db defined in `bootstrap.yml`, and it will be used in all profiles except 1 (so I don't have to copy the same DB setup in multiple files).

**Comment by maciejwalkowiak** [comment]
@kzwang may you check if changes proposed in https://github.com/spring-cloud/spring-cloud-aws/issues/495 would solve your problem?

**Comment by maciejwalkowiak** [comment]
Closed due to lack of feedback.
