### ISSUE TITLE
Consider upgrading aws sdk dependency to v2

### ISSUE THREAD

**Issue by anthofo** [spring-cloud/spring-cloud-aws#491]
An AWS java sdk v2 is available, the announcement post: https://aws.amazon.com/fr/blogs/developer/aws-sdk-for-java-2-x-released 
Since the announcement, more features have been added, here is the complete changelog: https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md

It brings some improvements that could not be fixed in v1.11.x since they are breaking changes.

For instance, the parsing of the `~/.aws/config` and `~/.aws/credentials` files has changed to be more close of the AWS CLI, the v1 java sdk and the current AWS CLI do not parse these files the same way, which can cause troubles.

**Comment by artembilan** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-aws/issues/267
