### ISSUE TITLE
Allow resolving AWS Parameter Store keys inside placeholders

### ISSUE THREAD

**Issue by behrangsa** [spring-cloud/spring-cloud-aws#494]
## Background

Let's assume that in my app's `application.yml` I have a property named `schedule`:

```yaml
schedule: "0 0 12 * * ? 2017"
```

I want to move this to Parameter Store.

To do that, I create `bootstrap.yml`:

```yml
aws:
  paramstore:
    default-context: demo
```

And then add the following parameter to Parameter Store: `/config/demo/schedule=0 0 12 * * ? 2017`. I also have to remove the `schedule` property from my `application.yml`.

This all works fine, however to a maintainer it is not immediately obvious that my app has a parameter named `schedule` that is defined in Parameter Store.

To work around that, instead of `/config/demo/schedule=0 0 12 * * ? 2017` I can add `/config/demo/paramstore.schedule=0 0 12 * * ? 2017` to Parameter Store and change my `application.yml` to:

```yaml
schedule: ${paramstore.schedule}
```

This lets maintainers know that the app has a parameter named `schedule`. It also gives a hint that its value is `${paramstore.schedule}`. 

## Feature request

Instead of the workaround above, similar to how Jasypt uses `ENC(...)` to decrypt encrypted values, post process and resolve values in the form of `PS(...)` from AWS Parameter Store.

For example:

```yaml
schedule: PS(schedule) # resolves to /config/demo/schedule
```

---

This is of course open for debate. One could argue that it is better not to explicitly refer to Parameter Store in property files to make them not locked in to a particular technology and instead use the workaround I have mentioned in the ticket.

**Comment by maciejwalkowiak** [comment]
I believe Spring Cloud AWS should stay consistent in this regard with other Cloud Config related implementations - this would mean that everything stays as it is and if needed workaround you provided can be used. What do you think @eddumelendez? How this is solved in Spring Cloud GCP?

**Comment by eddumelendez** [comment]
I think `AWS Parameter Store` is similar to `Runtime Config` in GCP but there is no similar implementation there regarding to feature request. Otherwise `Secret Manager` has the prefix `sm://` to revolve this properties key.

I have been also thinking about it the first time I saw this implementation but also found that make sense in favor of being explicit about where things are. Of course, the tread-off here is that the service will not portable to another environment per se. 

I think make sense to add this feature with the prefix `ps://this.is.the.key`.

**Comment by maciejwalkowiak** [comment]
Follow up, I have not seen any Spring Cloud project providing similar functionality - Vault, GCP or Spring Cloud Azure. I believe we should not implement this change cc: @eddumelendez

**Comment by eddumelendez** [comment]
just for the record https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/master/docs/src/main/asciidoc/secretmanager.adoc#secret-manager-property-source

gcp secretsmanager it does. I haven't use it and I have second thoughts on this. For now, I agree on not implementing this.

**Comment by maciejwalkowiak** [comment]
Considering that since 2.3 it's possible to load Parameter Store properties vis `spring.config.import=aws-parameterstore:` I think this issue can be closed.
