### ISSUE TITLE
stackResourceRegistryFactoryBean returns null value

### ISSUE THREAD

**Issue by reypader** [spring-cloud/spring-cloud-aws#496]
Encountering a problem with starting an application using `spring-cloud-starter-aws:2.1.0.RELEASE` with `cloud.aws.stack.auto = false`. The application encounters the following error:  

```Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'stackResourceRegistryFactoryBean' defined in class path resource [org/springframework/cloud/aws/autoconfigure/context/ContextStackAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.ClassCastException: org.springframework.beans.factory.support.NullBean cannot be cast to org.springframework.beans.factory.FactoryBean```

This is likely due to `org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration.stackResourceRegistryFactoryBean()` returning null.

```java
@Bean
    @ConditionalOnMissingBean(StackResourceRegistry.class)
    public StackResourceRegistryFactoryBean stackResourceRegistryFactoryBean(AmazonCloudFormation amazonCloudFormation) {

        if (StringUtils.hasText(environment.getProperty("cloud.aws.stack.name"))) {
            return new StackResourceRegistryFactoryBean(amazonCloudFormation, new StaticStackNameProvider(this.environment.getProperty("cloud.aws.stack.name")));
        }

        if (environment.getProperty("cloud.aws.stack.auto") == null || "true".equalsIgnoreCase(environment.getProperty("cloud.aws.stack.auto"))) {
            return new StackResourceRegistryFactoryBean(amazonCloudFormation, new AutoDetectingStackNameProvider(amazonCloudFormation, this.amazonEC2));
        }

        return null;
    }
```

Should this be changed to use `@ConditionalOnProperty("cloud.aws.stack.name")` and `@ConditionalOnProperty("cloud.aws.stack.auto")` ?

**Comment by JanGroot** [comment]
same issue in my project.

**Comment by maciejwalkowiak** [comment]
I am not able to reproduce it using 2.2.1 version. Could you please provide complete sample as a github repository that reproduces this issue?

**Comment by adannunez** [comment]
Running into the same issue. Just adding some more info that might be help troubleshoot.

I'm seeing the issue arise when `beanFactory.isSingleton("stackResourceRegistryFactoryBean")` is called and `StackResourceRegistryFactoryBean` is null due to the bean registration from the original post. In my case, the `isSingleton()` call is being made from a `BeanPostProcessor` provided by Axon. 

Not sure if this means the responsibility falls under `spring-cloud-aws`, another Spring team, or `Axon`. Hopefully someone here can provide a bit more direction.

```
Caused by: java.lang.ClassCastException: class org.springframework.beans.factory.support.NullBean cannot be cast to class org.springframework.beans.factory.FactoryBean (org.springframework.beans.factory.support.NullBean and org.springframework.beans.factory.FactoryBean are in unnamed module of loader 'app')
	at org.springframework.beans.factory.support.AbstractBeanFactory.isSingleton(AbstractBeanFactory.java:441) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.axonframework.spring.config.AbstractAnnotationHandlerBeanPostProcessor.postProcessAfterInitialization(AbstractAnnotationHandlerBeanPostProcessor.java:73) ~[axon-spring-4.3.3.jar:4.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:431) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
```

**Comment by maciejwalkowiak** [comment]
I think @reypader suggestion is valid:

`@ConditionalOnProperty("cloud.aws.stack.name")` and `@ConditionalOnProperty("cloud.aws.stack.auto")` with `havingValue=true` and `matchIfMissing=true` should do the job. PRs welcome!
