### ISSUE TITLE
Add support for message headers to NotificationMessagingTemplate

### ISSUE THREAD

**Issue by vghero** [spring-cloud/spring-cloud-aws#505]
I'm trying to get SNS message attribute filtering working using `NotificationMessagingTemplate`, but this does not seem supported yet. The methods in there only allow passing destination, message and subject. But no headers can be passed. Under the hood it's already possible though. There's already a feature request that goes into the same direction, but is targeting string arrays for filtering: https://github.com/spring-cloud/spring-cloud-aws/issues/368

What I've done to "workaround" is to extend `NotificationMessagingTemplate` and add an additional method for providing custom headers. Maybe something like that could find its way into an upcoming version? That would be great!

**Comment by zeldigas** [comment]
@vghero  take a look at 
```java
public <T> void convertAndSend(String destinationName, T payload,
			Map<String, Object> headers) throws MessagingException
```

**Comment by vghero** [comment]
Ok, seems I need new glasses :)! Thanks!

**Comment by dmitry-weirdo** [comment]
I actually have big doubts about `convertAndSend`, since custom headers do not work for SNS, and we have to set the custom message attributes instead. Is seems that custom attributes are not yet supported, or?
