### ISSUE TITLE
Non-Void return type with SqsListener throws java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Steffen911** [spring-cloud/spring-cloud-aws#514]
**Describe the bug**
Our application throws `java.lang.IllegalStateException: No handler for return value type: class java.lang.Object` exceptions for every received message.

Version:
Java: 1.8
Kotlin: 1.2.71
Spring Cloud: 
```
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-aws-messaging</artifactId>
            <version>1.1.3.RELEASE</version>
</dependency>
```

**Sample**
```kotlin
@SqsListener(value = ["sqs-queue"], deletionPolicy = ON_SUCCESS)
fun onMessageReceived(payload: String, @Header("TYPE") type: String): Any = when (type) {
    TYPE_A -> // do something
    TYPE_B -> // do something else
}
```

Since the when statement is also interpreted as an expression and we don't actually care about the returned value, we added the `Any` return type. Without this everything was fine and I assume that replacing `Any` with `Unit` would also be successful.

Nevertheless it should fail gracefully or ignore the returned value, if no `@SendTo` annotation is present.

**Additional Info**
Probably related to https://stackoverflow.com/questions/58632336/sqslistener-with-return-value-would-cause-exception

**Comment by maciejwalkowiak** [comment]
This behaviour is defined in Spring Messaging which is a part of Spring Framework. We are not able to amend it in Spring Cloud AWS as far as I can tell.
