### ISSUE TITLE
Support com.amazonaws.auth.profile.ProfileCredentialsProvider

### ISSUE THREAD

**Issue by noomkram** [spring-cloud/spring-cloud-aws#52]
Can support for ```com.amazonaws.auth.profile.ProfileCredentialsProvider``` be added within the ```<aws-context:context-credentials />```  namespace?  It would be convenient if credentials could be supplied via a profile name within a credentials file.

**Comment by jpoetker** [comment]
I agree.. The documentation says 

> The com.amazonaws.auth.DefaultAWSCredentialsProviderChain is used by all the clients if there is no dedicated credentials provider defined...

 but with RC2 this does not seem to be the case. The ```ContextCredentialsConfigurationRegistrar``` class seems to pretty aggressively decide that you are going to have static credentials or instance credentials, and no profile credentials. This is a deal breaker.

Is there away to disable the ```ContextCredentialsConfigurationRegistrar```? I tried excluding it, but did not have any luck.

**Comment by aemruli** [comment]
Hello @noomkram I will look into this to squeeze that into RC3. I think it is a valid use case.

**Comment by aemruli** [comment]
@jpoetker Did you exclude the org.springframework.cloud.aws.autoconfigure.context.ContextCredentialsAutoConfiguration class from your @EnableAutoConfiguration annotation ? 

I agree the documentation is misleading there, it was actually written before we had the auto configuration support. I will also look to integrate the profile credentials within the auto configuration.

**Comment by jpoetker** [comment]
@aemruli initially I tried excluding the registrar, but then figured out that I needed to try ```org.springframework.cloud.aws.autoconfigure.context.ContextCredentialsAutoConfiguration```. I didn't have any luck with either approach. I'm assuming because the latter gets included by other ```@Configuration``` classes.

I was also thinking a little bit about this, I'm a little knew to how the AutoConfiguration stuff works, but it seems like this approach would also make it very difficult for me to wire in my own implementation of ```CredentialsProvider```, which seems like a valid use case as well..

**Comment by aemruli** [comment]
@jpoetker I have added a support for the ProfileCredentialsProvider. Let me know if that does work for you, otherwise we can open a new ticket to allow custom CredentialsProvider to be configured in combination with auto-configuration

**Comment by jpoetker** [comment]
@aemruli Thanks, I'll check it out..

I was thinking again.. (dangerous for me) - There may be a better way to do what we need, I would think what we are doing is fairly common. Basically, I need to be able to run my spring-boot / aws-cloud app locally, outside of an EC2 container for development and testing. I still want to use AWS resources though. In this scenario the ```com.amazonaws.auth.DefaultAWSCredentialsProviderChain``` was working pretty great. (Locally we end up using ProfileCredentialsProvider, and in EC2 InstanceCredentialsProvider)

Maybe there is (or was already) a way to configure this up with spring profiles, but I wasn't seeing it.

**Comment by noomkram** [comment]
@aemruli works as advertised, thank you
