### ISSUE TITLE
Upgrade to version 2 of the Amazon SDK

### ISSUE THREAD

**Issue by gpmind** [spring-cloud/spring-cloud-aws#520]
**Describe the bug**
The amazon api endpoints have started warning about potential problems with using libraries coming from version 1 of the api. That's com.amazonaws:aws-... We can not use both revision of the API at the same time, there are numerous conflicts that arise from Spring Cloud dependencies starting with having 2 different SdkClientException classes to deal with.

**Sample**
You can make any standard test with asynchronous clients and you should get the mail.

**Comment by raoofm** [comment]
duplicate of #267 ?

**Comment by gpmind** [comment]
It certainly looks like it, and it's been hanging since 2016?

**Comment by maciejwalkowiak** [comment]
Indeed it's a duplicate of #267. You should be able to use SDK v1 and v2 in the same project.
