### ISSUE TITLE
SecretsManager Properties Are Ignored

### ISSUE THREAD

**Issue by cbriarnold-gmail** [spring-cloud/spring-cloud-aws#528]
**Describe the bug**
As of Spring-Cloud-Context-2.2.1.RELEASE, when an application is launched and both the Secrets Manager and and Parameter Store bootstrap properties are the same, the properties from the secrets manager get ignored. Upon inspecting the code, I found that in the PropertySourceBootstrapConfiguration.java class insertPropertySources method instead of adding the entire CompositePropertySource, it is going through each PropertySource in the composite and adding them in the list. Upon adding them to the MutablePropertySources, it does a check to see if the PropertySource with the same name already exists. Since both the AwsParamStorePropertySource and the AwsSecretsManagerPropertySource have the same name, it considers them equal and replaces the AwsSecretsManagerPropertySource using the AwsParamStorePropertySource created.

**Sample**
Bootstrap.properties
```
aws.secretsmanager.enabled=true
aws.secretsmanager.prefix=/prefix
aws.secretsmanager.name=appName
aws.paramstore.enabled=true
aws.paramstore.prefix=/prefix
aws.paramstore.name=appName
```
**Solution**
My suggestion would be to update the AwsParamStorePropertySource and the AwsSecretsManagerPropertySource to include the type of source in the name of the property source

**Comment by maciejwalkowiak** [comment]
@cbriarnold-gmail if I understood your issue right I think #564 should fix the problem. Can you take a look?

**Comment by maciejwalkowiak** [comment]
This issue has been fixed in Spring Cloud Commons project and is not present anymore when used with Spring Boot 2.3
