### ISSUE TITLE
SQSListener produces duplicates for the same message Id on fifo

### ISSUE THREAD

**Issue by gpmind** [spring-cloud/spring-cloud-aws#530]
**Describe the bug**
When using @SQSListener I notice duplicated calls done with the same message id from the same message standing as available in the queue. This is on a FIFO queue. I'm expecting not to receive duplicated messages which leads to further issues when we're queuing follow ups after processing.

I've tried the queue configured with no redrive which makes no difference.

**Comment by tristanessquare** [comment]
**Possible Workaround**

To solve the problem you could setup your SimpleMessageListenerContainer with a maxNumberOfMessages of 1. This configuration defines the max size of the batches that are received from each queue.

This configuration is global so you currently cannot setup queues with individual batch sizes. This solution also increases the number of calls to sqs and it reduces the throughput of messages as all messages are now processed sequentially.

**Possible Solution**

For FIFO queues group the messages received by messageGrouId and hand them over to the MessageExecutor. The MessageExecutor has to be extended in a way that it can process a list of messages sequentially.
