### ISSUE TITLE
cloud.aws.stack.auto 

### ISSUE THREAD

**Issue by shantgup** [spring-cloud/spring-cloud-aws#531]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

In ECS, when using the Fargate launch type, the application works fine. But in the EC2 launch type, it complains with this error:

`"com.amazonaws.services.cloudformation.model.AmazonCloudFormationException: Stack for i-0b56483f9029ab476 does not exist (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: 54e5b990-d2c7-4bbc-bfb0-d5f51cc166d0)" `

However, setting the cloud.aws.stack.auto to false explicitly in the "application.properties" resolves the issue. 

Note that there is no CloudFormation Stack, and no AutoScaling Group, so why does it look for one by default?

**Comment by maciejwalkowiak** [comment]
Spring Cloud AWS by default assumes application runs within Cloud Formation stack. If your application does not you should set `cloud.aws.stack.auto` to `false`.

We will reconsider the defaults.
