### ISSUE TITLE
Spring Cloud AWS Service autoconfiguration metadata

### ISSUE THREAD

**Issue by Ikki-Dai** [spring-cloud/spring-cloud-aws#535]
**Describe the bug**
while configure application.properties in IDE, the `spring-configuration-metadata.json` give error tips about `cloud.aws.credentials.access-key` property, actually `cloud.aws.credentials.accessKey` can work fine.

pls follow below to correct
`cloud.aws.credentials.access-key` -> `cloud.aws.credentials.accessKey`
`cloud.aws.credentials.secret-key` -> `cloud.aws.credentials.secretKey`

**version**
Spring Boot: 2.2.x
Spring Cloud: Hoxton.*

**Comment by maciejwalkowiak** [comment]
Kebab case properties in metadata are autogenerated from `@ConfigurationProperties` classes. The actual issue is that in few places like `ContextCredentialsAutoConfiguration` access key and secret key are retrieved directly from `Environment` rather than through `@ConfigurationProperties`.

**Comment by maciejwalkowiak** [comment]
Fixed in e805878a9268f721c2593a868877895098c39304
