### ISSUE TITLE
aws sqs exception while using spring cloud version Hoxton.SR3

### ISSUE THREAD

**Issue by ShefZee** [spring-cloud/spring-cloud-aws#546]
I have a simple program to send messages to SQS queue periodically. Please check the attachments for code. This is perfectly working for spring-cloud version Finchley.SR1, but NOT working with Hoxton.SR3.

I am getting the following exception while starting the application.
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.aws.core.env.ResourceIdResolver.BEAN_NAME': Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'stackResourceRegistryFactoryBean' defined in class path resource [org/springframework/cloud/aws/autoconfigure/context/ContextStackAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.aws.core.env.stack.config.StackResourceRegistryFactoryBean]: Factory method 'stackResourceRegistryFactoryBean' threw exception; nested exception is java.lang.IllegalArgumentException: No valid instance id defined`

[AwsSqsConfig.txt](https://github.com/spring-cloud/spring-cloud-aws/files/4518283/AwsSqsConfig.txt)
[MessagePublisher.txt](https://github.com/spring-cloud/spring-cloud-aws/files/4518284/MessagePublisher.txt)

**Comment by maciejwalkowiak** [comment]
Is application deployed with Cloud Formation? What value for `cloud.aws.stack.auto` property do you set? It would be great if you could post complete example together with your dependencies and `application.properties` file.

**Comment by maciejwalkowiak** [comment]
Please comment if problem still occurs.

**Comment by mmuniz75** [comment]
It works
