### ISSUE TITLE
Multiple SQS receives spring-cloud-aws-messaging with default config 2.2.1.RELEASE

### ISSUE THREAD

**Issue by hello-josh** [spring-cloud/spring-cloud-aws#548]
**Describe the bug**
I am seeing multiple receives on a single SQS message using the AWS GUI to add a message to the queue. I am running in a containerized environment and I will get 1 to 2 receives per container for a single message.

I am using the default configuration of `@SqsListener` on a controller method in spring boot with no xml based config and minimal java config:

```java
@Configuration
@EnableSqs
public class AwsConfig {

    @Bean
    public QueueMessagingTemplate queueMessagingTemplate(
            AmazonSQSAsync amazonSQSAsync) {
        return new QueueMessagingTemplate(amazonSQSAsync);
    }
}
```

```java
@Controller
@AllArgsConstructor
@Slf4j
public class SqsPollingController {

    private final ProjectWelcomeEmailService welcomeEmailService;

    @SqsListener(value = "${app.sqs.queue.welcome}", deletionPolicy = SqsMessageDeletionPolicy.ON_SUCCESS)
    public void welcomeEmailQueueListener(SendWelcomeEmailRequestDto welcomeEmailRequestDto) {
        log.info("Received welcome email request from SQS");
        welcomeEmailService.handleRequest(welcomeEmailRequestDto);
    }
}
```

My queue is configured as such:
![image](https://user-images.githubusercontent.com/638073/80638606-b4858780-8a2e-11ea-87b8-f72e6aa891bb.png)

Sends/Receives

![image](https://user-images.githubusercontent.com/638073/80639032-6d4bc680-8a2f-11ea-9f9c-95d77968b5c9.png)

What is going on? Does this library override message visibility to 0 on receive? I don't know where to put a breakpoint to find this.

**Comment by shashikanthgadgay0804** [comment]
Hi @hello-josh ,

Does this happen to all the messages or only few messages ? 

We are also facing a similar issue where the message isn't getting deleted after successful execution, hence message is being received 2 or 3 times.

**Comment by hello-josh** [comment]
Every message. I am in development phase so I am injecting one message at a time and I get 1 receive per running container all at the same time. I can't verify what is happening, but it seems as if the queue polling is overriding message visibility. It doesn't happen when I poll via the AWS UI or the AWS CLI on the same queue. I've even tried running one instance of my app in a debugger locally in IntelliJ and I get one per container plus one from my local. I can't seem to find the offending code that makes the SQS request

**Comment by sombhattacharyya1983** [comment]
@hello-josh   Have you tried playing with the **visibility timeout** setting ? I would suggest set it to 2 minutes or so  and see. Maybe in the code after you read the message you can set the timeout to a higher value and see ?

Ref : 
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html#configuring-visibility-timeout

**Comment by hello-josh** [comment]
> @hello-josh Have you tried playing with the **visibility timeout** setting ? I would suggest set it to 2 minutes or so and see. Maybe in the code after you read the message you can set the timeout to a higher value and see ?
> 
> Ref :
> https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html#configuring-visibility-timeout

I did review the setting. Visibility is set to 30 seconds. Please see my original bug report and the screen shot in it.

**Comment by maciejwalkowiak** [comment]
I am not able to reproduce this issue. Unless you are changing `SimpleMessageListenerContainer#visibilityTimeout` to `0`, this should not happen. If it's still the case, please provide fully working example ideally as a github repository and I am happy to take another look.

**Comment by hello-josh** [comment]
@maciejwalkowiak I moved this code into python/lambda instead. I couldn't figure it out and wasn't able to spend time on it. It seems the issue is when you have two or instances of the app running (i.e. two containers behind a load balancer). I am going to close this since I don't have code around to reproduce it any longer.

**Comment by maciejwalkowiak** [comment]
Thanks for an update. I did test with having multiple copies of application running and still only single copy of the message was being received.
