### ISSUE TITLE
Java config equivalent for aws-mail:mail-sender?

### ISSUE THREAD

**Issue by noomkram** [spring-cloud/spring-cloud-aws#55]
I couldn't find anything referenced in the documentation or browsing the source.

**Comment by aemruli** [comment]
Hello @noomkram, currently we have not an equivalent for that. You can write the class on your own 


    @Configuration
    public class MailSenderConfig {

	@Bean
	public JavaMailSender javaMailSender(AmazonSimpleEmailService amazonSimpleEmailService) {
		return new SimpleEmailServiceJavaMailSender(amazonSimpleEmailService);
	}
	
	@Bean(destroyMethod = "shutdown")
	public AmazonSimpleEmailServiceClient amazonSimpleEmailService(AWSCredentialsProvider credentialsProvider){
		return new AmazonSimpleEmailServiceClient(credentialsProvider);
	}
    }

**Comment by noomkram** [comment]
Understood, thank you.  Anything similar to:
```
@EnableContextResourceLoader
@EnableElasticCache
```
etc.

**Comment by joshuaherman** [comment]
Was this issue ever closed?

**Comment by maciejwalkowiak** [comment]
Thank you @noomkram for reporting. It's been a while. We have now autoconfiguration for SES (`MailSenderAutoConfiguration`) and there is no plan to invest anymore into `@EnableXXX` configuration.
