### ISSUE TITLE
Issue with Profile Separator

### ISSUE THREAD

**Issue by salah-java** [spring-cloud/spring-cloud-aws#554]
The Amazon AWS has possibility of adding '/' as profile separator.
I have secret names configured at AWS Secret Manager as
'/secret/application/configuration'

when I set '/' as profile separator, Bean validation triggers & application boot up fails.

Following are the logs

```
Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'aws.secretsmanager' to org.springframework.cloud.aws.secretsmanager.AwsSecretsManagerProperties failed:

    Property: aws.secretsmanager.profileSeparator
    Value: /
    Reason: must match "[a-zA-Z0-9.\-_]+"

```

Please add the '/' to allowed list of profile separators

**Comment by giova333** [comment]
I think that this pr should fix the issue https://github.com/spring-cloud/spring-cloud-aws/pull/466/commits/3336c98179c1d7a5d49cbb71af136e6374c8cfaa

**Comment by maciejwalkowiak** [comment]
I am wondering if there is any reason why we shouldn't allow `/` as profile separator in both Secrets Manager and Parameter Store integrations.
