### ISSUE TITLE
Add support to SimpleStorageResourceLoader for versioned S3 objects

### ISSUE THREAD

**Issue by robinhowlett** [spring-cloud/spring-cloud-aws#56]
Versioning in S3 is a means of keeping multiple variants of an object in the same bucket.

http://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html

Spring Cloud AWS Context supports loading resources using the convention `"s3://bucket/objectName"`

Context's `SimpleStorageResourceLoader` creates `SimpleStorageResources` by parsing the resource location string and splitting it into a bucket String and an objectName String. The Amazon S3 Client's `getObject` and `getObjectMetadata` methods are then passed the `bucket` and `objectName` Strings to return the S3 content and metadata respectively.

Amazon S3 is quite permissive in what characters are allowed in object names, but there is some guidance on using certain characters:

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

I propose that a convention is introduced that allows retrieving the resource of a particular version of an S3 object in a bucket that has versioning enabled, for example:

`"s3://bucket/objectName^versionId"`

If a `versionId` is not supplied for an object within a bucket with versioning enabled, the HEAD/latest version will be returned. If a `versionId` is not supplied for an object within a bucket without versioning enabled, the object is returned as normal.

**Comment by aemruli** [comment]
merged
