### ISSUE TITLE
Disable CloudFormation support by default

### ISSUE THREAD

**Issue by maciejwalkowiak** [spring-cloud/spring-cloud-aws#573]
CloudFormation is one of many ways to provision infrastructure on AWS. There are many reports from confused users who do not use CloudFormation and usually solution to their problem is turn disable `ContextStackAutoConfiguration`. To ease getting started experience and also make it simpler to use the framework for non-CloudFormation users `cloud.aws.stack.auto` should be `false` by default.

**Comment by eddumelendez** [comment]
this one can be address as part of https://github.com/spring-cloud/spring-cloud-aws/pull/582

**Comment by eddumelendez** [comment]
following this comment https://github.com/spring-cloud/spring-cloud-aws/pull/582#discussion_r439116322 As far as I can see, we can deprecate `spring-cloud-aws-context` in `2.3.x` and remove it `3.0.x`.
