### ISSUE TITLE
Drop dependency to javax.validation in Parameter Store and Secrets Manager 

### ISSUE THREAD

**Issue by maciejwalkowiak** [spring-cloud/spring-cloud-aws#576]
Both `spring-cloud-aws-parameter-store-config` and `spring-cloud-aws-secrets-manager-config` depend on `javax.validation:validation-api` to validate `@ConfigurationProperties` classes. This extra dependency can be dropped by making these classes implement `Validator` interface. 

More on how to do it: https://reflectoring.io/validate-spring-boot-configuration-parameters-at-startup/

**Comment by MatejNedic** [comment]
Hi, can i check this one?

**Comment by maciejwalkowiak** [comment]
@MatejNedic go for it!
