### ISSUE TITLE
Add option to set static region for Parameter Store and Secrets Manager integration

### ISSUE THREAD

**Issue by maciejwalkowiak** [spring-cloud/spring-cloud-aws#578]
Since Parameter Store and Secrets Manager integrations are not able to respect region configuration provided in `application.properties` we should allow users to set region explicitly for both Secrets Manager and Parameter store in `bootstrap.properties` file. This can be done by simply adding `region` property to `@ConfigurationProperties` classes and respect this property when creating clients.

It will fix #477

**Comment by tmnuwan12** [comment]
I will take a look. But needs some time to go through and I may ask questions :) Assign this to me.

**Comment by maciejwalkowiak** [comment]
@tmnuwan12 are you able to tackle it in foreseeable future? We are slowly getting to finishing 2.2.3 issues.

**Comment by eddumelendez** [comment]
Closing in favour of #616

**Comment by tmnuwan12** [comment]
@maciejwalkowiak didn't get time due to look at this. Sorry.
