### ISSUE TITLE
Create a Test Compile step for Spring Cloud AWS Integration Test in Circle CI 

### ISSUE THREAD

**Issue by DarrenForsythe** [spring-cloud/spring-cloud-aws#589]
**Is your feature request related to a problem? Please describe.**
Currently the the `spring-cloud-aws-integration-test` module is not defined as a module in the projects root pom, and manually needs to have a the `test-compile` phase ran on it to have some confidence that there are no checkstyle issues, and no compilation errors.

**Describe the solution you'd like**
While new integration tests are being proposed in gh-572 this module may be of value to continue to allow full E2E tests with AWS that Localstack may not be able to replicate, or produce a failing test. 

A solution would be to at least include the module in a Circle CI step to do a `test-compile`. This would at least catch any compilation and checkstyle/format issues. 

**Describe alternatives you've considered**
The module could be included in parent POM with the tests re-categorized to only execute with a given profile, or test annotation type. This would allow the maven reactor to at least execute every phase, minus the ITs unless specified. Keeping the project in sync and alleviating IDE issues or other gotchas

**Additional context**
N/A

**Comment by eddumelendez** [comment]
> While new integration tests are being proposed in gh-572 this module may be of value to continue to allow full E2E tests with AWS that Localstack may not be able to replicate, or produce a failing test.

Let's see how that works against `localstack`. But, totally agree we should enable this in the CI

I think we can use profiles so by default running against `localstack` using `testcontainers` and with a profile `aws-integration` against real aws instances.

/cc @maciejwalkowiak WDYT?

**Comment by DarrenForsythe** [comment]
There's a small PR that would solve this using JUnit5 Tag and an extra Maven profile that will exclude aws integration tests from running, while still compiling checkstyle etc as the module is now part of the reactor.

**Comment by maciejwalkowiak** [comment]
Thanks @DarrenForsythe! Fixed in https://github.com/spring-cloud/spring-cloud-aws/commit/f920fc35d4b4371ad9ea0c28ba5d6b7fa80518e7
