### ISSUE TITLE
SimpleMessageListenerContainer eats up exceptions without logging them

### ISSUE THREAD

**Issue by rahulpilani** [spring-cloud/spring-cloud-aws#59]
On line 194 of SimpleMessageListenerContainer, after the catching the exception, we should at least log it, otherwise, anyone looking at the logs will have no clue why a given message is being re-processed or thrown into the DLQ.

**Comment by rahulpilani** [comment]
Opened up a PR for this here: 
https://github.com/spring-cloud/spring-cloud-aws/pull/60

**Comment by aemruli** [comment]
Merged pull request
