### ISSUE TITLE
Deprecate @EnableX annotations

### ISSUE THREAD

**Issue by maciejwalkowiak** [spring-cloud/spring-cloud-aws#591]
Deprecate and eventually drop `@EnableX` annotations. Spring Cloud AWS has been created in pre-Spring Boot era where `@Enable` annotations was a very convenient way of configuring collection of beans in a declarative way. Since we are providing now auto-configuration for all our modules, we can drop `@Enable` annotations. It will bring following benefits:

- we can drop `Conditional` annotations provided by Spring Cloud AWS and use ones provided by Spring Boot
- we can drop a lot of factory beans code and use traditional Spring Boot autoconfigurations - this will make code much easier to approach for contributors
- we could use Spring Boot features when configuring integrations - since configuration will move completely to `autoconfigure` module (look SQS and SNS configuration)
- less confusion for users on how to use Spring Cloud AWS

I believe we should mark all `@Enable` annotations as deprecated in `2.3`, and drop them in `3.0`.

**Comment by maciejwalkowiak** [comment]
@eddumelendez your feedback is appreciated.

**Comment by eddumelendez** [comment]
As we were discussing, another benefit is `context` module can be optional too in 2.3 for `autoconfigure` module doing so. For further reference, new integrations should have their own module and/or autoconfiguration.

**Comment by maciejwalkowiak** [comment]
Fixed in https://github.com/spring-cloud/spring-cloud-aws/pull/606, https://github.com/spring-cloud/spring-cloud-aws/pull/615, https://github.com/spring-cloud/spring-cloud-aws/pull/636
