### ISSUE TITLE
AwsParamStorePropertySourceLocator gets extra contexts

### ISSUE THREAD

**Issue by audirob** [spring-cloud/spring-cloud-aws#596]
**Describe the bug**
The list of contexts is duplicated.

**Sample**
Given the following configuration:

> aws:
>  paramstore:
>       enabled: true
>       prefix: ''
>       profile-separator: '/'
>       default-context: ${spring.application.name}
>       fail-fast: false

I can see four contexts: 

![Screen Shot 2020-06-12 at 5 51 36 PM](https://user-images.githubusercontent.com/61826312/84521483-5dcdc780-acd5-11ea-8cc9-9d1e3a12c44d.png)

The contexts size should be 2 instead of 4.

**Comment by maciejwalkowiak** [comment]
Thanks for reporting it will be fixed in 2.2.3

**Comment by maciejwalkowiak** [comment]
Fixed in 582fdc6691ead7904aaed176af2cf85221edacd5 by @MatejNedic (https://github.com/spring-cloud/spring-cloud-aws/pull/602)
