### ISSUE TITLE
A way to configure Max Messages per SQS/SNS Listener.

### ISSUE THREAD

**Issue by froilan** [spring-cloud/spring-cloud-aws#618]
**Is your feature request related to a problem? Please describe.**
Our applications usually have listeners that have different needs. Some needs to be have low number of batching/max messages. And some are ideal to have larger batching/max messages.

If I understand correctly, when we configure `SimpleMessageListenerContainerFactory`, that sets the config for all the listeners in the application. Ideally there's a way to configure this on a per listener level.

**Describe the solution you'd like**
Maybe a way to override the max messages on a per listener level?

**Comment by mkatircioglu** [comment]
It seems that this is duplicated with #387. It would be better to close @maciejwalkowiak

**Comment by maciejwalkowiak** [comment]
Thanks @mkatircioglu you're right.
