### ISSUE TITLE
ResourceLoaderBeanPostProcessor trying to set applicationContext on ApplicationObjectSupport which has applicationContext already set

### ISSUE THREAD

**Issue by raviupreti85** [spring-cloud/spring-cloud-aws#62]
Beans extending ApplicationObjectSupport (that implements ApplicationContextAware) are being post processed by ApplicationContextAwareProcessor and ResourceLoaderBeanPostProcessor i.e. both try to set application context. Bean initialisation fails when application context is tried to set second time as ApplicationObjectSupport.setApplicationContext method throws an ApplicationContextException. One example of such a bean type is RequestMappingHandlerMapping. 

Maybe ResourceLoaderBeanPostProcessor should only set application context if it has not been already set.

**Comment by aemruli** [comment]
Thanks for reporting @raviupreti85 we will have a look at it.

**Comment by nathankurtyka** [comment]
+1

Awesome sleuthing by @raviupreti85  I just came here to submit this bug, and didn't do half the investigation he did!

**Comment by raviupreti85** [comment]
Thanks @nathankurtyka

**Comment by aemruli** [comment]
We are checking now that the bean is not of type ApplicationObjectSupport. I have alos opened an issue for Spring, so that we do not need to set application context in our post processor. 
https://jira.spring.io/browse/SPR-12857
