### ISSUE TITLE
Add spring-cloud-aws to user-agent for AWS metrics purposes

### ISSUE THREAD

**Issue by millems** [spring-cloud/spring-cloud-aws#628]
**Is your feature request related to a problem? Please describe.**
We at AWS would like to know when customers are using spring-cloud-aws.

We traditionally use user-agent metrics to identify features that customers are interested in or using, so that we can identify what features we should invest resources into. For example, when a customer uses S3 transfer manager, the user agent has a special string to say "I'm not just using the S3 client - I'm using the S3 transfer manager, which uses the S3 client". 

**Describe the solution you'd like**
Ideally, spring-cloud-aws would configure a [user-agent suffix](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#withUserAgentSuffix-java.lang.String-) of `spring-cloud-aws/${VERSION}` when the AWS clients are created. If spring-cloud-aws does not have access to the client when it is created, it can use `requestObject.getRequestClientOptions().appendUserAgent("spring-cloud-aws/${VERSION}")`, even though that's technically only documented for internal use.

**Describe alternatives you've considered**
Maven download numbers for spring-cloud-aws and Spring Initializr usages of spring-cloud-aws tell some of the story, but there's no substitute for actual usage and volume numbers, which AWS collects via user agents.

**Additional context**
We can help with a PR for this change request, if desired. This issue is just to kick off the feature request process.

**Comment by maciejwalkowiak** [comment]
@millems thanks for creating an issue. @eddumelendez just recently added a change that sets user agent: https://github.com/spring-cloud/spring-cloud-aws/commit/74743a581c5df92cfb17e2ff1a41ddce55f2bcef. We are going to release it with `2.2.3` which is very close to be ready.

**Comment by millems** [comment]
Awesome, thank you!

**Comment by eddumelendez** [comment]
@millems thanks for the report! Just want to let you know that we are using the `userAgentPrefix`

**Comment by millems** [comment]
@eddumelendez Would you mind using the `userAgentSuffix`? `userAgentPrefix` would override some of the other metrics that we usually include.

**Comment by eddumelendez** [comment]
sure! thanks for let us know. I will make the change later today.
