### ISSUE TITLE
Unsupported tag 'annotation-driven-queue-listener' 

### ISSUE THREAD

**Issue by elluard-doinglab** [spring-cloud/spring-cloud-aws#634]
I am willing to use spring cloud aws(2.2.2.RELEASE) on my server application 

I am using Spring 4.3.8.RELEASE 

When I use <aws-messaging:annotation-driven-queue-listener /> annotation like below but 
Unsupported tag 'annotation-driven-queue-listener'  message is shown.
How can I solve this problem

<img width="925" src="https://user-images.githubusercontent.com/49228039/88036183-2da00100-cb7e-11ea-9982-beb36d300d42.png">

<img width="830" src="https://user-images.githubusercontent.com/49228039/88035947-d0a44b00-cb7d-11ea-9e88-8c8605014ad5.png">

**Comment by maciejwalkowiak** [comment]
@elluard-doinglab in `schemaLocation` you're missing `xsd` suffix:

```
http://www.springframework.org/schema/cloud/aws/messaging/spring-cloud-aws-messaging.xsd
```

Ideally, do not use XML configuration as we are going to remove it in 2.3.

**Comment by elluard-doinglab** [comment]
@maciejwalkowiak 
the problem is solved, 
I tried to use Spring cloud aws version 1.x.x
Thank you for your helping
