### ISSUE TITLE
Set message structure for sns 

### ISSUE THREAD

**Issue by GooDGreY** [spring-cloud/spring-cloud-aws#64]
Within the org.springframework.cloud.aws.messaging.core.TopicMessageChannel#sendInternal method must be possibility to set MessageStructure property of the PublishRequest class. Otherwise, I can not send anything but a simple alert. But i want to send something like this:
{
"APNS": "{"aps":{"alert": "test","sound":"default"} }", 
"APNS_SANDBOX":"{"aps":{"alert":"'s'"}}", 
"GCM": "{ "data": { "message": "test" } }"
}
Sorry for my english, i hope you understand :)

**Comment by aemruli** [comment]
Hello @GooDGreY this has been solved with #31
