### ISSUE TITLE
Spring cloud aws jdbc forces Tomcat data pool, could Hikari be added?

### ISSUE THREAD

**Issue by jamesgustard** [spring-cloud/spring-cloud-aws#661]
Any Spring boot project will be using Hikari datapool as default , so when spring cloud aws jdbc is introduced to a spring boot project the datapool is switched over to tomcat.
 
The TomcatJdbcDataSourceFactory seems to rely on tomcat dataource configuration being present.
Could configurable  Hikari support be added, if it is not already possible to use Hikari?

**Comment by maciejwalkowiak** [comment]
Unfortunately Spring Cloud AWS JDBC module is bound to Tomcat connection pool. Please look into #610 for improvements plan to RDS integration.
