### ISSUE TITLE
Set specific region for every integration

### ISSUE THREAD

**Issue by eddumelendez** [spring-cloud/spring-cloud-aws#665]
**Is your feature request related to a problem? Please describe.**
Currently, we are not able to set a specific region for a given service.

**Describe the solution you'd like**
Add a region for every `ConfigurationProperties` which will be prioritized and in case it was not provided the the global region will be the fallback.

**Describe alternatives you've considered**

**Additional context**

**Comment by maciejwalkowiak** [comment]
@eddumelendez I believe this one can be closed?

**Comment by eddumelendez** [comment]
Yes.
