### ISSUE TITLE
Set specific credential for every integration

### ISSUE THREAD

**Issue by eddumelendez** [spring-cloud/spring-cloud-aws#666]
**Is your feature request related to a problem? Please describe.**
Currently, we are not able to set a specific credential for a given service.

**Describe the solution you'd like**
Add a credential for every `ConfigurationProperties` which will be prioritized and in case it was not provided the the global credential will be the fallback.

**Describe alternatives you've considered**

**Additional context**

**Comment by maciejwalkowiak** [comment]
I'm not convinced we should support it. What's the use case for that? I've never seen a project that needed multiple credentials.
