### ISSUE TITLE
Move to spring.cloud.aws prefix for configuration properties

### ISSUE THREAD

**Issue by eddumelendez** [spring-cloud/spring-cloud-aws#667]
**Is your feature request related to a problem? Please describe.**
Currently, there is a couple of prefixes in the project such as `cloud.aws` and `aws`.

**Describe the solution you'd like**
The project should provide consistency among the properties that are offered and the prefix should be `spring.cloud.aws` for every integration. In 2.3, backward compatibility should be added and the old ones are going to be removed in 3.0

**Describe alternatives you've considered**

**Additional context**

**Comment by MatejNedic** [comment]
Can I check this one up?

**Comment by mkatircioglu** [comment]
I offered that issue one or two months ago at gitter channel for release 3.0.0.M1. Wouldn't it be better to rename it for next major release for backward compatibility? @eddumelendez

**Comment by eddumelendez** [comment]
@MatejNedic thanks! Let's do it step by step instead of all at once. So, this issue can be address with multiple PRs.

@mkatircioglu what we have in mind is not rename them at 2.3.x, we will be offering the existing one plus the new one instead so people can migrate properly during 2.3.x instead. During this time we can benefit from `spring-boot-properties-migrator` module and in 3.0 we will be removing the previous ones. Since 3.0 is the major release then starting with prefix `spring.cloud.aws` and dropping the old ones make sense.

**Comment by eddumelendez** [comment]
@maciejwalkowiak your input is appreciate it.

**Comment by maciejwalkowiak** [comment]
@eddumelendez Considering timing, I think we should move it to 3.0 or 2.4 if we decide to release such version.
