### ISSUE TITLE
Need to have separate listener containers to start/stop message consumption from different queues when using the @MessageMapping annotation

### ISSUE THREAD

**Issue by subirparulekar** [spring-cloud/spring-cloud-aws#67]
Opening this feature request as suggested by Gary in the stackoverflow thread here:
http://stackoverflow.com/questions/29712212/how-to-programatically-start-stop-message-consumption-when-using-messagemapping

Looks like when using the @MessageMapping annotation, there is only one listener container to create listeners. So currently there is no way start/stop listening to the queues independently. Seems to be an all or none paradigm. It will be good to have the ability to be able to start/stop the consumptions on individual queues

**Comment by subirparulekar** [comment]
This also prevents you from being able to read from sqs queues in different regions in one deployment

**Comment by alainsahli** [comment]
Commit ccf3636042a8cfaafbc241b3690ae28566d19d3b adds new `start("queueName")` and `stop("queueName")` methods on the `SimpleMessageListenerContainer` to start/stop individual queues.

I close this issue and I created a new one for queues in different regions (#117).
