### ISSUE TITLE
Add samples

### ISSUE THREAD

**Issue by eddumelendez** [spring-cloud/spring-cloud-aws#675]
Provides a sample module `spring-cloud-aws-samples` which will contain every sub-module with a sample per every integration in the project.

* [ ] `spring-cloud-aws-elasticcache-redis-sample`
* [ ] `spring-cloud-aws-parameter-store-sample`
* [ ] `spring-cloud-aws-rds-sample`
* [ ] `spring-cloud-aws-s3-sample`
* [ ] `spring-cloud-aws-secrets-manager-sample`
* [ ] `spring-cloud-aws-ses-sample`
* [ ] `spring-cloud-aws-sns-sample`
* [ ] `spring-cloud-aws-sqs-sample`

Each sample should have tests and a readme file which provides steps to run it.

Pick your sample!

**Comment by h-hub** [comment]
hi @eddumelendez, may I start working on the ```spring-cloud-aws-secrets-manager-sample``` ?

**Comment by eddumelendez** [comment]
@h-hub great! `spring-cloud-aws-secrets-manager-sample` is your!

**Comment by h-hub** [comment]
Thanks @eddumelendez . I'll start working on this.

**Comment by h-hub** [comment]
@eddumelendez should I create a new module named ```spring-cloud-aws-samples```, put my sample under this module, and submit a pull request to branch 2.3.X ?

**Comment by yshameer** [comment]
@eddumelendez hi, may I start working on spring-cloud-aws-s3-sample?

**Comment by eddumelendez** [comment]
@yshameer sure, `spring-cloud-aws-s3-sample` is yours!

@h-hub yes, that module should be created and all the samples listed inside of it. When PRs are created we will handle conflicts or rebase properly.

Thanks!

**Comment by MatejNedic** [comment]
Hi @eddumelendez , can I take `spring-cloud-aws-parameter-store-sample`?

**Comment by sandeshdahake** [comment]
Hi @eddumelendez  is it ok if I work on spring-cloud-aws-sqs-sample ?

**Comment by h-hub** [comment]
@eddumelendez I submitted a pull request for ```spring-cloud-aws-secrets-manager-sample```. I would also like to start working on the ```spring-cloud-aws-ses-sample```. May I?
