### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by eddumelendez** [spring-cloud/spring-cloud-aws#676]
There are some tests which have not been migrated to use `ApplicationContextRunner`. It would be ideal to move them. Some of these test are:

* [ ] `AwsParamStoreBootstrapConfigurationTest`
* [ ] `AwsSecretsManagerBootstrapConfigurationTest`
* [ ] `ContextInstanceDataAutoConfigurationTest`
* [ ] `ContextRegionProviderAutoConfigurationTest`
* [ ] `ContextResourceLoaderAutoConfigurationTest`
* [ ] `CloudWatchExportAutoConfigurationTest`

Look at `SimpleEmailAutoConfigurationTest` for example.

Pick your test!

**Comment by MatejNedic** [comment]
Could I check CloudWatchExportAutoConfigurationTest for hacktoberfest?

**Comment by eddumelendez** [comment]
`CloudWatchExportAutoConfigurationTest` is all yours, @MatejNedic !

**Comment by mkatircioglu** [comment]
@eddumelendez I can get ContextInstanceDataAutoConfigurationTest if you are ok.

**Comment by eddumelendez** [comment]
@mkatircioglu Thanks for your offer! `ContextInstanceDataAutoConfigurationTest` is yours

**Comment by eberttc** [comment]
I’d like to check AwsSecretsManagerBootstrapConfigurationTest.

**Comment by eddumelendez** [comment]
@eberttc great! `AwsSecretsManagerBootstrapConfigurationTest` is yours!

**Comment by shashwat1998** [comment]
@eddumelendez can I get ContextResourceLoaderAutoConfigurationTest?

**Comment by eddumelendez** [comment]
@shashwat1998 of course! `ContextResourceLoaderAutoConfigurationTest ` is yours

**Comment by MatejNedic** [comment]
@eddumelendez since in #671 ApplicationContextRunner was introduced for CloudWatchExportAutoConfigurationTest and all tests were migrated to it, is it ok if I take AwsParamStoreBootstrapConfigurationTest

**Comment by gaurav9822** [comment]
@eddumelendez can I take ContextRegionProviderAutoConfigurationTest ?

**Comment by gaurav9822** [comment]
@eddumelendez Please also add "hacktoberfest" as a repo topic.

Notice from digital ocean about it- digitalocean/hacktoberfest#596

**Comment by maciejwalkowiak** [comment]
Thanks @gaurav9822 for the hint. We have no admin rights on the repo 🤷‍♂️. @spencergibb could you please add "hacktoberfest" to repo topics?

**Comment by spencergibb** [comment]
Done
