### ISSUE TITLE
spring AWS boot autoconfiguration breaks boot static content serving (for JSP) 

### ISSUE THREAD

**Issue by sodik82** [spring-cloud/spring-cloud-aws#68]
From http://docs.spring.io/spring-boot/docs/1.2.3.RELEASE/reference/htmlsingle/#boot-features-spring-mvc-static-content : 
> By default Spring Boot will serve static content from a directory called /static (or /public or /resources or /META-INF/resources) in the classpath or from *the root of the ServletContext*. 

However after adding the `spring-cloud-aws-autoconfigure` maven dependency the last option (ServletContext) stops to work, e.g. CSS files linked from webapp directory ends afterwards with HTTP 404.

Of course there are possible workarounds to place static content e.g. in /resource/static/ directory.

Sample project demostrating bug: https://dl.dropboxusercontent.com/u/34630863/aws-bug.zip
(based on spring-boot-samples). projects starts to work after removing AWS mvn dependency

**Comment by aemruli** [comment]
@sodik82 thanks for catching, much appreciated. I was able to reproduce the error and solve it. Please give the snapshot a try. Should be available in the next few mins.

**Comment by iscoolapp** [comment]
Hi @aemruli , I'm using snapshot 1.0.2 but this problem still occurs.

Thx in advance.

**Comment by sodik82** [comment]
hi, the "buggy" demo works well now; unfortunately, my original project was restructured so it is hard for me to get back in history :(

**Comment by iscoolapp** [comment]
Hi @aemruli !

Any news about this problem? 

I'm using snapshot 1.1.0 but this problem still occurs.

Thx!

**Comment by aemruli** [comment]
Hello @iscoolapp I just reopened the issue. We will check if we can reproduce it.

**Comment by aemruli** [comment]
Hi @iscoolapp  and @sodik82 I have changed the way how we work with the resource loader and hope that this change will fix your problems in any circumstances. I tried the provided sample app with success (even though that worked before 3ca473f change). 

I am closing this ticket now, please re-open if you ran into another issue with resource. 

Thanks!
