### ISSUE TITLE
404 not found spring-cloud-aws-context-1.0.xsd

### ISSUE THREAD

**Issue by kevinbheda** [spring-cloud/spring-cloud-aws#69]
I was referring  http://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html#_messaging  for aws sns notification to add sns  functionality in my office spring project. 
So i tried to setup aws sdk  xml configuration referring to this http://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html#_amazon_sdk_configuration
Basically  i added the schema depencies as specified in the link

```
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:aws-context="http://www.springframework.org/schema/cloud/aws/context"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/cloud/aws/context
        http://www.springframework.org/schema/cloud/aws/context/spring-cloud-aws-context-1.0.xsd">
```

Copied from example in spring aws doc:
```
<beans>
  <aws-context:context-credentials>
   <aws-context:simple-credentials access-key="xyz" secret-key="abc" >
  </aws-context:context-credentials>
</beans>
</beans>
```
But xml kept giving me error 
So i tried to load schema in browser
1.  http://www.springframework.org/schema/beans/spring-beans.xsd  - Response 200 ok  xml loaded.
2. http://www.springframework.org/schema/cloud/aws/context/spring-cloud-aws-context-1.0.xsd  - Response 404 not found. 

Am I doing something wrong over here or this a bug?

**Comment by dsyer** [comment]
It means the XSD hasn't been uploaded yet, so we can fix that. But you don't need to download the XSD to run your app, so the error must be from an XML editor or something (i.e. you can ignore it).

**Comment by kevinbheda** [comment]
I'm a newbie so dont have good knowledge of how xml definitions work so hard to digest "But you don't need to download the XSD to run your app"  can you give some reference link for understanding this ?

Please notify once you upload the xsd.
Thanks

**Comment by spencergibb** [comment]
@kevinbheda Besides the 404 is there some problem preventing you from working?

**Comment by kevinbheda** [comment]
@spencergibb well i had hard deadline delivery to complete aws sns functionality in half a day at work
so having very little time after i got xml editor and 404 error, i gave up and switched to aws java sdk. 
But would really like to use spring-aws sdk in future.

**Comment by aemruli** [comment]
I am closing this for now. As we have defined the spring.schemas correctly

**Comment by dsyer** [comment]
The 1.0 XSDs have been uploaded and symlinked, e.g. http://www.springframework.org/schema/cloud/spring-cloud-aws-context.xsd. The original poster seems to have lost interest, but this should never have stopped anyone from using the schemas.

**Comment by kevinbheda** [comment]
@dsyer  thanks for uploading the schema. I've been following this thread. I was a newbie at that time and did not know that i can ignore the xml editor error

**Comment by edwardsre** [comment]
@spencergibb The file located at http://www.springframework.org/schema/cloud/spring-cloud-aws-messaging.xsd references a dependent xsd which does not exist (`schemaLocation="http://www.springframework.org/schema/cloud/aws/context/spring-cloud-aws-context-1.0.xsd"`). The file is located here: http://www.springframework.org/schema/cloud/spring-cloud-aws-context.xsd.

It would be nice in IntelliJ to download the external resource, but as it is, it errors out when trying to fetch  the dependent xsd.
