### ISSUE TITLE
Publish Spring Boot metrics to Cloudwatch

### ISSUE THREAD

**Issue by aemruli** [spring-cloud/spring-cloud-aws#7]

**Comment by gtonic** [comment]
+1

**Comment by sachinlad** [comment]
Sorry, but I am confused about what milestone would this be part of? Also, if there are any dates around release? 

I am in need to do this and rather than creating something custom of my own it might be better to just wait.

**Comment by aemruli** [comment]
Hi @sachinlad we are publishing a 1.1 milestone next week and this PR will be part. 
We will merge this week into trunk. 

Sorry for the delay.

**Comment by sachinlad** [comment]
Nice to hear its available now. Are there any examples around how to configure it?

**Comment by sachinlad** [comment]
Is there any documentation or example code to reference it? It seems like most of the beans are auto-configured so enable this only involves setting some configuration to application.properties file? Is that correct?

**Comment by aemruli** [comment]
@sachinlad Indeed the documentation is unfortunately missing, we will create a updated version within the next releases. Do enable the metic export to Cloud Formation, you will need to configure the namespace with the property cloud.aws.cloudwatch.namespace

Have a look at the integration test https://github.com/spring-cloud/spring-cloud-aws/blob/master/spring-cloud-aws-integration-test/src/test/java/org/springframework/cloud/aws/metric/MetricExporterTest.java that is an integration test and export the metrics to cloud formation. 

Hope that helps, feel free to come back in case of any problems.

**Comment by nyashodhar** [comment]
What is the release date for this feature?
Presently, we incorporated this with the MileStone version.

Also, for Spring Metrics to be available to MetricExporter, we had to create the MetricsEndpointMetricReader bean. Is there a reason, why that is not part of the CloudWatchMetricAutoConfiguration?

How can we send Metrics with Dimensions? Will there be a provision to do that? At this point, looking at the code, we wont be able to do it. or am I missing something?

**Comment by gauravbrills** [comment]
any help with the docs on this or the ETA on release @aemruli

**Comment by gihad** [comment]
Any update on the questions asked by @nyashodhar?

**Comment by jonathannaguin** [comment]
@aemruli is there any documentation apart of that JUnit test?

**Comment by Frantch** [comment]
Where the hell is the document or sample on how to use these spring-cloud stuff?????

**Comment by gauravbrills** [comment]
I had implemented this long back and its pretty straight forward the autoconfiguration mostly takes care of all the heavy lifting I will post some snippets here once I get some time .
