### ISSUE TITLE
Allow prefix in spring-cloud-starter-aws-secrets-manager-config without forward slash

### ISSUE THREAD

**Issue by vamsi245** [spring-cloud/spring-cloud-aws#709]
**Is your feature request related to a problem? Please describe.**
spring-cloud-starter-aws-secrets-manager-config takes a prefix with a forward slash

**Describe the solution you'd like**
Change the class to accept prefix without forward slash. Some companies have policies to restrict secretsmanager creation with forward slash

**Describe alternatives you've considered**
None

**Additional context**
https://cloud.spring.io/spring-cloud-aws/2.1.x/multi/multi__cloud_environment.html

**Comment by eddumelendez** [comment]
we are discussing about naming properties keys in [this issue](https://github.com/spring-cloud/spring-cloud-aws/issues/607). I will close this in favor of that one.
