### ISSUE TITLE
SNS AutoConfiguration fail on non web application

### ISSUE THREAD

**Issue by VanRoy** [spring-cloud/spring-cloud-aws#73]
SNS AutoConfiguration require "WebMvcConfigurer" class on classpath.
It could be great that SNS can be autoconfigured on spring-batch context.

It can be possible to split in two class, the SNS Configuration and the WebMvc argumentResolvers injection.

Thanks.
Julien.

**Comment by aemruli** [comment]
Thanks @VanRoy for reporting. You should be now able to use the pre-configured AmazonSNS client to publish messages.

**Comment by VanRoy** [comment]
Thanks a lot, this is exactly what I needed.
