### ISSUE TITLE
Move AwsSecretsManagerProperties.PREFIX_PATTERN to Configuration Properties

### ISSUE THREAD

**Issue by venkat22** [spring-cloud/spring-cloud-aws#736]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
Some of our clients doesn't allow Prefix to start with '/'.  Moving it to properties will help us to override the same on need basis.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by eddumelendez** [comment]
As part of `spring-cloud-aws` 2.3, the following property `aws-secretsmanager:` or `aws-secretsmanager:my-secret-key` or
`aws-secretsmanager:my-secret-key;my-anoter-secret-key`. This will cover the request.

**Comment by adrian-morfi** [comment]
Hi @eddumelendez, 

How can I implement your solution?
Right now I have this:

bootstrap.properties
```
aws.secretsmanager.name=${SECRET_NAME}
aws.secretsmanager.prefix=/
```
pom.xml
```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-context</artifactId>
  <version>2.1.0.RELEASE</version>
</dependency>
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-aws-secrets-manager-config</artifactId>
  <version>2.1.0.RELEASE</version>
</dependency>
```

With my solution I am forced to prefix "/".
What version of my dependencies should I change and what change in my bootstrap.properties should I made.

**Comment by maciejwalkowiak** [comment]
@adrian-morfi use Spring Cloud AWS 2.3 https://spring.io/blog/2021/03/17/spring-cloud-aws-2-3-is-now-available

**Comment by adrian-morfi** [comment]
@maciejwalkowiak, it works! 

thanks!
