### ISSUE TITLE
Release 1.0.1.RELEASE not available on Maven Central

### ISSUE THREAD

**Issue by ddebree** [spring-cloud/spring-cloud-aws#74]
When attempting to access the artefacts on Maven Central, it appears that version 1.0.1.RELEASE is not available. Searching on Maven central only shows 1.0.0.RELEASE:
http://search.maven.org/#browse%7C-190486165

**Comment by aemruli** [comment]
@dsyer can you please check that issues and re-upload ? Thanks

**Comment by dsyer** [comment]
Done.
