### ISSUE TITLE
Spring Boot 2.4.x compatibility

### ISSUE THREAD

**Issue by WtfJoke** [spring-cloud/spring-cloud-aws#760]
Hi there,

Sorry for asking a question here since the [stackoverflow question I found](https://stackoverflow.com/questions/65564485/spring-cloud-aws-support-for-spring-boot-2-4) wasnt answered.
Is Spring Cloud AWS compatible with Spring Boot 2.4.x?

Because according to Spring Initilizr its not:
![grafik](https://user-images.githubusercontent.com/7139697/105467595-3345e300-5c96-11eb-8b13-338f98a68b0b.png)

Or is the 2.3.x spring cloud aws release the first one to bring compatibility with spring boot 2.4.x? 
If so, is there an ETA for 2.3.x?

Thank you!

**Comment by maciejwalkowiak** [comment]
Not yet. Spring Cloud AWS 2.3 is compatible with Spring Boot 2.4, it will be released very soon.

**Comment by joelhess** [comment]
I ended up bumping into this, by accident (didn't see the warning) but everything seems to be working. Is there a particular issue that you're concerned about compatibility, or is it just not tested?

**Comment by digimon1740** [comment]
> Not yet. Spring Cloud AWS 2.3 is compatible with Spring Boot 2.4, it will be released very soon.
> 
> I'll keep this issue open till 2.3 is released.

faster faster

**Comment by maciejwalkowiak** [comment]
@digimon1740 if all goes according to a plan, today Release Candidate!

**Comment by maciejwalkowiak** [comment]
@joelhess 2.2.x is built against Boot 2.3 and older Spring Cloud. It's not tested if it works with 2.4

**Comment by digimon1740** [comment]
> @digimon1740 if all goes according to a plan, today Release Candidate!

Thanks for your comment :) that sounds great

**Comment by maciejwalkowiak** [comment]
Spring Cloud AWS 2.3 RC2 has been released - https://maciejwalkowiak.com/blog/spring-cloud-aws-2-3-rc2-released/.

GA expected in a week. It would be great if you could use RC2 and give us feedback.

**Comment by D3jank** [comment]
I tested Spring Cloud AWS 2.3 RC2 with Spring Cloud Kafka and ran into the following issue: https://stackoverflow.com/questions/66371655/spring-cloud-kafka-and-aws-secrets-inputbindinglifecycle-exception

Any advice on how to fix that would be great!

**Comment by neiljbrown** [comment]
> @maciejwalkowiak
> I tested Spring Cloud AWS 2.3 RC2 with Spring Cloud Kafka and ran into the following issue: https://stackoverflow.com/questions/66371655/spring-cloud-kafka-and-aws-secrets-inputbindinglifecycle-exception
> 
> Any advice on how to fix that would be great!

@D3jank - posted some advice to Stackoverflow, which may or may not help. Regards.

**Comment by joshiste** [comment]
@maciejwalkowiak is there any schedule for the release?

**Comment by joelhess** [comment]
It's been released. Check out https://github.com/awspring/spring-cloud-aws

**Comment by denis111** [comment]
So this page should be updated https://spring.io/projects/spring-cloud-aws ...

**Comment by maciejwalkowiak** [comment]
@joshiste We have released 2.3.0, next step is official announcement and update sites. Thanks for patience and your feedback is very welcome!
