### ISSUE TITLE
Link to 2.3.0 documentation is broken

### ISSUE THREAD

**Issue by andrewedstrom** [spring-cloud/spring-cloud-aws#766]
**Type**: Bug

**Component**:
Documentation

**Describe the bug**
The link to the documentation for Spring Cloud AWS 2.3.0 is broken here:https://spring.io/projects/spring-cloud-aws#learn

I believe the link should be this: https://docs.awspring.io/spring-cloud-aws/docs/2.3.0-RC2/reference/html/index.html

**Comment by maciejwalkowiak** [comment]
Thanks for reporting, the link is fixed: https://docs.awspring.io/spring-cloud-aws/docs/current/reference/html/index.html
