### ISSUE TITLE
is v2.3.0 released?

### ISSUE THREAD

**Issue by andreas-trvlk** [spring-cloud/spring-cloud-aws#780]
Hi. I need compatible version for my Spring project which uses v2.4.x, especially for `spring-cloud-starter-aws-parameter-store-config`. I read that Spring Cloud AWS v2.3.x is the version that will compatible. But I cannot find it in the maven repository nor in the tag list. Do we have any additional news/step on how to use this v2.3.x?

**Comment by maciejwalkowiak** [comment]
Spring Cloud AWS 2.3 is released under new organisation: https://github.com/awspring/spring-cloud-aws

Read more: https://spring.io/blog/2021/03/17/spring-cloud-aws-2-3-is-now-available
