### ISSUE TITLE
Document that cloud.aws.region.static must be set if not running in AWS

### ISSUE THREAD

**Issue by Slooz** [spring-cloud/spring-cloud-aws#784]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
A lot of people seem to get confused by the following error:

> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3': Invocation of init method failed; nested exception is com.amazonaws.SdkClientException: Unable to load region information from any provider in the chain

#272, #251, #148

**Describe the solution you'd like**
While the error clearly points out the issue, the documentation doesn't make any mention of it. It has been said many times on GitHub issues, but it should also be documented:
https://github.com/spring-cloud/spring-cloud-aws/issues/148#issuecomment-218163733, https://github.com/spring-cloud/spring-cloud-aws/issues/272#issuecomment-397757049, https://github.com/spring-cloud/spring-cloud-aws/issues/339#issuecomment-636503818

**Describe alternatives you've considered**
I searched through GitHub for the recommended way to solve this issue, but that's not ideal

**Comment by maciejwalkowiak** [comment]
Replaced with https://github.com/awspring/spring-cloud-aws/issues/173
