### ISSUE TITLE
Getting Cannot find cache named 'xxx' for CacheableOperation

### ISSUE THREAD

**Issue by maxsap** [spring-cloud/spring-cloud-aws#80]
Hello I have an application using Spring-boot-jersey, Spring-data and spring cloud aws, among other things I need to use the ElastiCache integration but whenever I configure it I am getting the above error, to me it looks like there is some kind of context mixing where the ElastiCache is not able to find the configured caches.
My project consists of multiple maven sub-modules as below:
backend:
-API
-Admin
-----Domain
-----Core services

The API and Admin modules expose an executable WAR file and add extra dependencies and configurations.

My configuration for the caching is the following: 

 > /*
  >*  by default we need to skip elasticache auto config because its going to cause IllegalArgument   exceptions due to cache not found.
>   */
 >       @Configuration
  >      @EnableAutoConfiguration(exclude = {ElastiCacheAutoConfiguration.class})
>        public class CacheConfiguration {
>
>	@Configuration
>        @EnableCaching
 >       protected static class LocalCacheConfiguration {
>
>        @Bean
>        public CacheManager createSimpleCacheManager() {
>            SimpleCacheManager simpleCacheManager = new SimpleCacheManager();
>            List<Cache> caches = new ArrayList<>(2);
>            caches.add(new ConcurrentMapCache("publicFeed"));
>            caches.add(new ConcurrentMapCache("OAuthTokenCache"));
>            caches.add(new ConcurrentMapCache("privateFeed"));
>            simpleCacheManager.setCaches(caches);
>
>            return simpleCacheManager;
>        }
>
>    }
>	
>    @Configuration
>    @EnableElastiCache
>    @Profile("LIVE")
>    protected static class ElastiCacheConfiguration {
>
>    }
>}

Whenever I am running tests on the domain module the caching works as expected and the cache is found, but whenever I am booting the application (running the API module) I am getting the following message:
*Getting Cannot find cache named 'xxx' for CacheableOperation
after some debugging I thing this is something regarding different contexts where the cache provider gets confused and does not use the correct caches.
Also if I manually autowire the cacheManager and request a cache, then it works as expected.

**Comment by aemruli** [comment]
Hi @maxsap, I have two questions here 

- Do you run inside a CloudFormation stack with your application ? 
- Have you tried to configure the cache names with the @EnableElastiCache annotation ? 

We are only auto-detecting all caches if you are running inside a stack, otherwise you have to declare the cache manually (e.g. @EnableElastiCache({@CacheClusterConfig(name = "publicFeed", expiration = 23), @CacheClusterConfig(name = "OAuthTokenCache", expiration = 42)})

**Comment by maxsap** [comment]
Hello @aemruli,

No I haven't because the issue that I am mentioning appears in my local setup where the local cacheManager bean should be used.

**Comment by aemruli** [comment]
Hello @maxsap, I think in your setup you can leave the local cache configuration. For the Elasticcache (in your "LIVE" profile) you need to explicitly configure the cache clusters you want to use from Amazon Elasticache. 

With the changes mentioned in my previous comment you should be able to leverage the profile for local and ElastiCache caching.

**Comment by aemruli** [comment]
Closing for now, as the behavior seems correct. Please re-open if there are any findings.

**Comment by jeffxor** [comment]
So we are having a similar issue that it can not find the CacheCluster "Cannot find cache named 'CacheCluster' for CacheableOperation".  It is obviously a misconfiguration on my end I am just not sure what the @CacheClusterConfig name should be set to. Below is an screenshot of our clusters. Also we are using Redis.

<img width="1233" alt="screen shot 2015-08-18 at 11 43 37 pm" src="https://cloud.githubusercontent.com/assets/1331890/9348911/5e500f80-4603-11e5-990b-5d64a6756464.png">

**Comment by maxsap** [comment]
I managed to trace the source of the issue and would like to post it here if anyone faces the same issue in the future.
Turns out that this was not an issue with Spring-AWS but with spring-boot configuration, there where multiple EnableAutoconfiguration annotations mixed with SpringBootApplication ones that where creating issues.

**Comment by ajainy** [comment]
Hi, 
I am also stuck on similar issues. I am running application locally. But I created "memcached" backed elasticache cluster on aws. But I am not able to connect to that instance from my local laptop. I am running as spring-boot app. I configured right aws credentials in property file etc.
But everytime, I run application, cachemanager is default simple-cache manager and concurrent hashmap as caches.

**Comment by yamanyar** [comment]
I had the same problem. In my case solution was to exclude auto configuration in application as displayed below:
```java
@EnableAutoConfiguration(exclude = ElastiCacheAutoConfiguration.class)`
```
and then manually define as below:

```java
@Configuration
@EnableElastiCache({@CacheClusterConfig(name = "dev-cache")})
@Profile("!local")
public class ClusterCache {

}
```
You can also define cache for your local execution such: 
```java
@Configuration
@EnableCaching
@Profile("local")
public class LocalCache {
    @Bean
    public CacheManager createSimpleCacheManager() {
        SimpleCacheManager simpleCacheManager = new SimpleCacheManager();
        List<Cache> caches = new ArrayList<>(2);
        caches.add(new ConcurrentMapCache("dev-cache"));
        simpleCacheManager.setCaches(caches);
        return simpleCacheManager;
    }
}
```
Instead of "dev-cache", use your cluster name. Of course; using a spring expression is a must if you have dev/prod environments.

**Comment by kxd195** [comment]
I'm pulling my hair out on this... not sure why but I'm also getting CacheClusterNotFound.

My AWS cache is fs-redis-cache. I have inbound TCP port 6379 for anywhere 0.0.0.0/0 on the EC2 security group.

My Application.java has:
`@EnableAutoConfiguration(exclude = ElastiCacheAutoConfiguration.class)`

My CacheConfig.java has:
`@Configuration
@EnableElastiCache({@CacheClusterConfig(name = "fs-redis-cache")})
public class ClusterCache {

}`
