### ISSUE TITLE
Using different ElastiCache clusters across environments

### ISSUE THREAD

**Issue by mwielansky** [spring-cloud/spring-cloud-aws#81]
We are looking to implement ElastiCache using the Cacheable annotation, however we cannot find an approach to add some indirection between the name defined in the annotation and the configured cache cluster name in AWS. In our case, we'd like the application deployed to our test servers to reference a test cache cluster and the prod servers to reference prod. Both sets of servers are running on the same AWS account.  Please add a feature request to add SPeL support to the cache cluster name. If you have any other suggestions, please let us know. Thank you in advance.

**Comment by aemruli** [comment]
Hello @mwielansky, thanks for you issue. I would propose to use CloudFormation stack. Then you can basically reference to the CloudFormation cache name. Based on the stack which is running, this will then point to the physical cache. Have a look at our cache configuration in the integration test suite (https://github.com/spring-cloud/spring-cloud-aws/blob/master/spring-cloud-aws-integration-test/src/test/resources/IntegrationTest.template). 

There we have a cache configuration for memcached and also redis 

```
 "CacheCluster": {
    "Type": "AWS::ElastiCache::CacheCluster",
    "Properties": {
        "CacheNodeType": "cache.t1.micro",
        "CacheSecurityGroupNames": [
        {
                "Ref": "CacheSecurityGroup"
        }
        ],
              "Engine": "memcached",
              "NumCacheNodes": "1"
        }
 },
 "RedisCacheCluster": {
      "Type": "AWS::ElastiCache::CacheCluster",
      "Properties": {
           "CacheNodeType": "cache.t1.micro",
           "CacheSecurityGroupNames": [
              {
                    "Ref": "CacheSecurityGroup"
               }
           ],
            "Engine": "redis",
           "NumCacheNodes": "1"
 }
```

then you can reference to those "logical" names inside your code. The stack can be started multiple times for your stages.

```
        @Cacheable("CacheCluster")
	public String expensiveMethod(String key) {
	}
```

**Comment by aemruli** [comment]
Leaving the ticket open, to check if we can do expression resolution. Maybe that will be forwarded to Spring Framework...

**Comment by aemruli** [comment]
I am closing this ticket, @mwielansky you should either use the stack, or you will have to wait until https://jira.spring.io/browse/SPR-13332 have been fixed.
