### ISSUE TITLE
Make @MessageMapping Spring Expression Language aware

### ISSUE THREAD

**Issue by elruwen** [spring-cloud/spring-cloud-aws#84]
Hi!

I am not sure if this project or the spring-messaging project is the right place, but since the resolution of the content of the @MessageMapping annotation currently happens in the QueueMessageHandler which belongs to this project, I will give it a try here.

Currently I can specify a queue name using the @MessageMapping annotation. We have a dev environment in which each developer has it's own stack to play around. So the logical queue name myqueue exists several times per environment, each time with a prefix or something. I would like to be able to use something like @MessageMapping("${my.queue.name.property}").

To get things going I subclassed the QueueMessageHandler the following way at the moment:
```java
    @Autowired
    private Environment environment;

    @Override
    protected MappingInformation getMappingForMethod(Method method, Class<?> handlerType) {
        MappingInformation original = super.getMappingForMethod(method, handlerType);
        if (original != null) {
            Set<String> resolvedResourceIds = new HashSet<>(original.getLogicalResourceIds().size());
            for (final String resourceId : original.getLogicalResourceIds()) {
                final String resolvedResourceId;
                if (resourceId.startsWith("${") && resourceId.endsWith("}")) {
                    String propertyName = resourceId.substring(2, resourceId.length() - 1);
                    resolvedResourceId = environment.getRequiredProperty(propertyName);
                } else {
                    resolvedResourceId = resourceId;
                }
                resolvedResourceIds.add(resolvedResourceId);
                LOGGER.info(LoggingFormatter.formatEvent("Detecting MessageMapping annotation for queue {}"), resolvedResourceId);
            }
            return new MappingInformation(resolvedResourceIds);
        }
        return null;
    }
```

It is a little bit hacky and supports only properties. I have no idea how to integrate the Spring Expression language, otherwise I would also have added a pull request ;)

Would be nice to have that feature in future.

Cheers
Ruwen

**Comment by alainsahli** [comment]
Hi @elruwen 

This was already implemented with issue #43.
