### ISSUE TITLE
Warning "'java.util.UUID' cannot be sent as message attribute ..." on any request sent to SQS channel

### ISSUE THREAD

**Issue by frederikheremans** [spring-cloud/spring-cloud-aws#86]
When sending a messages using the AWS `QueueMessagingTemplate`, a warning is logged every time:

```
WARN  o.s.c.a.m.core.QueueMessageChannel - Message header with name 'id' and type 'java.util.UUID' cannot be sent as message attribute because it is not supported by SQS.
```

Logged from:
`org.springframework.cloud.aws.messaging.core.QueueMessageChannel#getMessageAttributes`

The issue is that the `MessageHeaders` always includes an id header of type UUID. I can do some magic before the Message actually reaches this point of the code, but there is no way of creating `MessageHeaders` without an ID.

Changing log level works, and not having the generated ID as part of the SQS message attributes is fine - but it would make sense to ignore the ID header and not log.

**Comment by CyborgMaster** [comment]
I have this same problem.  I seems like spring cloud aws should be responsible for making sure any headers generated should match what is sent to SQS without throwing warnings.

**Comment by CyborgMaster** [comment]
Awesome thanks!  Where should I look to monitor for an official release to maven central?

**Comment by apryce** [comment]
We are still seeing this in 1.0.4.RELEASE. Was there maybe a regression?
