### ISSUE TITLE
@EnableElastiCache values not being picked up correctly

### ISSUE THREAD

**Issue by jeffxor** [spring-cloud/spring-cloud-aws#93]
So we are having a similar issue that it can not find the CacheCluster "Cannot find cache named 'CacheCluster' for CacheableOperation".  It is obviously a misconfiguration on my end I am just not sure what the @CacheClusterConfig name should be set to. Below is an screenshot of our clusters. Also we are using Redis.

I have tried the following:-
    @EnableElastiCache({@CacheClusterConfig(name = "CacheCluster", expiration = 23)} )
    @EnableElastiCache({@CacheClusterConfig(name = "cachecluster", expiration = 23)} )
    @EnableElastiCache({@CacheClusterConfig(name = "cachecluster-001", expiration = 23)} )

<img width="1233" alt="screen shot 2015-08-18 at 11 43 37 pm" src="https://cloud.githubusercontent.com/assets/1331890/9348911/5e500f80-4603-11e5-990b-5d64a6756464.png">

From further investigation it appears that during configuration of the ElastiCacheCachingConfiguration the values inside are not picked up correctly forcing the CachingConfigurer cachingConfigurer method to always attempt to getConfiguredCachesInStack() rather than use the cache names provided in the annotation.

**Comment by aemruli** [comment]
Hello @jeffxor could you please try to collapse the caches into on @EnableElastiCache annotation.

  @EnableElastiCache({
  @CacheClusterConfig(name = "cachecluster-001", expiration = 23),
  @CacheClusterConfig(name = "cachecluster-002", expiration = 23)} )

That should make all two caches available in your screenshot.

**Comment by jeffxor** [comment]
Sorry that was just showing the different names of the CacheClusters we were trying as we where unsure what the name should when not created using CloudFormation. To be clear we only have one

    @EnableElastiCache({@CacheClusterConfig(name = "CacheCluster", expiration = 23)} )

in our configuration. We are not seeing get configured correctly through the Java Config. However, we switched off the AutoConfiguration and configured it through xml and it works. The below line is not setting the correct values 

    this.annotationAttributes = AnnotationAttributes.fromMap(importMetadata.getAnnotationAttributes(EnableElastiCache.class.getName(), false));

for this line to be executed

    if (this.annotationAttributes != null && this.annotationAttributes.getAnnotationArray("value").length > 0) {
         return new ElastiCacheCacheConfigurer(amazonElastiCache, resourceIdResolver,
       getCacheNamesFromCacheClusterConfigs(this.annotationAttributes.getAnnotationArray("value")), cacheFactories);
    }

**Comment by aemruli** [comment]
@jeffxor I just followed up on this issue and tried to reproduce. I am not sure that I get the correct error but let me try to explain. 

You can use the @EnableElastiCache with pre-configured cache names. Those can be names of caches which are available without a stack and names within the current stack. 

@EnableElastiCache({@CacheClusterConfig(name = "firstCache"), @CacheClusterConfig(name = "secondCache")})

I checked your comment about the wrong code line and the code seems to work okay, we have a test for this in org.springframework.cloud.aws.cache.config.annotation.ElastiCacheCachingConfigurationTest#enableElasticache_configuredWithExplicitCluster_configuresExplicitlyConfiguredCaches


Do you use the spring-cloud-aws-autoconfigure support ? If so then please try disabling that. I am closing this ticket for now feel free to open in case of more information.
