### ISSUE TITLE
spring-cloud-starter-aws 1.0.3 with 1.0.2 spring cloud aws dependencies

### ISSUE THREAD

**Issue by altfatterz** [spring-cloud/spring-cloud-aws#94]
`compile("org.springframework.cloud:spring-cloud-starter-aws:1.0.3.RELEASE")` 
pulls in 1.0.2 spring cloud aws project dependencies. Is this intentional?

**Comment by aemruli** [comment]
Hello @altfatterz, yes this was indeed intentional as the starters were ahead (e.g. starter 1.0.3 used 1.0.2 deps). This should not happen in the future anymore as the starters have been moved to the respective project and are version along with them.
