### ISSUE TITLE
Java equivalent for aws-context:context-resource-loader?

### ISSUE THREAD

**Issue by mhottinger1** [spring-cloud/spring-cloud-aws#95]
I used the following documentation to wire BasicAWSCredentials, KMSEncryptionMaterialsProvider, ClientConfiguration, and CryptoConfiguration into an AmazonS3EncryptionClient via XML configuration:

[Spring Cloud AWS IO Guides](http://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html)

The last line of my XML configuration is something similar to:

`<aws-context:context-resource-loader amazon-s3="myAmazonS3EncryptionClientBean"/>`

Once I had everything wired-up using XML, I began refactoring in order to use all Java configuration, but couldn't figure out how to express the `<aws-context:context-resource-loader>` bean above in Java. I took a peek at the documentation and source, but nothing stood out. Any help/suggestions are appreciated!

**Comment by mhottinger1** [comment]
After some internal research and discussions I was able to express `<aws-context:context-resource-loader amazon-s3="myAmazonS3EncryptionClientBean"/>` in Java configuration by autowiring a `ResourceLoaderBeanPostProcessor` that takes an `AmazonS3` object in it's constructor. 

```
@Bean
@Autowired
public static ResourceLoaderBeanPostProcessor resourceLoaderBeanPostProcessor(
            AmazonS3Client amazonS3EncryptionClient) {
        AmazonS3 amazonS3 = amazonS3EncryptionClient;
        return new ResourceLoaderBeanPostProcessor(amazonS3);
}
```
*Note*: This applies to 1.0.3.RELEASE+

**Comment by apogrebnyak** [comment]
In 1.1.3.RELEASE look at @EnableContextResourceLoader annotation.

I do think this should be covered in reference documentation
