### ISSUE TITLE
Has 1.0.3.RELEASE been formally released?

### ISSUE THREAD

**Issue by eddgrant** [spring-cloud/spring-cloud-aws#97]
Just curious as I can see the 1.0.3 artefacts in Maven central however [the website](http://cloud.spring.io/spring-cloud-aws/) still lists 1.0.3 as snapshot and I can't find any change logs or release notes/ announcements?

**Comment by dsyer** [comment]
The website needs to be updated. I'll do that now, thanks.

**Comment by eddgrant** [comment]
Thanks, I can see the website has now bee updated. Is there a change log anywhere or should I just diff the {{1.0.2.RELEASE}} branch and the {{v1.0.3.RELEASE}} tag?

**Comment by dsyer** [comment]
We don't maintain release notes for this project AFAIK (maybe @aemruli has something?). You can get a list of issues resolved from github.
